balena-io/etcher

- build/browser/app.js
- lib/browser/app.js
The issue is fixed by stopping the drive scanner interval before
burning.
> Fix EPERM issue when burning in Windows

- package.json
This version contains a fix that allows Herostratus to be correctly
elevated when running with `npm start`.
See fix here:
https://github.com/jorangreef/sudo-prompt/commit/344da8f7b2325460f19353ff2dbcf59f92a89426
> Upgrade sudo-prompt to v1.1.8

- package.json
This version is the last one that works on GNU/Linux.
> Downgrade to Electron v0.31.2

- lib/elevate.js
Currently, the parent application will not be closed until the children
process is closed, leading to two Herostratus applications running at
the same time on OS X.
> Fire and forget OS X sudo prompt

- Makefile
This was the last known version to work on Ubuntu.
See https://github.com/resin-io/herostratus/pull/10
> Package Electron with 0.31.2

- Makefile
This change fixes the following issues:
- https://github.com/resin-io/herostratus/issues/17
- https://github.com/resin-io/herostratus/issues/18
> osx(package) Build without --asar

- PUBLISHING.md
This is needed to avoid optional dependencies not being installed.
See https://github.com/resin-io/herostratus/issues/22
> Document the need of npm install --force

- lib/elevate.js
- lib/herostratus.js
- package.json
Currently we fire and forget `sudoPrompt.exec()` and run a timeout for
`process.exit(0)` right away, however this means that the timeout will
start as soon as the elevation dialog is shown when no sudo cache exists
and therefore the timeout will finish before the user can type his
password and submit.
The fix is to keep the parent alive until the children dies, but call
`app.dock.hide()` to make the parent completely invisible to the
operating system.
Fixes: https://github.com/resin-io/herostratus/issues/31
> osx: Fix first time elevation failure

- build/browser/app.js
- lib/browser/app.js
- lib/index.html
Physical drive names are long and cause the dropdowns to overflow.
Fixes: https://github.com/resin-io/herostratus/issues/23
> win32: Show drive letter instead of device in dropdown

- package.json
This version contains a fix for a cmd.exe window popping in for a
fraction of a second when elevating Herostratus on Windows.
Fixes: https://github.com/resin-io/herostratus/issues/39
> Upgrade windosu to v0.2.0

- package.ignore
The issue is that the `windosu-elevate.cmd` script that `windosu`
internally calls to perform the elevation.
After some investigation this is due one of our ignore regular
expressions used to filter out unnecessary files from the production
package:
```
(.*).md
```
The period matches anything but a space, causing file ending in `cmd` to
be matched, and therefore excluded from the package.
Since the intention of this regex was to match a literal period,
escaping does the trick.
Partly-Fixes: https://github.com/resin-io/herostratus/issues/20
> Fix Windows not asking for elevation when packaged

- Makefile
- package.json
The following libraries were upgraded to versions that include this fix:
- electron-prebuilt
- drivelist
Fixes: https://github.com/resin-io/herostratus/issues/35
Fixes: https://github.com/resin-io/herostratus/issues/18
> Fix drivelist spawn issues inside asar package

- build/browser/app.js
- build/css/main.css
- lib/browser/app.js
- lib/index.html
- lib/scss/main.scss
This PR includes various improvements:
- Prevent white flash when running application
- Implement poor man's ngCloak based on app controller
- Use ngBind instead of curly braces interpolation
Fixes: https://github.com/resin-io/herostratus/issues/62
> Prevent flash of unstyled content at startup

- lib/index.html
Showing `\\.\PhysicalDriveN` makes no sense for a Windows user after
selecting based on drive letters on the dropdown.
> Show drive letter on selection on Windows

- lib/elevate.js
- package.json
For some reason, when using `windosu`, the app is elevated three times.
However this only happens when the application is packaged for
distribution.
After a couple of days debugging this issue, we have no clue about
what's going on, but `elevator` seems to work fine.
Fixes: https://github.com/resin-io/herostratus/issues/29
> Replace windosu with elevator

- README.md
An update was needed after renaming the project to `resin-etcher`.
> Update Appveyor badge

- lib/index.html
After checking Windows file manager and some other programs that display
drive letters, we can see that a backslash at the end is not mandatory.
> Do not append a backslash after drive letter in Windows

- build/browser/app.js
- lib/browser/app.js
- lib/index.html
- package.json
The `drivelist` module includes a new property called `name` in `2.0.7`
that resolves to the drive letter (mount point) on Windows, and to the
drive otherwise.
> Simplify drive letter / device conditional

- .travis.yml
- appveyor.yml
We're only targetting Electron, which uses only modern versions of
NodeJS.
> Only target v4 in CI servers

- .jshintrc
Hound CI uses it's default otherwise, which is too short.
> Set an explicit maxlen

- lib/etcher.js
JSHint complains about `Window` as a redefinition warning.
> Require electron-window as ElectronWindow

- build/browser/app.js
- lib/browser/app.js
- lib/browser/modules/selection-state.js
- lib/index.html
- tests/browser/modules/selection-state.spec.js
You can click on the selected image/drive label to select them again.
The re-selection is disabled if there is a burning in process.
Fixes: https://github.com/resin-io/resin-etcher/issues/90
> Allow to re-select the first two step selections

- lib/browser/modules/image-writer.js
- lib/components/hero-progress-button.html
- lib/index.html
- tests/browser/modules/image-writer.spec.js
This error happened when trying to burn an image when there is already a
burn in progress.
Fixes: https://github.com/resin-io/resin-etcher/issues/96
> Fix sporadic Cannot read property 'then' of undefined

- build/css/main.css
- lib/scss/main.scss
For some reasons, despite being disabled, buttons still call the action
defined as `ngClick`. In the case of the burn progress button, this
results in:
```sh
TypeError: Cannot read property 'device' of undefined
```
Fixes: https://github.com/resin-io/etcher/issues/132
> Prevent click events on disable buttons

- package.ignore
Previously, the browser code lives in `build/browser` given it was built
with Browserify. Recently, Browserify was removed:
https://github.com/resin-io/etcher/commit/96bf7f3624322045c996090b91b235d4feb85949
and therefore we load the browser code from `lib/browser`.
> Don't ignore lib/browser in the final package

- lib/elevate.js
Printing to `stderr` makes no sense since the process is detached from
the shell when packaged.
> Show error dialogs on elevation errors

- lib/elevate.js
- package.json
Later versions make use of shell commands over the internal contents of
the module causing errors when the application is packaged as an
`asar`.
This issue is being fixed here: https://github.com/jorangreef/sudo-prompt/issues/10
> Downgrade sudo-prompt to v1.1.8

- .gitignore
- Makefile
- PUBLISHING.md
- package.ignore
The `bluebird` module contains a directory called "release", which gets
omitted by `electron-packager`.
After some experimentation, there doesn't seems to be a way to make
`electron-packager` ignore a pattern only on the current directory,
therefore we change the name of our output directory to something that
can't possibly collide with something else.
> Rename release/ to etcher-release/

- Makefile
- README.md
- package.json
This version contains a fix to prevent dropping capabilities in renderer
threads.
See https://github.com/atom/electron/issues/3666
Fixes https://github.com/resin-io/etcher/issues/52
> Upgrade Electron to v0.36.8

- package.json
This new version includes `jshint` as a `peerDependency`, meaning we
must manually install it as well.
See https://github.com/spalger/gulp-jshint/blob/master/CHANGELOG.md#20
> Upgrade gulp-jshint to v2.0.0

- package.json
There are no breaking changes in the only widget we're using from this
library, `uib-dropdown.`
> Upgrade angular-ui-bootstrap to v1.2.1

- package.json
We made some manual changes to `package.json` that were not formatted
correctly.
This PR lets `npm` itself reorganize and format the manifest.
> Reformat package.json

- Makefile
- PUBLISHING.md
Fixes: https://github.com/resin-io/etcher/issues/158
> Sign application in OS X using Resin's developer ID

- package.json
This version contains a fix to prevent the test suite from crashing.
> Upgrade resin-image-zip to v1.1.2

- lib/browser/modules/drive-scanner.js
This ensures there are no orphaned intervals running.
> Stop scanner interval before starting a new one

- lib/elevate.js
- lib/src/dialog.js
Our `package.json` contains a custom `displayName` property which equals
"Etcher" at the time of this writing.
This PR makes use of this property directly instead of hardcoding
"Etcher" in some places.
> Make use of package.json display name to reference the app

- lib/partials/main.html
It lets you be sure that the auto-selected drive is the one you intended
to write to.
Fixes: https://github.com/resin-io/etcher/issues/192
> Show size when there is a selected drive

- package.json
This version omits DMG mounted images by default.
Fixes: https://github.com/resin-io/etcher/issues/193
> Upgrade drivelist to v2.0.8

- lib/browser/app.js
- lib/browser/modules/image-writer.js
- lib/browser/modules/notifier.js
- lib/partials/main.html
- tests/browser/modules/image-writer.spec.js
- tests/browser/modules/notifier.spec.js
Previously, the burn state lived in the controller, however if the user
moved to another page (the settings page for example) and then returned,
the progress state would be lost, leading to a broken progress bar.
Fixes: https://github.com/resin-io/etcher/issues/190
> Move burn state to ImageWriterService

- package.json
This is the correct way of adding a pre-release identifier according to
https://github.com/npm/node-semver.
> Bump version to v1.0.0-beta.0

- lib/browser/modules/drive-scanner.js
This error was reported by TrackJS various times:
```
TypeError: Cannot read property 'length' of undefined
at EventEmitter.<anonymous> (file:///Users/jviotti/Projects/resin/etcher/lib/browser/app.js:104:15)
at emitOne (events.js:77:13)
at EventEmitter.emit (events.js:169:7)
at /Users/jviotti/Projects/resin/etcher/lib/browser/modules/drive-scanner.js:131:17
at processQueue (/Users/jviotti/Projects/resin/etcher/node_modules/angular/angular.js:15616:28)
at /Users/jviotti/Projects/resin/etcher/node_modules/angular/angular.js:15632:27
at Scope.$eval (/Users/jviotti/Projects/resin/etcher/node_modules/angular/angular.js:16884:28)
at Scope.$digest (/Users/jviotti/Projects/resin/etcher/node_modules/angular/angular.js:16700:31)
at /Users/jviotti/Projects/resin/etcher/node_modules/angular/angular.js …
```
> Fix Cannot read property 'length' of undefined

- lib/browser/modules/analytics.js
Otherwise, all we get in TrackJS are "anonymous" users, without a way to
link them to Mixpanel users.
> Configure TrackJS with userId

- lib/src/dialog.js
Currently, we "swallow" errors by only showing them with the "dialog"
module, causing them to not be logged to TrackJS.
> Throw error after displaying it with dialog

- package.json
This new version contains various fixes to better detect removable
drives.
> Upgrade drivelist to v2.0.9

- lib/etcher.js
Turns out that even by using `process.exit(1)`, the electron main
process doesn't exit instantly, but continues executing code.
This causes electron to throw on `electron.globalShortcut` because this
functionality is not available given that we didn't create a renderer
view.
Fixes: https://github.com/resin-io/etcher/issues/215
> Return to avoid any further code execution after an elevation error

- build/css/main.css
- lib/browser/app.js
- lib/browser/components/drive-selector.js
- lib/partials/main.html
- lib/scss/components/_modal.scss
- lib/scss/components/_tick.scss
- lib/scss/main.scss
- lib/scss/modules/_bootstrap.scss
- package.json
- tests/browser/components/drive-selector.spec.js
This modal provides a more advanced way to select a drive. It prevents
certain issues the dropdown was having, like the contents overflowing
when there were many connected drives.
Fixes: https://github.com/resin-io/etcher/issues/202
> Implement a drive selector modal

- lib/browser/pages/finish/controllers/finish.js
- lib/browser/pages/finish/templates/success.tpl.html
EXposing the settings from the `FinishController` is a better approach
that instantiating the `SettingsController` in the Finish page template.
> Use SettingsService in FinishController

- lib/browser/app.js
- lib/browser/utils/open-external/directives/open-external.js
- lib/browser/utils/open-external/open-external.js
- lib/index.html
- tests/browser/utils/open-external.spec.js
This directive will be used in the header and footer instead of having
to rely on `NavigationController` to expose `shell.openExternal`.
> Implement an `openExternal` attribute directive.

- lib/browser/app.js
- lib/browser/utils/if-state/directives/hide-if-state.js
- lib/browser/utils/if-state/directives/show-if-state.js
- lib/browser/utils/if-state/if-state.js
- lib/index.html
- tests/browser/utils/if-state.spec.js
This directives will be used in the header navigation instead of
re-using this logic from the `NavigationController`.
A consequence of this change is that `NavigationController` is no longer
needed, and therefore is removed.
> Implement `showIfState` and `hideIfState` directives

- build/css/main.css
- lib/scss/components/_button.scss
On Electron, the user can click and press over a button,
then move the mouse away from the button and release,
and the button will erroneusly keep the `:focus` state style.
The current workaround consists of:
- Iterate through all the Bootstrap button styles.
- Set the default 'background', `color` and `border-color` to match the
style of the normal state.
> Undo `:focus` styles from Bootstrap.

- lib/etcher.js
From the documentation:
> `useContentSize` Boolean - The `width` and `height` would be used as web
> page’s size, which means the actual window’s size will include window
> frame’s size and be slightly larger. Default is `false`.
The original issue is that when you specify a width/height, the actual
size that you get is slighly smaller, since the OS title bar is included
in the size you provide.
By using the `useContentSize` option, we ensure the `WebView` gets the
intended size, no matter the title bar.
This PR invalidates: https://github.com/resin-io/etcher/pull/244
> Enable useContentSize BrowserWindow option

- lib/src/dialog.js
- tests/src/dialog.spec.js
The following error is thrown if the open file dialog is cancelled
without any selection:
```
Unhandled rejection TypeError: Cannot read property '0' of undefined
at Number.indexedGetter (/home/parallels/Projects/etcher/node_modules/bluebird/js/release/call_get.js:106:15)
at Number.tryCatcher (/home/parallels/Projects/etcher/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/home/parallels/Projects/etcher/node_modules/bluebird/js/release/promise.js:503:31)
at Promise._settlePromise (/home/parallels/Projects/etcher/node_modules/bluebird/js/release/promise.js:560:18)
at Promise._settlePromise0 (/home/parallels/Projects/etcher/node_modules/bluebird/js/release/promise.js:605:10)
at Promise._settlePromises …
```
> Fix uncaught exception if no file was selected from a dialog

- lib/browser/utils/open-external/directives/open-external.js
- package.json
- tests/browser/utils/open-external.spec.js
Fix shell.openExternal() freezing GNU/Linux
Electron's `shell.openExternal()` fails on GNU/Linux when Electron is
ran with `sudo`.  The issue was reported, and this is a workaround until
its fixed on the Electron side.
`node-open` is smart enough to check the `$SUDO_USER` environment
variable and to prepend `sudo -u <user>` if needed.
We keep `shell.openExternal()` for OSes other than Linux since we intend
to fully rely on it when the issue is fixed, and since its closer
integration with the operating system might lead to more accurate
results than a third party NPM module.
See https://github.com/electron/electron/issues/5039
> Fix shell.openExternal() freezing GNU/Linux

- Makefile
- package.json
This PR fixes a frequent issue users were having where opening
`Etcher.app` would result in:
"Etcher.app" is damaged and can't be opened. You should move it to
the trash.
Checking the code-signature of the application returned the following
error message:
$ spctl -a -v Etcher.app
Etcher.app: invalid signature (code or signature have been modified)
The solution is based on the following paragraphs from Apple's "OS X
Code Signing in Depth" technical note:
https://developer.apple.com/library/mac/technotes/tn2206/_index.html
> Code signing uses extended attributes to store signatures in non-Mach-O
> executables such as script files. If the extended attributes are lost
> then the program's identity will be broken. Thus, when you ship your
> script, you must use a mechanism that preserves …
> Codesign OS X app inside the DMG package

- lib/browser/components/drive-selector/templates/drive-selector-modal.tpl.html
The `name` property equals the drive letter in Windows, and the mount
point in UNIX based operating systems.
Fixes: https://github.com/resin-io/etcher/issues/258
> Show drive name in drive selector modal

- build/css/main.css
- lib/browser/components/progress-button/styles/_progress-button.scss
Make the progress bar background striped, and the actual bar solid.
Fixes: https://github.com/resin-io/etcher/issues/251
> Invert progress bar stripes

- build/css/main.css
- lib/scss/components/_modal.scss
UI Bootstrap adds the `.modal-open` class to the `<body>`
element and sets its right padding to the width of the
window, causing the window content to overflow and get
pushed to the bottom.
The `!important` flag is needed since UI Bootstrap inlines
the styles programatically to the element.
Fixes: https://github.com/resin-io/etcher/issues/257
> Fix window contents pushed below when a modal is open

- lib/browser/app.js
- lib/browser/models/selection-state.js
- tests/browser/models/selection-state.spec.js
Suppose you plug a device, select it in Etcher, but then eject it from
your computer. Etcher will keep the selection thinking the drive is
still there.
With this PR, the selected drive, if any, is ensured its still inside
the array of available drives, otherwise the selected is cleared.
Fixes: https://github.com/resin-io/etcher/issues/254
> Detect removal of selected drive

- README.md
Electron no longer supports 10.8.
See http://electron.atom.io/docs/v0.37.5/tutorial/supported-platforms/#os-x
> Make clear that Etcher supports OS X >= 10.9

- package.json
This version contains the following changes:
- Detect Macbook SDCard readers in OS X.
- Detect removable drives better in Windows.
- Keep one decimal in Windows drive size.
Fixes: https://github.com/resin-io/etcher/issues/255
> Upgrade drivelist to v2.0.13

- lib/src/dialog.js
If the function lacks a message or a title, the following error is
thrown:
Error: Could not call remote function ``.
Check that the function signature is correct.
Underlying error: Error processing argument at index 0,
conversion failure from undefined
> Prevent dialog.showErrorBox() throwing if wrong parameters

- Makefile
The capital letter is not very user friendly for command line people.
Fixes: https://github.com/resin-io/etcher/issues/278
> Rename Linux binary to "etcher"

- lib/browser/app.js
- lib/browser/modules/notification.js
Its helpful to have an auditive/visual cue when a burn operation
completed.
Instead of adding a setting entry to enable/disable notifications, you
can use the standard way to control notifications from your operating
system. For example, in OS X, you might go to "System Preferences" ->
"Notifications" and disable notifications for "Etcher".
Fixes: https://github.com/resin-io/etcher/issues/280
> Implement OS notifications on burn completion

- Makefile
- PUBLISHING.md
Before:
118M   Etcher-linux-x64
122M   Etcher-linux-x86
142M   Etcher-win32-x64
116M   Etcher-win32-x86
After:
74M    Etcher-linux-x64
74M    Etcher-linux-x86
124M   Etcher-win32-x64
102M   Etcher-win32-x86
Fixes: https://github.com/resin-io/etcher/issues/281
> Compress Linux executables and Windows DLLs with UPX

- lib/browser/app.js
- lib/browser/components/drive-selector/services/drive-selector.js
If you have the drive selector modal opened, but you eject all the
available drives, the modal will be closed automatically.
Fixes: https://github.com/resin-io/etcher/issues/295
> Hide drive selector modal if no available drives

- lib/browser/components/drive-selector/drive-selector.js
- lib/browser/components/drive-selector/services/drive-selector-state.js
- lib/browser/models/selection-state.js
- tests/browser/components/drive-selector.spec.js
- tests/browser/models/selection-state.spec.js
Previously, `DriveSelector` kept a temporary selection state until the
modal was closed, which caused the selected drives to be passed to
`SelectionStateModel`.
This proves to be problematic when attempting to pass changes to
`SelectionStateModel` to `DriveSelector`. For example, consider the case
where the `DriveSelector` modal is opened with two drives, and one is
ejected. The remaining drive will be auto-selected by Etcher in the
background, but `DriveSelector` will not update itself with such change.
Fixes: https://github.com/resin-io/etcher/issues/304
> Connect DriveSelector with SelectionStateModel

- lib/browser/app.js
- lib/partials/main.html
Currently, if you have only one connected drive, Etcher will auto-select
it. One the single drive is auto-selected, if you attempt to change your
drive selection by clicking on the "Change" link button, the
re-selection is undone, and redone in a matter of milliseconds, making
it very difficult to get the drive selector modal to open.
A simple solution to this problem is making "Change" links trigger the
reselection action (e.g: opening modals, dialogs, etc) instead of simply
undoing the selection.
Fixes: https://github.com/resin-io/etcher/issues/296
> Improve UX when re-selecting a single available drive

- lib/browser/app.js
- lib/browser/modules/image-writer.js
- lib/browser/os/dropzone/directives/dropzone.js
- lib/browser/os/dropzone/dropzone.js
- lib/browser/os/notification/notification.js
- lib/browser/os/notification/services/notification.js
- lib/browser/os/open-external/directives/open-external.js
- lib/browser/os/open-external/open-external.js
- lib/browser/os/window-progress/services/window-progress.js
- lib/browser/os/window-progress/window-progress.js
- lib/browser/utils/notifier/notifier.js
- lib/browser/utils/notifier/services/notifier.js
- lib/browser/utils/path/filters/basename.js
- lib/browser/utils/path/path.js
- lib/index.html
- lib/partials/main.html
- lib/scss/main.scss
- tests/browser/os/dropzone.spec.js
- tests/browser/os/open-external.spec.js
- tests/browser/os/window-progress.spec.js
- tests/browser/utils/notifier.spec.js
- tests/browser/utils/path.spec.js
- Rename `Etcher.Utils.Dropzone` to `Etcher.OS.Dropzone`
- Rename `Etcher.Utils.OpenExternal` to `Etcher.OS.OpenExternal`
- Rename `Etcher.Utils.WindowProgress` to `Etcher.OS.WindowProgress`
- Rename `Etcher.notification` to `Etcher.OS.Notification`
- Rename `Etcher.notifier` to `Etcher.Utils.Notifier`
- Rename `Etcher.path` to `Etcher.Utils.Path`
> Reorganize utilities and desktop integration modules

- lib/browser/app.js
This dependency is only required by `Etcher.Components.DriveSelector`.
> Don't require angular-ui-bootstrap in main module

- lib/browser/app.js
- lib/browser/components/drive-selector/drive-selector.js
- lib/browser/components/progress-button/progress-button.js
- lib/browser/models/selection-state.js
- lib/browser/models/settings.js
- lib/browser/modules/analytics.js
- lib/browser/modules/drive-scanner.js
- lib/browser/modules/image-writer.js
- lib/browser/os/dropzone/dropzone.js
- lib/browser/os/notification/notification.js
- lib/browser/os/open-external/open-external.js
- lib/browser/os/window-progress/window-progress.js
- lib/browser/pages/finish/finish.js
- lib/browser/pages/settings/settings.js
- lib/browser/utils/if-state/if-state.js
- lib/browser/utils/notifier/notifier.js
- lib/browser/utils/path/path.js
- tests/browser/components/drive-selector.spec.js
- tests/browser/models/selection-state.spec.js
- tests/browser/modules/drive-scanner.spec.js
- tests/browser/modules/image-writer.spec.js
- tests/browser/os/dropzone.spec.js
- tests/browser/os/open-external.spec.js
- tests/browser/os/window-progress.spec.js
- tests/browser/utils/if-state.spec.js
- tests/browser/utils/notifier.spec.js
- tests/browser/utils/path.spec.js
This makes them very nicely require-able, for example:
angular.module('MyModule', [
require('my-dependency');
]);
From https://medium.com/@kentcdodds/how-to-distribute-your-angularjs-module-e04d4dd58ddc#.yqg2zo8im
> Make all angular modules export the name of the module

- lib/browser/app.js
Not doing so leads the writer state to have a `progress` of `100%`,
while `isFlashing()` is `false`, which is an inconsistent state.
Fixes: https://github.com/resin-io/etcher/issues/327
> Reset writer state on flash error

- package.json
This new version contains a fix for the `stream.push() after EOF` error
hit when writing unaligned images.
Fixes: https://github.com/resin-io/etcher/issues/307
> Upgrade resin-image-write to v3.0.3

- build/css/main.css
- lib/browser/components/drive-selector/services/drive-selector-state.js
- lib/browser/components/drive-selector/templates/drive-selector-modal.tpl.html
- lib/scss/components/_modal.scss
- tests/browser/components/drive-selector.spec.js
The current "Close" button makes it confusing to the user to know if
he's accepting his changes, or just discarding them.
The "Close" button in the top right corner was replaced with a standard
cross icon, and there is a new "Continue" block button fixed in the
bottom of the modal.
Fixes: https://github.com/resin-io/etcher/issues/294
> Improve UX when closing the drive selector modal

- lib/elevate.js
This is mostly used for debugging purposes, or by power users that know
what they're doing.
> Allow to bypass elevation with an environment variable

- Etcher.desktop
- Makefile
- scripts/desktopintegration
This is useful to prompt the user to install the `.desktop` file.
The `Description` key in `Etcher.desktop` was changed to `Comment` since
`desktop-file-validate` complained with:
Etcher.desktop: error: file contains key "Description" in group "Desktop
Entry", but keys extending the format should start with "X-"
After checking the desktop file format specification, the correct key
should be "Comment"
(https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s05.html).
See: https://github.com/resin-io/etcher/commit/bc6e51996441ce50cd5998712f79e15b6bf6499b#commitcomment-17164442
> Make use of AppImage desktop integration script

- lib/etcher.js
Since the Electron upgrade, Windows users are hitting a weird error
about `global-shortcut` not existing.
A solution is to `require('global-shortcut')` instead of accessing it as
a property of `electron`.
> Fix Error: Cannot find module `../global-shortcut` in Windows

- Makefile
We're distributing AppImages now for convenience.
> Deprecate tar.gz GNU/Linux "installers"

- lib/gui/app.js
- lib/gui/components/drive-selector/templates/drive-selector-modal.tpl.html
- lib/gui/partials/main.html
- lib/gui/utils/byte-size/byte-size.js
- lib/gui/utils/byte-size/filters/gigabyte.js
- package.json
- tests/gui/utils/byte-size.spec.js
This new version reports the size as a number of bytes instead of a
human readable string, so we have to take care of converting back to a
readable GB format ourselves.
> Upgrade drivelist to v3.0.0

- tests/gui/utils/byte-size.spec.js
- `os` in unused in `byte-size.spec.js`
> Fix lint warnings

- lib/cli/cli.js
- lib/cli/etcher.js
This option makes the Etcher CLI outputs state information in a way that
can be easily parsed by a parent process spawning it.
The format of the state output is:
```
<type> <percentage>% <eta>s <speed>
```
This can be easily parsed as follows:
```js
const output = line.split(' ');
const state = {
type: output[0],
percentage: parseInt(output[1], 10),
eta: parseInt(output[2], 10),
speed: parseInt(output[3], 10)
};
```
> Implement Etcher CLI "robot" option

- lib/gui/app.js
- lib/gui/modules/image-writer.js
- lib/start.js
- package.json
This file runs the Etcher CLI if the binary was ran with
`ELECTRON_RUN_AS_NODE`, or the GUI otherwise.
> Add entry point file to decide between GUI/CLI

- package.json
This new version contains a fix where the `diskutil` command was not
found on certain OS X setups.
> Upgrade node-umount to v1.1.3

- lib/cli/etcher.js
This makes it a bit easier to determine if a `stdout` line is a progress
state or not, rather than checking for both `write` or `check`.
> Prefix robot progress state output with "progress"

- lib/cli/etcher.js
- lib/src/exit-codes.js
The purpose is that defined exit codes can be reused in the GUI, so they
are kept in sync more easily.
> Move Etcher CLI exit code definitions to lib/src

- lib/start.js
> Document that ELECTRON_RUN_AS_NODE doesn't load app.asar by default

- lib/cli/cli.js
The CLI now attempts to detect whether it is being run as an argument to
a JavaScript runner (like node or electron), or as a final packaged
executable by applying some heuristics on the first argument.
> Make sure the CLI handles arguments correctly when being packaged

- scripts/packageignore.js
Otherwise, the `.` is interpreted as a period in a regular expression,
which matches every literal character, causing some packages deep in
the `node_modules/` hierarchy to be ignored for no reason.
For example, if we ignore `.git`, then a package like `foo-git` will be
excluded from the final package.
> Escape leading periods on packageignore list

- package.json
This new version contains a fix to align unaligned images and prevent
`EINVAL` errors.
Fixes: https://github.com/resin-io/etcher/issues/348
> Upgrade resin-image-write to v4.0.1

- lib/cli/cli.js
The binary used when spawning the CLI in OS X during development is
`electron-prebuilt/disk/Electron.app/Contents/MacOS/Electron`.
To make sure we catch both `Electron` and `electron`, make the
executable name lowercase before comparing it.
> Make sure CLI args are parsed correctly when spawning in OS X

- lib/cli/etcher.js
Currently, the exit codes documented in the help section was not
honoured if the CLI was ran with the `--robot` option. In this case, the
CLI would exit with code 0 even if the validation failed.
> Use correct exit codes when running Etcher CLI with --robot

- lib/gui/modules/image-writer.js
- package.json
The purpose is that defined exit codes can be reused in the GUI, so they
are kept in sync more easily.
> Implement writing by spawning the CLI as a child process

- PUBLISHING.md
This is needed to build native NodeJS addons.
> Add Python as a PUBLISHING pre-requisite

- lib/src/elevate.js
After elevation routine refactoring, it looks like we have to exit the
parent process after a short while, otherwise it kills the app before
the elevated child process is executed.
> Fix application not being elevated in Windows

- tests/gui/components/svg-icon.spec.js
This was causing builds to fail in Windows.
> Consider carriage returns when asserting SVG contents equality

- package.json
Fancier reporters are not shown correctly on CI servers.
> Set mocha reporter to `min`

- lib/gui/pages/settings/templates/settings.tpl.html
The fact that there is a checkbox at the left of the items already makes
clear the ticking them enables the setting.
> Remove implicit "Enable" from settings items

- build/css/main.css
- lib/gui/app.js
- lib/gui/components/update-notifier/controllers/update-notifier.js
- lib/gui/components/update-notifier/services/update-notifier-s3.js
- lib/gui/components/update-notifier/services/update-notifier.js
- lib/gui/components/update-notifier/styles/_update-notifier.scss
- lib/gui/components/update-notifier/templates/update-notifier-modal.tpl.html
- lib/gui/components/update-notifier/update-notifier.js
- lib/gui/models/settings.js
- lib/gui/pages/settings/styles/_settings.scss
- lib/gui/pages/settings/templates/settings.tpl.html
- lib/gui/scss/components/_modal.scss
- lib/gui/scss/main.scss
- lib/gui/scss/modules/_bootstrap.scss
- lib/gui/utils/manifest-bind/directives/manifest-bind.js
- lib/gui/utils/manifest-bind/services/manifest-bind.js
- package.json
- tests/gui/components/update-notifier.spec.js
- tests/gui/utils/manifest-bind.spec.js
Auto-update functionality is not ready for usage. As a workaround to
prevent users staying with older versions, we now check for updates at
startup, and if the user is not running the latest version, we present a
modal informing the user of the availiblity of a new version, and
provide a call to action to open the Etcher website in his web browser.
Extra features:
- The user can skip the update, and tell the program to delay the
notification for 7 days.
Misc changes:
- Center modal with flexbox, to allow more flexibility on the modal height.
interacting with the S3 server.
- Implement `ManifestBindService`, which now serves as a backend for the
`manifest-bind` directive to allow the directive's functionality to be
re-used by other services.
- Namespace checkbox styles that are specific to …
> Implement update notifier modal

- build/css/main.css
- lib/gui/app.js
- lib/gui/components/drive-selector/templates/drive-selector-modal.tpl.html
- lib/gui/models/selection-state.js
- lib/gui/os/dialog/services/dialog.js
- lib/gui/partials/main.html
- lib/gui/scss/components/_list-group.scss
- lib/gui/scss/main.scss
- tests/gui/models/selection-state.spec.js
- The drive selector modal was modified such that drives that are not large
enough are crossed out, and the user is not able to click them.
- In the case of drive auto-selection, not large enough drives won't
attempt to get autoselected.
This commit introduces:
- The `SelectionStateModel.isDriveLargeEnough()` function.
Fixes: https://github.com/resin-io/etcher/issues/344
> Prevent selection of drives that are not large enough

- scripts/build/windows.bat
Otherwise, dependencies used by `packageignore.js`, like Lodash, could
not be found.
> Call packageignore.js after depencies have been installed in Windows

- docs/PUBLISHING.md
- package.json
- scripts/build/darwin.sh
- scripts/build/linux.sh
- scripts/build/windows.bat
Not building Etcher with the exact NodeJS version bundled with Electron
can cause all sorts of weird issues. This was previously documented, but
its now enforced so Etcher packagers don't forget by accident.
> Enforce expected NodeJS version in build scripts

- scripts/build/darwin.sh
- scripts/build/linux.sh
This allows the users to continuously run the build script without
having to remove `etcher-release` or certain files inside that directory
to prevent silly "file exists" errors.
> Override files if needed in the build scripts

- scripts/build/windows.bat
Since the addition of a patch to only install production dependencies on
build scripts, the Windows build would fail when reaching to
`electron-builder`, since this dependency might not be installed at that
point.
> Install dev dependencies before calling electron-builder on Windows

- lib/gui/os/dropzone/directives/dropzone.js
- tests/gui/os/dropzone.spec.js
There has been changes in the model regarding with how the image
information was stored, and the dropzone directive was never modified to
comply with those changes.
> Fix image drag and drop not working anymore

- lib/gui/etcher.js
Fixes: https://github.com/resin-io/etcher/issues/389
> Prevent global shorcuts from interferring with other applications

- build/css/main.css
- lib/gui/app.js
- lib/gui/components/progress-button/styles/_progress-button.scss
Currently we disable pointer events on the "Flash" button once a flash
is in progress to prevent the user from clicking it, but we didn't
consider that if the user kept focus on the button, he can press the
"space" bar for the same effect.
Fixes: https://github.com/resin-io/etcher/issues/431
> Prevent pressing "space" to re-click the "Flash" button

- lib/gui/os/open-external/directives/open-external.js
- package.json
We currently had a workaround in place to make use of `node-open`
instead of Electron's built-in `shell` module since the latter didn't
work on older Electron versions on GNU/Linux for some reason.
After some experimentation, `node-open` doesn't seem to be working for
elevated applications anymore. I honestly didn't chase the issue further
since Electron `shell` has been fixed, and works fine when elevated,
therefore this PR basically undoes the previous workaround.
Fixes: https://github.com/resin-io/etcher/issues/443
> Fix GNU/Linux not opening an external resource when elevated

- appveyor.yml
- lib/gui/os/open-external/directives/open-external.js
- Fix lint warning.
- Set the correct electron version in `appveyor.yml`
> Fix CI tests

- lib/cli/writer.js
This annotation was introduced in: 1872d1f
> Document `can-ignore` module.require annotation

- lib/gui/etcher.js
If a user drags and drops an image, an HTML file, or other resource the
WebView understands, Electron will navigate away from the application
and load it up in the WebView, making the application unusable unless
the user restarts it.
Fixes: https://github.com/resin-io/etcher/issues/430
> Prevent exernal resources from being loaded by the WebView

- lib/gui/os/dialog/services/dialog.js
If the error object is not well-formed, try to get as most information
about it as we can instead of just realying on generic error messages.
> Try to get more information about error messages

- lib/gui/app.js
The user might attempt to select an invalid image by dropping on the
first step, which would cause Etcher to blindly select it, possibly
causing errors later on the process.
This PR makes use of the list of supported extensions provided by
`SupportedFormatsModel` and prevents the selection if necessary, logging
an event that might help us determine which unsupported image types
users try to burn most often.
> Prevent selection of invalid images

- lib/gui/app.js
- lib/gui/components/drive-selector/controllers/drive-selector.js
- lib/gui/components/drive-selector/drive-selector.js
- lib/gui/components/drive-selector/templates/drive-selector-modal.tpl.html
- lib/gui/models/drives.js
- lib/gui/modules/drive-scanner.js
- lib/gui/partials/main.html
- tests/gui/models/drives.spec.js
- tests/gui/modules/drive-scanner.spec.js
Currently, `DriveScannerService` is in charge of both scanning the
available drives and maintaining the state of the currently detected
drives.
To honour the single responsibility principle, we split this service
into a `DrivesModel`, which is incharge of maintaining the state without
caring how they are detected, and `DriveScannerService`, which only
scans the available drives and modified `DrivesModel` accordingly.
> Extract DrivesModel from DriveScannerService

- lib/gui/models/supported-formats.js
- tests/gui/models/supported-formats.spec.js
Currently, we detect the extensions of an image path by finding the
first dot, and splitting everything afterwards, however this will fail
with image paths containing dots, like `foo.1.2.3-bar.iso.gz`.
> Fix image containing dots in the filename considered unsupported

- build/css/main.css
- lib/gui/pages/finish/styles/_finish.scss
- lib/gui/pages/finish/templates/success.tpl.html
- lib/gui/scss/main.scss
- lib/gui/scss/modules/_bootstrap.scss
This is by no means a complete CSS refactoring. There still a lot to be
done. This encompasses mostly:
- Move "Finish page" specific styles to that module.
- Remove unused CSS rules.
- Move generic Bootstrap rules to `_bootstrap.scss`.
> Cleanup CSS

- build/css/main.css
- lib/gui/pages/finish/templates/success.tpl.html
- lib/gui/scss/components/_label.scss
We want to re-use the `label` component without big paddings in other
areas of the application, therefore we move the custom padding to a
separate label modifier.
> Apply checksum label padding as a custom modifier

- build/css/main.css
- lib/gui/components/drive-selector/styles/_drive-selector.scss
- lib/gui/components/drive-selector/templates/drive-selector-modal.tpl.html
- lib/gui/scss/main.scss
This is a huge improvement over our current approach, which was simply
to cross out the drive without further explanation.
> Show an informative label if a drive is not large enough

- tests/gui/components/update-notifier.spec.js
We rely on a millisecond to determine the state of the update notifier
logic, which can fail at least once per 50 builds or so.
We increase the time difference to account for this little room for
error.
> Fix sporadic race condition in update notifier test suite

- appveyor.yml
- package.json
The new version contains an important fix to prevent `EPERM` errors on
Windows with certain drives.
Fixes: https://github.com/resin-io/etcher/issues/334
> Upgrade etcher-image-write to v5.0.1

- lib/gui/app.js
- lib/gui/index.html
In older versions of Electron, the application would display a quick
flash of white before running caused by the WebView loading up.
This workaround doesn't seem necessary anymore.
> Remove body display hidden white flash workaround

- build/css/main.css
- lib/gui/app.js
- lib/gui/components/tooltip-modal/controllers/tooltip-modal.js
- lib/gui/components/tooltip-modal/services/tooltip-modal.js
- lib/gui/components/tooltip-modal/styles/_tooltip-modal.scss
- lib/gui/components/tooltip-modal/templates/tooltip-modal.tpl.html
- lib/gui/components/tooltip-modal/tooltip-modal.js
- lib/gui/partials/main.html
- lib/gui/scss/main.scss
- package.json
This PR introduces two changes to mitigate this problem and overall
provide a better UX:
- Show ellipses in the middle of the image name in the first step if
needed.
- Add a tooltip below the image selection label in the first step toshow a little modal displaying the full path to the image.
Fixes: https://github.com/resin-io/etcher/issues/418
> Prevent a very long image name from breaking the UI

- lib/gui/app.js
Currently we have logic in the drive selector dialog to prevent invalid
drives (too small, locked, etc) from being selected, however we are not
protecting auto-selection from these invalid devices.
> Prevent an invalid drive from being auto-selected

- scripts/build/darwin.sh
- scripts/build/linux.sh
- scripts/build/windows.bat
This dependency is not used directly by our build scripts, but its used
by `node-gyp` when building native modules, and its much nicer to show a
warning early on than having to halt the build script in the middle for
missing this dependency (specially on Windows systems).
> Check for python in build scripts

- build/css/main.css
- lib/gui/components/update-notifier/services/update-notifier.js
- lib/gui/components/update-notifier/styles/_update-notifier.scss
- lib/gui/scss/components/_modal.scss
Currently, the modal style style used in this component was declared in
`components/_modal.scss`, however since this srule is very specific to
the update notifier component, its better declared in
`update-notifier/styles`.
> Move update notifier modal style to the component

- scripts/elevate-linux.sh
Consider the case where a previously elevated mount was not unmounted
correctly. `mount | grep $(basename $APPIMAGE)` would evaluate to a
multi-line string, and therefore `awk` will perform its work on *each*
line separately, usually returning something like:
```
/tmp/.mountXXXX
/tmp/.mountYYYY-elevated
```
We then pass `$mountpoint` to `mkdir -p`, which evaluates to:
```
mkdir -p /tmp/.mountXXXX
/tmp/.mountYYYY-elevated
```
Therefore `/tmp/.mountXXXX` gets created, and
`/tmp/.mountYYYY-elevated` is ran as an executable, causing all sort of
cryptic errors to come out. This can be even worse, since the third
column of a `mount` line is not always a path, so the errors make even
less sense.
Fixes: https://github.com/resin-io/etcher/issues/482
Fixes: …
> Make sure elevated mount-point evaluates to a single line in GNU/Linux

- scripts/elevate-linux.sh
Currently, when the AppImage was being ran as `root` we would attempt to
run `./usr/bin/etcher`, assuming we were inside the AppDir already and
the relative path would resolve correctly.
> Resolve AppImage binary path correctly when running it as root

- lib/gui/etcher.js
Otherwise, DevTools gets opened inside the Etcher window, causing the
GUI to get completely messed up.
> Open DevTools in "undocked" mode by default

- lib/gui/app.js
- lib/gui/models/supported-formats.js
- lib/gui/os/dialog/services/dialog.js
- package.json
- tests/gui/models/supported-formats.spec.js
Currently, we extract all the extensions from an image path and report
back that the image is invalid if *any* of the extensions is not a
valida extension, however this can cause trouble with images including
information between dots that are not strictly extensions.
For example:
```
elementaryos-0.3.2-stable-i386.20151209.iso
```
Etcher will consider `20151209` to be an invalid extension and therefore
will prevent such image from being selected.
As a way to allow these corner cases but will make use of our enforced
check controls, the validation routine will only consider extensions
starting from the first non compressed extension.
This PR also includes logic to show a nice GUI dialog saying that the
image is invalid in order to provide a much better experience than just
silently …
> Don't check extensions before the first non compressed extension

- README.md
- docs/CONTRIBUTING.md
- package.json
Etcher will start following Angular's commit guidelines, enforced by a
neat tool called `commitizer`, with the main purpose of being able to
auto-generate the CHANGELOG file.
> chore: configure commitizen

- docs/MAINTAINERS.md
We will be generating shrinkwrap files in every release for the
following purposes:
- Be able to run an `npm install` containing the exact package versions
used at the time of publishing.
- Auto-generate dependency updates CHANGELOG entries by comparing
shrinkwrap files between versions.
See: https://docs.npmjs.com/cli/shrinkwrap
> docs: document how to update the shrinkwrap file

- npm-shrinkwrap.json
- package.json
- scripts/shrinkwrap.js
If you run an `npm install` and then run `npm shrinkwrap`, the resulting
shrinkwrap file will contain the installed optional dependencies, making
them "required". If such optional dependency is platform dependent, `npm
install` will fail on different platform.
This is a known `shrinkwrap` limitation whose only workaround seems to
be manually filtering out platform specific dependencies from
`npm-shrinkwrap.json`.
For this purpose, we introduced the following changes:
- A custom `shrinkwrapIgnore` property in `package.json`, where we can
list specific modules that need to be filtered out from
`npm-shrinkwrap.json`.
- A NodeJS script to generate `npm-shrinkwrap.json` and omit modules
specified in `shrinkwrapIgnore` automatically.
- An NPM script called `shrinkwrap`, for convenience.
- Add …
> chore(shrinkwrap): omit platform-specific deps

- lib/src/exit-codes.js
The lint complained that there were two consequent empty lines.
> style: fix lint warning in exit-codes.js

- npm-shrinkwrap.json
- package.json
- tests/gui/models/supported-formats.spec.js
This type of images are distributed by the Ostro Project.
Closes: https://github.com/resin-io/etcher/issues/491
See: https://github.com/resin-io-modules/etcher-image-stream/pull/10
> feat: add support for dsk images

- docs/MAINTAINERS.md
This PR documents the process to upgrade the Electron version correctly,
in order to prevent any potential compatibility issue when building
native dependencies.
> docs(MAINTAINERS.md): steps to upgrade electron

- lib/gui/os/dialog/services/dialog.js
If for some reason either the error title or message are not strings,
the user gets a very obscure error that looks something like this:
```
Error: Could not call remote function ''.
Check that the function signature is correct.
Underlying error:
Error processing argument at index 0, conversion failure
```
What's even worse is that the above error is thrown when we attempt to
display an `Error` object, therefore completely hiding the real error.
In this commit, we make sure both parameters to `showErrorBox()` are
strings, as a safety measure to prevent this from happening again.
See: https://github.com/resin-io/etcher/issues/127
> fix: ensure dialog.showErrorBox() arguments are strings

- docs/CLI.md
This document explains what the Etcher CLI is, how can be used, and some
peculiarities, like `--robot` and exit codes.
> docs(CLI.md): write the CLI.md document

- lib/gui/models/store.js
- tests/gui/models/selection-state.spec.js
We shouldn't allow a write-protected drive from being selected, since
users will get confusing `EPERM` errors later on.
> fix: throw if attempting to select a locked drive

- lib/gui/app.js
- lib/gui/models/store.js
- tests/gui/models/drives.spec.js
If the user has a selected drive, but a new scan shows that such drive
is no longer available, then the selected drive should be de-selected.
> fix: deselect drive if its not available anymore

- lib/gui/models/store.js
We were duplicating the remove drive logic in the `SET_AVAILABLE_DRIVES`
case when the currently selected drive didn't exist anymore.
A better way to handle this without coding repetition is to recursively
apply the reduced with the new state.
> refactor: apply REMOVE_DRIVE recursively in SET_AVAILABLE_DRIVES

- lib/gui/components/drive-selector/templates/drive-selector-modal.tpl.html
- lib/gui/models/drives.js
The addition of `ImmutableJS` caused some issues with Angular's digest
loop. Since `Immutable#toJS()` returns a new object/array every time
(that is, different references), it caused AngularJS to get stuck in an
infinite digest loop when using `ngRepeat` over a function that called
`Immutable#toJS()`.
> fix: infinite digest loop with ngRepeat + ImmutableJS

- lib/gui/app.js
- lib/gui/models/store.js
- tests/gui/models/drives.spec.js
Now that we have a central source of truth for state mutations, the
auto-select feature fits really well in the redux store, particularly
inside the `SET_AVAILABLE_DRIVES` action.
This also has the great benefit that we can unit test the auto-selection
logic, which was not particularly trivial before, when such code lived
in the controller instead.
The only downside of this approach is that we lose the nice "Auto-select
drive" analytics event, which will be re-added very soon in a future PR.
> refactor: move auto-select logic to redux store

- lib/gui/app.js
Currently, the update check runs every single time the main application
controller is instantiated, meaning that the update check would run
again when you visit the settings screen and go back to the main page,
or return to the main page after finishing a flash.
> fix: check for updates only once at startup

- lib/gui/app.js
- lib/gui/models/store.js
- lib/gui/modules/image-writer.js
- lib/gui/pages/finish/controllers/finish.js
- lib/gui/pages/finish/finish.js
- tests/gui/modules/image-writer.spec.js
Currently, we were taking care of resetting the flashing state manually
across several controllers. Now that data mutations live in a single
place, we trigger a flash state reset whenever the flashing flag is set
to false, which reliably handles every case and allows us to forget
about it.
> refactor: reset state when the flashing flag is set to false

- lib/gui/models/store.js
- tests/gui/modules/image-writer.spec.js
Currently, we allow updating the flashing state independently on the
value of the `flashing` property.
In order to maintain the application state coherent, we deny updating
the flashing state if we're not currently flashing, which lets us safely
assume that the state will be in a reset state if we're not flashing.
> fix: don't allow to set the flashing state if not flashing

- lib/gui/models/drives.js
- lib/gui/models/selection-state.js
- lib/gui/models/store.js
- lib/gui/modules/image-writer.js
Referencing actions as properties of an object is more reliable than
just hardcoding strings everywhere.
> refactor: expose an object of available actions

- lib/gui/models/store.js
- lib/gui/modules/image-writer.js
Currently, the "flash" property of the application state containing both
the actual flashing state, and the flashing flag.
To simplify things, the following changes have been introduced:
- Move `flash.flashing` to `isFlashing`.
- Move `flash.state` to `flashState`.
- Rename `SET_FLASHING` to `SET_FLASHING_FLAG`.
- Extract `UNSET_FLASHING_FLAG` from `SET_FLASHING_FLAG`.
> refactor: flatten "flash" data structure property

- lib/gui/modules/analytics.js
- lib/gui/modules/image-writer.js
- From `Etcher.analytics` to `Etcher.Modules.Analytics`.
- From `Etcher.image-writer` to `Etcher.Modules.ImageWriter`.
> refactor: improve analytics and image-writer module names

- lib/gui/app.js
- lib/gui/models/store.js
- lib/gui/modules/image-writer.js
- lib/gui/partials/main.html
- tests/gui/modules/image-writer.spec.js
So the property is consistent from what we get from `etcher-image-write`
and we don't have to unnecessarily rename ourselves to pass it to the
model.
> refactor: rename progress property to percentage

- lib/gui/models/store.js
- tests/gui/modules/image-writer.spec.js
The commit 0f8136f, which enforced validation for the state object,
introduced a subtle bug where `Missing state eta` would be thrown if
`eta === 0`, since `!0` evaluates to `true`.
This would cause the flashing to stop right at the end (when eta is
zero).
> fix: don't throw missing eta if eta is zero

- lib/gui/app.js
- lib/gui/models/store.js
- lib/gui/modules/image-writer.js
- lib/gui/pages/finish/controllers/finish.js
- lib/gui/pages/finish/finish.js
- lib/gui/pages/finish/templates/success.tpl.html
- lib/gui/partials/main.html
- tests/gui/modules/image-writer.spec.js
This is a rather big PR that moves the flash results information to the
Redux store, which simplifies and improves a lot of things as throughly
described in the commits that introduced Redux.
Here's a summary of the changes:
- Add a `flashResults` property to the store.
- Validate the contents of `flashResults`, handling certain edge cases
that make the modal incoherent.
- Split `ImageWriterService.setFlashing()` to
`ImageWriterService.setFlashingFlag()` and
`ImageWriterService.unsetFlashingFlag()`.
- Require the flash results to be passed to
`ImageWriterService.unsetFlashingFlag()`.
- Stop resolving the flash results from `ImageWriterService.flash()`.
- Implement `ImageWriterService.getFlashResults()`.
- Make the `RESET_FLASH_STATE` action reset the flash results.
- Access the source …
> refactor: move flash results state to Redux store

- lib/gui/app.js
- lib/gui/components/update-notifier/controllers/update-notifier.js
- lib/gui/components/update-notifier/services/update-notifier.js
- lib/gui/components/update-notifier/templates/update-notifier-modal.tpl.html
- lib/gui/models/settings.js
- lib/gui/models/store.js
- lib/gui/modules/analytics.js
- lib/gui/modules/image-writer.js
- lib/gui/pages/finish/controllers/finish.js
- lib/gui/pages/finish/templates/success.tpl.html
- lib/gui/pages/settings/controllers/settings.js
- lib/gui/pages/settings/templates/settings.tpl.html
- lib/gui/partials/main.html
- package.json
- tests/gui/components/update-notifier.spec.js
- tests/gui/models/settings.spec.js
The state data structure now contains a property called `settings`, which
is a map containing all setting values.
The list of supported settings can be calculated by retrieving the keys
from the `settings` object, which means that if we support a setting, we
must include a default.
> refactor: store settings in redux store

- build/css/main.css
- lib/gui/components/progress-button/styles/_progress-button.scss
The progress button exhibits spiky diagonals when used it with the
"striped" modifier. This can be seen better when drastically reducing the animation
speed.
Turns out its a Webkit rendering bug. I've stumbled into dozens of
"workarounds" on the internet (mainly Stack Overflow), however none of
them fixed the issue.
After some crazy amount of experimentation, the issue is gone if we add
1% to certain stop positions. Weird stuff.
Fixes: https://github.com/resin-io/etcher/issues/472
> fix(progressButton): spiky diagonal lines

- lib/gui/etcher.js
Turns out the user can zoom-in the whole application, which we didn't
notice before.
> fix: prevent user from zooming in the whole application

- .github/ISSUE_TEMPLATE.md
An issue template would help us ensure we get all the information we
need at the time of submission, so we don't have to go back and forth
with the user to answer the same questions every time, wasting the
user's time.
See: https://github.com/blog/2111-issue-and-pull-request-templates
> chore: add a GitHub issue template

- package.json
This version contains a fix to an `EPERM` issue ocurring on Windows.
See: https://github.com/resin-io-modules/etcher-image-write/pull/45
Fixes: https://github.com/resin-io/etcher/issues/531
> fix(Windows): upgrade etcher-image-stream to v5.0.2

- lib/gui/components/update-notifier/templates/update-notifier-modal.tpl.html
Since the addition of Redux and ImmutableJS data structures, we store
the application settings in the Redux store.
This means that checkboxes on templates can no longer bind to the
setting properties directly.
This was fixed in the setting page, but we missed one of them in the
update notifier model.
```html
ng-model="modal.settings.get('sleepUpdateCheck')"
```
Won't lead any meaningful return, and in fact, throws an uncaught
exception.
Changelog-Entry: Fix uncaught exception when showing the update notifier modal.
> fix(GUI): uncaught exception in update notifier

- lib/gui/models/store.js
- lib/gui/modules/image-writer.js
- tests/gui/modules/image-writer.spec.js
There is a small flaw in the current state validation rules where a
speed that equals zero will be considered as if the speed was missing
giving that `!0 == true`.
Changelog-Entry: Fix state validation error when speed equals zero.
> fix(GUI): don't throw if state speed is 0

- lib/gui/app.js
- lib/gui/partials/main.html
- npm-shrinkwrap.json
- package.json
In certain timezones, like India's, the ETA would display very weird
numbers. The problem was that we passed a number of milliseconds to
MomentJS, which created a Date object based on it taking timezones into
consideration.
As a solution, we convert the seconds to a Date object containing the
lowest possible date values, and set its seconds to the ETA, since this
effectively represents just the number of seconds we're interested in.
Changelog-Entry: Fix incorrect ETA numbers in certain timezones.
> fix(GUI): incorrect ETA on certain timezones

- lib/gui/app.js
Currently, if either `OSDialogService.selectImage()` or
`DriveSelectorService.open()` are rejected, we completely swallow the
errors, making very hard to debug certain problems.
This PR takes care of showing the usual error dialog for those cases.
> minifix(GUI): handle image dialog and drive selector errors

- npm-shrinkwrap.json
- package.json
This new version contains a huge improvement on how the `kdesudo` dialog
looks.
See: https://github.com/jorangreef/sudo-prompt/commit/17f45ebef31afd9fb6260f7c2950fea4aab5ae4d
> upgrade: `sudo-prompt` to v5.1.0

- lib/gui/app.js
- lib/gui/components/drive-selector/controllers/drive-selector.js
Using `dismiss()` causes the promise to be rejected, with no reason in
this case. Given we made sure we were handling errors from dialogs in a
previous commit, this issue manifested itself.
The `close()` function, without arguments, makes more sense in this
case.
See: https://github.com/resin-io/etcher/pull/548
> minifix(GUI): use close() to dismiss drive selector modal

- docs/COMMIT_GUIDELINES.md
This document will serve as a more expanded guide on the commit
conventions we are going to be introducing in this project mainly for
the purpose of `CHANGELOG.md` generation.
See: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit
> docs: commit guidelines

- lib/gui/app.js
- lib/gui/modules/image-writer.js
Currently, if we cancel elevation, we'd get a big scary validation error
about `passedValidation` not being passed to the flash results object.
This fix also requires some adjustments to `wasLastFlashSuccessful()` in
order to adapt to the cancellation scenario.
Since a cancelled elevation request means the writing never took place,
`wasLastFlashSuccessful()` returns `true` if so, without even looking at
`passedValidation`.
Changelog-Entry: Fix error when cancelling an elevation request.
> fix(GUI): uncaught error when cancelling an elevation request

- lib/src/child-writer/utils.js
Images may contain parenthesis. This is usually the case when you
re-download a file with a web browser, which atuaomtically appends `(N)`
to the path.
Not escaping parenthesis means that when passing the image path as an
argument to the write proxy script, bash will complain about it as a
syntax error on the command.
The fix is not necessary in Windows. I've been able to write images
containing parenthesis in that operating system without issues.
Changelog-Entry: Fix error when writing images containing parenthesis in GNU/Linux and OS X.
Fixes: https://github.com/resin-io/etcher/issues/556
> fix(GUI): escape parens in image paths on Linux/OS X

- lib/src/child-writer/writer-proxy.js
The `elevator` module passes its arguments directly to
`child_process.execFile()`, which handles escaping spaces and other
weird issues by default.
Instead of passing a separate argument for every word of the writer
proxy script command, we passed the whole thing at once, which means we
didn't get the escaping features by default.
Changelog-Entry: Fix flashing not starting when an image name contains a space.
> fix(GUI): escape image path spaces correctly on Windows

- package.json
This version contains a GNU/Linux fix there the image extension was
changed by the dialog.
Changelog-Entry: Fix `ENOENT` error when selecting certain images with multiple extensions on GNU/Linux.
See: https://github.com/electron/electron/issues/6305
> upgrade(GUI): electron to v1.2.6

- README.md
- docs/USER-DOCUMENTATION.md
Document how to globally disable AppImage's desktop integration feature,
which promtps the user to create a desktop shortcut for the appliation
at startup.
> docs(GUI): deactivate desktop shortcut Linux prompt

- lib/gui/models/supported-formats.js
- tests/gui/models/supported-formats.spec.js
Currently, we take the image extension casing into account when
determining if the extension is a recognised one (e.g: `img`, `iso`,
etc). This causes an "Invalid image" error to be thrown when selecting
an image with an uppercase extension, like `UBUNTU.ISO`.
Changelog-Entry: Don't throw an "Invalid image" error if the extension is not in lowercase.
Fixes: https://github.com/resin-io/etcher/issues/567
> fix(GUI): ignore casing when checking an image extension validity

- .travis.yml
- appveyor.yml
- docs/CONTRIBUTING.md
- docs/MAINTAINERS.md
- docs/PUBLISHING.md
- scripts/build/darwin.sh
- scripts/build/linux.sh
- scripts/build/windows.bat
Currently build scripts install dependencies and package everything on
every run. In order to allow more customisation, the build scripts now
accept the following commands:
- `install`: Only install dependencies.
- `package`: Only package the application.
- `all`: Install dependencies and package the application.
The above differentiation allows us to improve the documentation and CI
configuration files to point to the `install` commands instead of having
to explain how to configure NPM correctly, since that's done by the
build scripts by default.
> chore: add commands to build scripts

- .eslintrc.yml
We're currently forcing a UNIX linebreak style, which causes hundreds of
complaints from the linter when cloning the project in a Windows machine
with a default configuration.
> chore: don't force a linebreak style in ESLint

- .github/ISSUE_TEMPLATE.md
Doing it like this means that one does not have to delete the note before posting; it simply won't appear.
> Use comments instead of plaintext in issue template

- npm-shrinkwrap.json
- package.json
This version contains a fix for a `diskpart` error on Windows.
Changelog-Entry: Upgrade `etcher-image-write` to v5.0.2
Link: https://github.com/resin-io-modules/etcher-image-write/blob/master/CHANGELOG.md
See: https://github.com/resin-io/etcher/issues/552
See: https://github.com/resin-io/etcher/issues/571
> upgrade: etcher-image-write to v5.0.2

- npm-shrinkwrap.json
- package.json
This version contains a fix to check the removable state of drives without a
file system in Windows.
Link: https://github.com/resin-io-modules/drivelist/blob/master/CHANGELOG.md
Changelog-Entry: Upgrade `drivelist` to v3.2.2.
> upgrade: drivelist to v3.2.2

- build/css/main.css
- lib/gui/models/store.js
- lib/gui/modules/drive-scanner.js
- lib/gui/pages/settings/controllers/settings-dangerous-modal.js
- lib/gui/pages/settings/controllers/settings.js
- lib/gui/pages/settings/settings.js
- lib/gui/pages/settings/styles/_settings.scss
- lib/gui/pages/settings/templates/settings-dangerous-modal.tpl.html
- lib/gui/pages/settings/templates/settings.tpl.html
- lib/gui/scss/modules/_space.scss
This setting makes Etcher not filter non-removable drives, allowing you to
arbitrarily write to your system drives.
This is a dangerous option, therefore we present it in a separate section of
the settings page, and show an informative confirmation dialog.
Changelog-Entry: Add an "unsafe" option to bypass drive protection.
Fixes: https://github.com/resin-io/etcher/issues/480
> feat(GUI): enable "unsafe" mode

- docs/CONTRIBUTING.md
The dependencies are checked for in the build scripts, but for the user
convenience, we should also list them explicitly in the `CONTRIBUTING.md`
guide.
> docs: explicitly list all dependencies in CONTRIBUTING.md

- docs/CONTRIBUTING.md
- docs/MAINTAINERS.md
- docs/PUBLISHING.md
- package.json
- scripts/build/darwin.sh
- scripts/build/linux.sh
- scripts/build/windows.bat
We were previously requiring users to run the exact same NodeJS version as
Electron bundled in order to avoid native add-on compilation incompatibilities,
however this problem is completely mitigated by configuring NPM to build
against an Electron specific V8.
> chore: stop requiring a specific nodejs version to build Etcher

- lib/gui/os/dialog/services/dialog.js
- npm-shrinkwrap.json
- package.json
We were currently checking if a drive was large enough for an image by checking
the image file size, completely ignoring compression. This results on a small
chance of the uncompressed image not actually fitting in the drive, and
throwing more weird errors later on.
In order to mitigate this, we use the new `.getEstimatedFinalSize()` function
from `etcher-image-stream`, which returns the uncompressed size in the case of
compressed images.
We needed to update the build script for OS X to configure NPM correctly,
otherwise `lzma-native` throws some errors due to an ABI V8 incompatibility
issue.
Fixes: #571
See: https://github.com/addaleax/lzma-native/issues/25
Changelog-Entry: Check if drive is large enough using the final uncompressed size of the image.
Signed-off-by: …
> fix(GUI): check drive size against uncompressed image size

- docs/USER-DOCUMENTATION.md
Document that `parted` warnings about invalid GPT and physical block
size issues can be safely ignored as they are a consequence of "hybrid
iso's".
Fixes: https://github.com/resin-io/etcher/issues/312
> docs: ubuntu iso's hybrid format and parted warnings

- docs/CONTRIBUTING.md
This small entry explains how to upgrade a dependency and ensure
`npm-shrinkwrap.json` is updated correctly.
> docs: upgrade an npm dependency and handling shrinkwrap correctly

- lib/cli/etcher.js
The Etcher CLI doesn't care if the drive exists or not. The user will
eventually find out since the CLI will output an `ENOENT` when trying to
actually write data, however its nicer from a UX perspective to catch
this early on.
Changelog-Entry: Validate the existence of the passed drive.
> feat(CLI): validate drive

- lib/cli/etcher.js
- lib/cli/writer.js
- lib/gui/app.js
- lib/gui/models/store.js
- lib/gui/modules/image-writer.js
- lib/gui/partials/main.html
- lib/src/child-writer/index.js
- npm-shrinkwrap.json
- package.json
- tests/gui/modules/image-writer.spec.js
We try our best to check that the images the user select are too big for
the selected drive as early as possible, but this probes to be
problematic with certain compressed formats, like bzip2, which doesn't
store any information about the uncompressed size, requiring a ~50s
intensive computation as a minimum to find it out.
For these kinds of formats, we don't perform an early check, but instead
gracefully handle the case where the drive doesn't have any more space.
This PR handles an `ENOSPC` error by displaying the alert orange ribbon,
and prompting the user to retry with a larger drive. This is a huge
improvement over the cryptic `EIO` error what was thrown before, and
over having Etcher freeze at a certain percentage point.
Changelog-Entry: Display a nice alert …
> feat(GUI): display a nice alert ribbon if drive runs out of space

- docs/CONTRIBUTING.md
One of the steps incorrectly says "Re-install the dependencies. This
will update the `npm-shrinkwrap.json` file". The intention was to say
that you should `npm install` the *new* dependency, and that will update
the `npm-shrinkwrap.json` file.
> docs: fix error on the upgrading a dependency guide at CONTRIBUTING.md

- npm-shrinkwrap.json
- package.json
- tests/gui/models/supported-formats.spec.js
Changelog-Entry: Add support for `raw` images.
See: https://github.com/resin-io-modules/etcher-image-stream/pull/21
> feat: add support for `raw` images

- CHANGELOG.md
- docs/MAINTAINERS.md
- package.json
- versionist.conf.js
Versionist is a small utility to automatically generate CHANGELOGs based
on a certain commit convention.
This PR adds a new `changelog` npm script that calls Versionist to
preppend a new CHANGELOG entry based on our current structure.
Dealing with links to changes between versions in GitHub is hard to
automatise with a tool like Versionist. We chose to get rid of such
links since they are a nice to have, but don't provide any meaningful
value to maintainers, since they can manually see the diffs with `git
diff`.
> chore: integrate versionist

- npm-shrinkwrap.json
- package.json
This version fixes an issue were certain malformed Zip files choked
`etcher-image-stream`.
Link: https://github.com/resin-io-modules/etcher-image-stream/blob/master/CHANGELOG.md
Fixes: https://github.com/resin-io/etcher/issues/410
> upgrade: `etcher-image-stream` to v2.6.1

- lib/gui/app.js
- lib/gui/components/svg-icon/directives/svg-icon.js
- lib/gui/models/selection-state.js
- lib/gui/models/store.js
- lib/gui/os/dialog/services/dialog.js
- lib/gui/os/open-external/directives/open-external.js
- lib/gui/os/open-external/services/open-external.js
- lib/gui/partials/main.html
- npm-shrinkwrap.json
- package.json
- tests/gui/components/svg-icon.spec.js
- tests/gui/models/selection-state.spec.js
- tests/gui/os/open-external.spec.js
The following PRs add support for a custom `_info` directory containing
metadata such an image URL, display name, logo, etc in
`etcher-image-stream`:
- https://github.com/resin-io-modules/etcher-image-stream/pull/16
- https://github.com/resin-io-modules/etcher-image-stream/pull/14
- https://github.com/resin-io-modules/etcher-image-stream/pull/13
Now that this module supports such metadata, we make use of it in the
GUI as follows:
- The file name is replaced with the display name.
- The file name links to the image URL.
- The "Select Image" logo is replaced with the image logo.
Some miscellaneous changes introduces in this PR to support the changes
described above:
- Implement `SelectionStateModel.getImageUrl()`.
- Implement `SelectionStateModel.getImageLogo()`.
- Implement …
> feat(GUI): rich image extensions

- lib/src/child-writer/utils.js
Consider a directory name such as `Juan's Files`. When passing such path
as an argument to the child writer proxy script, Bash will complain
with:
> Unexpected EOF while looking for matching `'`
The solution is to manually escape quotes on the image path.
Changelog-Entry: Escape quotes from image paths to prevent Bash errors on GNU/Linux and OS X.
> fix(GUI): escape quotes from image paths

- lib/gui/app.js
- lib/gui/components/drive-selector/templates/drive-selector-modal.tpl.html
- lib/gui/models/selection-state.js
- lib/gui/models/store.js
- tests/gui/models/drives.spec.js
- tests/gui/models/selection-state.spec.js
Instead of storing the whole selected drive object, we barely store a
reference to the corresponding drive in the available drives array (the
reference being the drive device).
This greatly simplifies the application state in the following ways:
- The drive metadata (size, description, etc) is not duplicated in the
state, enforcing a single source of truth.
- If the selected drive stops being available (e.g: is unplugged), the
reference doesn't hold anymore, making this functionality very natural
to implement.
- Makes `SelectionStateModel.isCurrentDrive()` much more inuitive, since
we don't have to document that changes in the metadata of the drive
object, or extra keys such as `$$hashKey` don't change the result of
this function.
- Ensures the state never goes into a problematic state …
> refactor(GUI): store drive as a reference to available drives

- npm-shrinkwrap.json
- package.json
This version contains the following fixes:
- Correctly handle mount points with spaces in GNU/Linux.
- Correctly report drive sizes in macOS Sierra.
Changelog-Entry: Upgrade `drivelist` to v3.2.4.
> upgrade: `drivelist` to v3.2.4

- lib/gui/components/drive-selector/services/drive-selector.js
- lib/gui/components/modal/modal.js
- lib/gui/components/modal/services/modal.js
- lib/gui/components/tooltip-modal/services/tooltip-modal.js
- lib/gui/components/tooltip-modal/tooltip-modal.js
- lib/gui/components/update-notifier/services/update-notifier.js
- lib/gui/components/update-notifier/update-notifier.js
- lib/gui/pages/settings/controllers/settings.js
- lib/gui/pages/settings/settings.js
When the user clicks on the backdrop of a modal, the modal promise gets
rejected, therefore triggering our application error handler.
UI Bootstrap provides a way to disable the backdrop completely, but
doesn't provide a way to allow a backdrop click to simply close the
modal rather than rejecting it, as if an issue happened.
To mitigate this issue, and still preserve the backdrop functionality,
we created `ModalService`, which abstracts the messy details of calling
`$uibModal`, and has custom logic to ignore "backdrop click" errors.
Changelog-Entry: Fix "backdrop click" uncaught errors on modals.
> fix(GUI): backdrop click error on modals

- build/css/main.css
- lib/gui/models/store.js
- lib/gui/partials/main.html
- lib/gui/scss/main.scss
- tests/gui/models/drives.spec.js
Currently, we intentionally prevent a drive from being auto-selected if
there was no selected image for UX purposes, however this way of
thinking has been challenged, and we didn't find a real UX problem by
doing this.
As a minor design improvement, we gray out the drive name in the main
window when an image hasn't been selected yet.
Changelog-Entry: Perform drive auto-selection even when there is no selected image.
> feat(GUI): perform drive auto-selection when no selected image

- lib/gui/modules/analytics.js
Currently, TrackJS would receive errors when running Etcher locally.
Most of the errors reported from those environments are due to
developing Etcher, and create a lot of noise in TrackJS.
With this PR, we ensure Etcher will only report errors when running
inside an `asar` archive, which means its a "packaged" Etcher version.
Changelog-Entry: Only enable error reporting if running inside an `asar`.
> fix(GUI): only enable error reporting if running inside an asar

- lib/gui/app.js
- lib/gui/modules/image-writer.js
- lib/gui/partials/main.html
- tests/gui/modules/image-writer.spec.js
Currently, we subscribe to the store change events and manually update a
`.state` property in `ImageWriterService`. A much more elegant approach
is to provide a `.getFlashState()` function that fetches the flash state
directly from the store when needed.
> refactor(GUI): stop storing flash state in a `.state` object variable

- lib/gui/models/store.js
- tests/gui/models/selection-state.spec.js
We recently introduced a feature where a single available drive would be
auto-selected even if the user didn't select an image.
This introduces a potential scenario that brings the state to an
incoherent state:
- Start Etcher.
- Let a drive get auto-selected.
- Select an image larger than the auto-selected drive.
In this case, the drive is known to not have enough space to hold the
image, but remains auto-selected.
This PR makes sure the drive is deselected automatically in the above
scenario.
> minifix(GUI): deselect auto-selected drive if image is too large

- lib/gui/app.js
- lib/gui/models/flash-state.js
- lib/gui/modules/image-writer.js
- lib/gui/pages/finish/controllers/finish.js
- lib/gui/pages/finish/finish.js
- lib/gui/partials/main.html
- tests/gui/models/flash-state.spec.js
- tests/gui/modules/image-writer.spec.js
`ImageWriterService` currently has two responsibilities. It contains
logic to start and manage a flash process, and provides an API to
interact with the current flash state.
To honour the single responsibility principle, we extract
`FlashStateModel` from `ImageWriterService`.
> refactor(GUI): extract FlashStateModel from ImageWriterService

- lib/gui/models/flash-state.js
- lib/gui/models/store.js
- lib/gui/modules/image-writer.js
- lib/gui/pages/finish/controllers/finish.js
- lib/gui/pages/main/controllers/main.js
- lib/gui/pages/main/templates/main.tpl.html
- tests/gui/models/flash-state.spec.js
Currently, the client application knows too much about how the flash
results are stored in the internal state, and relies on its structure to
perform its logic.
This PR introduces several getters to `FlashStateModel` and makes
`FlashStateModel.getFlashResults()` private, ensuring clients don't
depend on the flash results object.
> refactor(GUI): increase encapsulation of flash results structure

- lib/gui/models/store.js
- tests/gui/models/flash-state.spec.js
We were currently throwing a validation error if the error code was not
string when setting the flash results, however a number error code makes
sense in some cases, and its what its returned by a `ChildProcess`
object.
See: https://github.com/resin-io/etcher/issues/609
> minifix(GUI): permit a number error code in flash results

- lib/cli/etcher.js
- lib/gui/pages/main/controllers/main.js
- lib/src/child-writer/index.js
- npm-shrinkwrap.json
- package.json
- scripts/shrinkwrap.js
This version contains the following improvements:
- https://github.com/jviotti/removedrive/pull/3
- https://github.com/jviotti/removedrive/pull/2
Changelog-Entry: Upgrade `removedrive` to v1.1.1.
Link: https://github.com/jviotti/removedrive/blob/master/CHANGELOG.md
See: https://github.com/resin-io/etcher/issues/573
> upgrade: `removedrive` to v1.1.1

- npm-shrinkwrap.json
- package.json
This version makes sure the device file descriptor is closed right after
validation completes. This fix prevents `RemoveDrive.exe` from throwing
an `EBUSY` error when trying to unmount the drive.
Changelog-Entry: Upgrade `etcher-image-write` to v6.0.1.
Link: https://github.com/resin-io-modules/etcher-image-write/blob/master/CHANGELOG.md
See: https://github.com/resin-io/etcher/issues/573
> upgrade: `etcher-image-write` to v6.0.1

- npm-shrinkwrap.json
- package.json
Changelog-Entry: Fix internal removable drives considered system drives in macOS Sierra.
See: https://github.com/resin-io-modules/drivelist/pull/86
> upgrade: `drivelist` to v3.2.6

- npm-shrinkwrap.json
- package.json
Currently, if no graphical polkit authentication agent is found,
`sudo-prompt` will yield a "User did not grant permission." error, which
gives the impression the user cancelled the dialog (or entered the wrong
password), causing confusion for the user.
Instead, Etcher will now display a nice "No polkit authentication agent
found." error dialog.
Changelog-Entry: Display an error if no graphical polkit authentication agent was found.
See: https://github.com/jorangreef/sudo-prompt/pull/29
> fix(GUI): display an error if no polkit authentication agent was found

- lib/cli/etcher.js
- lib/cli/log.js
When using the `--robot` option, we write to `stdout`/`stderr` using
`WritableStream#write()`. This operation is asynchronous, however we're
not waiting for the data to be flushed before calling `process.exit()`
right after emitting the `done` event.
This causes a rance condition where sometimes `done` is never written to
the log file, and therefore the GUI remains waiting forever.
Changelog-Entry: Fix application stuck at "Finishing".
See: https://github.com/resin-io/etcher/issues/613
See: https://github.com/resin-io/etcher/issues/609
See: https://github.com/resin-io/etcher/issues/573
> fix(CLI): wait for robot output to be flushed before exitting

- lib/gui/pages/main/controllers/main.js
There are some cases where AngularJS won't recognise that the available
drive list has changed, and incorrectly keeps asking the user to connect
a drive.
This problem was mainly witnessed in Windows, and could be reproduced
with the following steps:
- Start Etcher with no available drive.
- Select an image.
- Plug a drive.
Etcher keeps showing "Connect a drive" in the second step.
Changelog-Entry: Fix new available drives not being recognised automatically in Windows.
> fix(GUI): force Etcher to auto-detect newly available drives

- lib/gui/pages/main/controllers/main.js
- lib/gui/pages/main/templates/main.tpl.html
Currently, we show "Finishing..." indenpendently on if we're waiting for
the flash to emit the "done" event, or we're waiting for the drive to be
unmounted.
As a way to simplify things, we move the hairy `ngShow` stack from the
main template to a nice function in the controller.
Changelog-Entry: Show "Unmounting..." while unmounting a drive.
> feat(GUI): show "Unmounting..." while unmounting a drive

- lib/gui/pages/main/controllers/main.js
The problem can be reproduced with the following steps:
- Start Etcher.
- Plug a single drive, and let Etcher auto-select it.
- Navigate to the settings screen.
- Go back to the main screen.
The drive is auto-removed for a very small amount of time, until
auto-selection takes care of selecting it again. This behaviour causes
no harm, but its a bit annoying.
The problem was caused by a previous fix, which auto-removed the drive
if navigating back to the main screen after a flash finished, however
the fix no longer makes a lot of sense now that we allow a drive to be
selected even when no image has been chosen.
Changelog-Entry: Prevent selected drive from getting auto-removed when navigating back to the main screen from another screen.
Signed-off-by: Juan Cruz Viotti …
> fix(GUI): drive is removed everytime user navigates to main screen

- lib/gui/app.js
- lib/gui/modules/analytics.js
- lib/gui/modules/error.js
- lib/gui/pages/main/controllers/main.js
- lib/gui/pages/main/main.js
Error handling is currently a mess. The knowledge to correctly report an
error both to the end user and to us is scattered in many places.
This PR introduces the following changes:
- Rename `AnalyticsService.logDebug()` to `AnalyticsService.logDebug()`
to clarify better the intention of the function.
- Move `$log` decorators from an `AnalyticsService` run block to
`AnalyticsService.logDebug()`.
- Implement `AnalyticsService.logException()`, whose duty is to log an
exception to TrackJS or any related service, and log it to DevTools.
- Implement `ErrorService.reportException()`, whose duty is to report an
exception to every interested party. This means logging the error to
TrackJS, displaying it DevTools and showing a nice alert to the user.
This function is based from `handleError()` from …
> refactor(GUI): unify error handling

- lib/gui/app.js
- lib/gui/pages/main/controllers/main.js
Currently, the logic the controls the drive scanner and populates the
drive model lives in the main application controller.
This is not optimal because:
- The drive scanner stops populating the drives model when the
application is not on the main screen.
- An event handler subscribes to the drive scanner every time the user
navigates back to the main screen.
This PR moves the drive scanner logic to a run block in the entry point
of the application.
> refactor(GUI): move drive scanner logic to application entry point

- lib/gui/os/open-external/services/open-external.js
- tests/gui/os/open-external.spec.js
This PR fixes an uncaught error being thrown when
`OSOpenExternalService.open()` is called with an undefined value.
> minifix(GUI): don't call shell.openExternal if resource is undefined

- docs/USER-DOCUMENTATION.md
This entry roughly documents how to get Etcher running on Wayland by
using the XWayland Server.
Fixes: https://github.com/resin-io/etcher/issues/509
> docs(GUI): running Etcher on Wayland

- docs/ARCHITECTURE.md
- lib/gui/pages/main/controllers/drive-selection.js
- lib/gui/pages/main/controllers/flash.js
- lib/gui/pages/main/controllers/image-selection.js
- lib/gui/pages/main/controllers/main.js
- lib/gui/pages/main/main.js
- lib/gui/pages/main/templates/main.tpl.html
- tests/gui/pages/main.spec.js
The main page controller contained a lot of undocumented and untested
logic. As a first step towards cleaning up the whole thing, this PR
introduces the following changes:
- Implement `ImageSelectionController`, `DriveSelectionController`, and
`FlashController` as children of `MainController`. Each of them is
used by the appropriate main page "steps", and contains logic specific
to them. The `MainController` hosts functionality that applies to the
page as a whole.
- Add JSDoc annotations fo every controller function/property.
- Unit test several controller functions.
- Simplify template logic.
The "GUI fifty-thousand foot view" section in ARCHITECTURE.md has been
removed since there is no longer a single place where you can see all
the interactions between components.
Signed-off-by: Juan …
> refactor(GUI): main controller

- npm-shrinkwrap.json
- package.json
This version contains support to extract a bmap file out of an archive
image.
See: https://github.com/resin-io/etcher/issues/171
Changelog-Entry: Upgrade `etcher-image-stream` to v3.1.0.
Link: https://github.com/resin-io-modules/etcher-image-stream/blob/master/CHANGELOG.md
> upgrade: `etcher-image-stream` to v3.1.0

- docs/CLI.md
- lib/cli/cli.js
- lib/cli/etcher.js
- lib/cli/writer.js
- lib/gui/models/selection-state.js
- lib/gui/models/store.js
- lib/gui/modules/image-writer.js
- lib/gui/os/dialog/services/dialog.js
- lib/gui/pages/finish/templates/success.tpl.html
- lib/gui/pages/main/controllers/flash.js
- lib/gui/pages/main/controllers/image-selection.js
- lib/src/child-writer/index.js
- lib/src/child-writer/utils.js
- npm-shrinkwrap.json
- package.json
- tests/gui/models/flash-state.spec.js
- tests/gui/models/selection-state.spec.js
- tests/gui/pages/main.spec.js
This PR integrates `.bmap` support recently added to
`etcher-image-write` into Etcher itself.
It does it in the following way:
- It adds a `--bmap` option to the Etcher CLI.
- It saves a potential `bmap` file contents to the
`SelectionStateModel`.
- In the GUI, at the time of writing, if there is a `bmap` file content
in `SelectionStateModel`, it gets written to a temporary file and such
path is passed as the `--bmap` option to the CLI.
Since validation checksums don't make sense anymore, the finish screen
doesn't show the checksum box in this case.
Changelog-Entry: Add `.bmap` support.
Fixes: https://github.com/resin-io/etcher/issues/171
> feat: integrate bmap support

- lib/gui/pages/main/templates/main.tpl.html
The current tooltip, "SHOW IN FULL", proved to be a bit confusing for
users. We're using "SHOW FULL FILE NAME", as kindly suggested by @dlech.
Fixes: https://github.com/resin-io/etcher/issues/634
Changelog-Entry: Improve image full file name modal tooltip.
> minifix(GUI): improve image full file name modal tooltip

- lib/gui/components/drive-selector/services/drive-selector.js
Steps to reproduce:
- Insert a single drive.
- Open drive selector modal.
- Extract the drive while drive selectector modal is open.
- Check DevTools.
The solution is to use `.close()` instead of `.dismiss()`. After some
diving into the documentation and the code, `.dismiss()` is only
available from within the modal controller, however if you want to close
the modal from outside, `.close()` is the way to go.
Notice that `.close()` returns a rejected promise when being called from
the modal itself, but thats not the case from outside, which is quite
confusing, but means we can safely use `.close()` in this context.
Changelog-Entry: Fix "`modal.dismiss` is not a function" exception.
> fix(GUI): "modal.dismiss" is not a function

- npm-shrinkwrap.json
- package.json
This version contains an optimisation that makes analysing archive
images (e.g: ZIP) for metadata much faster.
Changelog-Entry: Improve speed when retrieving archive image metadata.
> upgrade: `etcher-image-stream` to v3.1.1

- npm-shrinkwrap.json
- package.json
The changes we're interested in are:
- https://github.com/resin-io-modules/drivelist/pull/89
- https://github.com/resin-io-modules/drivelist/pull/91
Changelog-Entry: Upgrade `drivelist` to v3.3.0.
> upgrade: `drivelist` to v3.3.0

- lib/cli/writer.js
- npm-shrinkwrap.json
- package.json
The change we're interested in is:
- https://github.com/resin-io-modules/etcher-image-write/pull/51
Changelog-Entry: Prevent failed validation due to drive getting auto-mounted in GNU/Linux.
Fixes: https://github.com/resin-io/etcher/issues/574
> upgrade: `etcher-image-write` to v7.0.0

- docs/CLI.md
- lib/cli/cli.js
- lib/cli/etcher.js
- lib/cli/writer.js
- lib/gui/models/selection-state.js
- lib/gui/modules/image-writer.js
- lib/src/child-writer/index.js
- lib/src/child-writer/utils.js
- tests/gui/models/selection-state.spec.js
In order to get the bmap file contents to the Etcher CLI, we were
handling extraction, writing to a temporary file, then reading again,
and all sorts of other mumbo-jumbo, without realising that
`etcher-image-stream` already has this information right where we need
it (in the CLI's writer module) and in the way we need it (as plain
text).
Re-using from there hugely simplifies things.
> refactor: rely on `etcher-image-stream` to fetch bmap contents

- docs/USER-DOCUMENTATION.md
This entry documents all the GNU/Linux libraries needed to run Etcher.
Fixes: https://github.com/resin-io/etcher/issues/630
> docs(GUI): runtime linux libraries

- npm-shrinkwrap.json
- package.json
- https://github.com/resin-io-modules/etcher-image-write/pull/53
Changelog-Entry: Prevent `ENOSPC` if the drive capacity is equal to the image size.
Fixes: https://github.com/resin-io/etcher/issues/629
> upgrade: `etcher-image-write` to v7.0.1

- npm-shrinkwrap.json
- package.json
- https://github.com/resin-io-modules/etcher-image-stream/pull/27
Changelog-Entry: Fix incorrect estimated entry sizes in certain ZIP archives.
Fixes: https://github.com/resin-io/etcher/issues/644
> upgrade: `etcher-image-stream` to v3.1.2

- npm-shrinkwrap.json
- package.json
This version contains a fix for the `blkid: command not found` error in
certain GNU/Linux distributions.
- https://github.com/resin-io-modules/drivelist/pull/92
Changelog-Entry: Fix `blkid: command not found` error in certain GNU/Linux distributions.
Fixes: https://github.com/resin-io/etcher/issues/640
> upgrade: `drivelist` to v3.3.1

- build/css/main.css
- lib/gui/pages/main/styles/_main.scss
- lib/gui/pages/main/templates/main.tpl.html
- lib/gui/scss/main.scss
There are many SCSS rules in `lib/gui/scss/main.scss` that only apply to
the main page. In order to keep things tidy, those styles were moved to
`lib/gui/pages/main/styles/_main.scss`.
> refactor(GUI): move main page specific styles to pages/main/styles

- .scss-lint.yml
- .travis.yml
- appveyor.yml
- build/css/main.css
- docs/CONTRIBUTING.md
- lib/gui/scss/components/_alert-ribbon.scss
- lib/gui/scss/components/_button.scss
- lib/gui/scss/components/_label.scss
- lib/gui/scss/components/_modal.scss
- lib/gui/scss/components/_tick.scss
- lib/gui/scss/main.scss
- lib/gui/scss/modules/_bootstrap.scss
- package.json
This PR integrates SCSS Lint, a tool that will help us keep SCSS tidier.
I've included a sensible configuration at `.scss-lint.yml`, and
documentation on how to install it on `CONTRIBUTING.md`.
The tool will run automatically as part of `npm run lint`.
> chore(GUI): integrate scss-lint

- docs/RUNNING-LOCALLY.md
Packaging Etcher with NSIS v3.x results in weird errors. We only support
v2.x, for which the latest version is v2.51.
> docs: nsis required version

- .travis.yml
- appveyor.yml
`scss_lint` suddenly requires Ruby 2, which is breaking all our Travis
CI and Appveyor builds, which ship older versions.
> chore: upgrade ruby version in CI services

- build/css/main.css
- lib/gui/scss/components/_label.scss
`.label-danger` is defined by Bootstrap, and its coloring re-uses what
was defined in `$brand-danger`, which is currently unset.
To prevent the module from going out of sync with our new CSS palette,
we explicitly declare the colorings in the component file.
> refactor(GUI): explicitly declare `.label-danger` coloring

- build/css/main.css
- lib/gui/pages/main/styles/_main.scss
- lib/gui/scss/components/_badge.scss
Move `.badge` coloring to the main page's style file, since the style we
currently hardcode on the component itself is very tied to the
particular context the badge is being instantiated in.
> refactor(GUI): badge coloring

- build/css/main.css
- lib/gui/scss/components/_alert-ribbon.scss
- lib/gui/scss/modules/_bootstrap.scss
We have some global CSS rules that affect `.alert` living in
`_bootstrap.scss`, however `.alert` is only being used by our
`.alert-ribbon` component, so it makes sense to move those rules over
there.
> refactor(GUI): move `_bootstrap.scss` alert rules to `.alert-ribbon`

- build/css/main.css
- lib/gui/pages/finish/styles/_finish.scss
- lib/gui/pages/main/styles/_main.scss
- lib/gui/scss/components/_button.scss
The `.button` component is not the responsible of knowing the
`min-width` it should occupy in the actual pages.
> refactor(GUI): move button min-width rules to page styles

- lib/gui/pages/main/templates/main.tpl.html
This component is visually shown on the top of the window, however its
HTML code is placed below the "Flash" button, which is
counter-intuitive.
> refactor(GUI): move `alert-ribbon` to the top of the page

- npm-shrinkwrap.json
- package.json
- https://github.com/resin-io-modules/drivelist/pull/94
Changelog-Entry: Show device id if device doesn't have an assigned drive letter in Windows.
Fixes: https://github.com/resin-io/etcher/issues/671
> upgrade: `drivelist` to v3.3.3

- lib/gui/app.js
- lib/gui/index.html
- lib/gui/models/selection-state.js
- tests/gui/models/selection-state.spec.js
We've recently added support for a `supportUrl` property in an archive
image `_info/manifest.json`, which the publisher can use to define the
URL where it would like to redirect users facing problems.
This PR makes the "Need help?" link at the top right corner open the
configured `supportUrl` url, and fallback to the original Etcher's help
page if no `supportUrl` is found.
In order to accomplish this, we made the following changes:
- Implement `SelectionStateModel.getImageSupportUrl()`
- Implement `HeaderController` controller
Changelog-Entry: Make the "Need help?" link dynamically open the image support url.
Fixes: https://github.com/resin-io/etcher/issues/662
> feat(GUI): "Need help?" dynamically opens the image support url

- lib/gui/pages/main/templates/main.tpl.html
For consistency purposes on the main screen, we switch the "Connect a
drive" button to be the classic primary blue button as the other ones.
> style(GUI): make "Connect a drive" button blue

- lib/gui/pages/main/controllers/main.js
- lib/gui/pages/main/templates/main.tpl.html
- tests/gui/pages/main.spec.js
A function in the `MainController` was being named
`shouldFlashStateBeDisabled`, however it should have been
`shouldFlashStepBeDisabled`.
> style(GUI): fix `state` -> `step` typo in main controller

- lib/cli/etcher.js
The Etcher CLI displays a nice `Checksum: $checksum` message upon
completion. Since the addition of bmap support, a checksum for an image
might not be calculated, causing the CLI to display `Checksum:
undefined`.
This PR takes care of this small UX issue by only showing the checksum
message if one indeed exists.
> minifix(CLI): only show final checksum if one exists

- lib/gui/components/flash-error-modal/controllers/flash-error-modal.js
- lib/gui/components/flash-error-modal/flash-error-modal.js
If the user encounters a flash error, and then presses the "Retry"
button, the drive selection is cleared, but then is re-selected right
away because its probably the only available drive, leading to a very
strange behaviour UX-wise.
As a solution, we avoid clearing the drive selection.
Changelog-Entry: Don't clear the drive selection if clicking the "Retry" button.
> fix(GUI): don't clear drive selection if clicking "Retry"

- lib/gui/modules/error.js
This function used to handle `ENOSPC` as a corner case in order to
prevent it from being shown using the default Analytics/Dialog
machinery. This was because the "alert ribbon" used to react to changes
automatically from the templates, however, now that the "alert ribbon"
was removed, and replaced it with modals, we have finer control of how
and when this error gets shown, so the workaround is no longer
necessary.
See: https://github.com/resin-io/etcher/commit/951b8de9fc76821cf3140bd7e75c2d57ee8def21
> refactor(GUI): remove `ErrorService.reportException()` ENOSPC workaround

- npm-shrinkwrap.json
- package.json
This new version contains the following changes:
- Add `recommendedDriveSize` property in `_info/manifest.json`.
- Upgrade `unbzip2-stream` to v1.0.10, which fixes a known uncaught
exception when decompressing large `.bz2` files.
- Add support for markdown instructions at
`_info/instructions.markdown`.
Changelog-Entry: Upgrade `etcher-image-stream` to v4.3.0.
> upgrade: `etcher-image-stream` to v4.3.0

- lib/gui/components/drive-selector/controllers/drive-selector.js
- lib/gui/components/drive-selector/drive-selector.js
- lib/gui/components/drive-selector/templates/drive-selector-modal.tpl.html
- lib/gui/components/warning-modal/controllers/warning-modal.js
- lib/gui/components/warning-modal/services/warning-modal.js
- lib/gui/components/warning-modal/styles/_warning-modal.scss
- lib/gui/components/warning-modal/templates/warning-modal.tpl.html
- lib/gui/components/warning-modal/warning-modal.js
- lib/gui/models/selection-state.js
- lib/gui/models/store.js
- lib/gui/pages/settings/controllers/settings.js
- lib/gui/pages/settings/templates/settings.tpl.html
- lib/gui/scss/main.scss
- tests/gui/models/drives.spec.js
- tests/gui/models/selection-state.spec.js
Recently, we've added support for a `recommendedDriveSize` property in
the `manifest.json` of extended image archives, which the image can use
to warn the user that his drive, even if it is large enough to hold the
image, might not be large enough to deliver a good usage experience
later on.
When this property is found, the GUI reacts in the following ways:
- Drives that are large enough to hold the image but don't meet the
recommended drive size are tagged with a warning label in the drive
selector component.
- Attempting to select a "labeled" drive opens a warning modal asking
for user confirmation.
- Drives that don't meet the recommended drive size declared in the
image won't get auto-selected.
- If there is a drive already selected, and the user picks an image
whose recommended drive …
> feat(GUI): image-defined recommended drive size

- docs/USER-DOCUMENTATION.md
- lib/gui/app.js
This feature is very appealing when running Etcher ouside a common
desktop environment, for example, as a Resin.io application. In such a
platform, an update notifier that points the user to the website makes
no sense, since the platform itself is responsible for the update.
For such cases, we added support for an environment variable called
`ETCHER_DISABLE_UPDATES`, that when set, will prevent the update check
altogether.
Changelog-Entry: Allow the user to disable auto-update notifications with an environment variable.
> feat(GUI): allow disabling auto-update notifications

- docs/USER-DOCUMENTATION.md
Sometimes a flash error ends up taking the user's drive in a state that
can't be easily recover with usual disk utility tools. For when this
happens, we add some documentation about fail-proof methods to recover
the drive.
> doc: recovering broken drives

- npm-shrinkwrap.json
- package.json
This new version contains a fix for a very weird `cscript is not
recognised` error reported long ago.
Changelog-Entry: Fix "cscript is not recognised as an internal or external command" Windows error.
Fixes: https://github.com/resin-io/etcher/issues/552
See: https://github.com/resin-io-modules/drivelist/pull/95
> upgrade: `drivelist` to v3.3.4

- npm-shrinkwrap.json
- package.json
This version contains a fix for incorrect validation errors being
reported when flashing bzip2 files due to incorrect slicing of the drive
stream when calculating the checksum.
See: https://github.com/resin-io-modules/etcher-image-write/pull/61
Changelog-Entry: Fix incorrect validation errors when flashing bzip2 images.
Fixes: https://github.com/resin-io/etcher/issues/710
Fixes: https://github.com/resin-io/etcher/issues/709
> upgrade: `etcher-image-write` to v8.1.2

- .travis.yml
- docs/RUNNING-LOCALLY.md
- scripts/build/darwin.sh
This results in ~10MB savings, which is not much, but still worth
reducing as much as we can.
See: https://github.com/resin-io/etcher/issues/711
> chore: apply HFS+ compression to *.app in OS X

- npm-shrinkwrap.json
- package.json
This version contains an important fix for the sporadic EPERM issues
encountered on Windows systems.
Fixes: https://github.com/resin-io/etcher/issues/627
Link: https://github.com/resin-io-modules/etcher-image-write/blob/master/CHANGELOG.md
Changelog-Entry: Fix sporadic EPERM write errors on Windows.
> upgrade: `etcher-image-write` to v8.1.3

- lib/src/child-writer/writer-proxy.js
When the application is packaged as an AppImage, we're accidentally not
applying the whitespace escaping routine, causing images that contain
white spaces to cause Etcher to stall and never start the write.
The issue was even harder to debug given that the problem was not
reproducible when running Etcher from `npm start`.
Changelog-Entry: Fix flashing never starting after elevation in GNU/Linux.
Fixes: https://github.com/resin-io/etcher/issues/631
Fixes: https://github.com/resin-io/etcher/issues/665
> fix(GUI): no write after elevation in GNU/Linux

- docs/RUNNING-LOCALLY.md
Some of the packaging modules that we use don't work on previous NodeJS
versions.
Fixes: https://github.com/resin-io/etcher/issues/725
> docs: require at least NodeJS v6 to build Etcher

- scripts/build/linux.sh
I am playing around with debian packaging again. It is helpful to be able to build the electron package without building the appimage on linux.
> Allow building electron package separate from building appimage on linux

- scripts/build/linux.sh
Debian packaging tools cannot analyze the binaries if they are compressed
with upx. If we move the compression to the appimage command, then the
output of the package command can be used for building debian packages.
> Move upx compression to appimage command in linux build script

- docs/RUNNING-LOCALLY.md
We list all the pre-requisites needed to get up and running with Etcher,
and then say "run this script to install dependencies", which can be
interpreted as if the install script actually also installs the
pre-requisites, which is not the case.
To clarify this, we add a clear bold notice, and change "dependencies"
to "npm dependencies", to make the distinction clearer.
> docs: clarify that the install script doesn't install pre-requisites

- .travis.yml
There is no `g++-4.8` binary in OS X in Travis CI anymore for some
reason.
> chore: only alias CXX to specific gcc versions on Linux

- lib/gui/pages/settings/controllers/settings.js
- lib/gui/pages/settings/templates/settings.tpl.html
In Windows, if the user unmounts a drive, then the drive becomes
inaccessible to the OS. Compare this to UNIX based operating systems,
where an unmounted drive is still available for many I/O operations.
To prevent confusion, we say "eject" instead of "unmount" when running
on Windows, despite "unmount" being the correct way of saying it.
See: https://github.com/resin-io/etcher/issues/750
> style(GUI): say "eject" instead of "unmount" in Windows

- lib/gui/pages/main/controllers/image-selection.js
Currently, if the "CHANGE" label at the bottom of the image selection
step, once an image has been selected, is clicked, the selection state
is cleared.
Since https://github.com/resin-io/etcher/pull/602, we allow the drive
state to change independently of the image selection state, so the above
behaviour doesn't make sense anymore.
Fixes: https://github.com/resin-io/etcher/issues/730
Changelog-Entry: Don't clear selection state when re-selecting an image.
> fix(GUI): don't clear selection state when re-selecting an image

- npm-shrinkwrap.json
- package.json
- tests/gui/models/supported-formats.spec.js
We're particularly interested in the following change:
- Add `etch` support.
Also:
- Add a `.description` property to all archive related errors.
- Rename archive metadata base path from `_info` to `.meta`.
Changelog-Entry: Add support for `etch` images.
> upgrade: `etcher-image-stream` to v5.1.0

- scripts/build/debian/config.json
A policy kit authentication agent is needed for privilege escalation.
See: https://github.com/resin-io/etcher/issues/756#issuecomment-253298322
> chore(debian): add depedency on polkit package

- docs/USER-DOCUMENTATION.md
Document the need to have a polkit authentication running in GNU/Linux
to be able to go through the authentication system.
Fixes: https://github.com/resin-io/etcher/issues/756
> docs(GUI): no polkit authentication agent found Linux error

- docs/USER-DOCUMENTATION.md
Since the Etcher GUI is based on Electron, it only runs on platforms
supported by Electron, which in the case of macOS, is 10.9 and newer
versions.
As an alternative, we propose using the Etcher CLI.
See: https://github.com/electron/electron/blob/master/docs/tutorial/supported-platforms.md
Fixes: https://github.com/resin-io/etcher/issues/761
> docs(GUI): minimim macOS supported platform

- lib/gui/app.js
- lib/gui/pages/main/main.js
The "dropzone" directive, which we use to implement drag and drop
support, was not being loaded in the application at all for some reason.
It was probably accidentally deleted during major refactorings.
Changelog-Entry: Fix drag and drop not working anymore.
> fix(GUI): drag and drop not working anymore

- scripts/build/linux.sh
The `$output_package` variable is defined inside the `package_x$ARCH`
functions, which means that if we run the following commands:
```sh
./scripts/build/linux.sh package x64
./scripts/build/linux.sh appimage x64
```
The `$output_package` variable will not be defined when the script runs
the `appimage` command.
To workaround this issue, we declare a new `$package_directory` variable
inside the `appimage` command clause.
> chore: fix output_package unbound variable in GNU/Linux

- build/css/main.css
- lib/gui/pages/main/styles/_main.scss
- lib/gui/pages/main/templates/main.tpl.html
The main purpose of this change is to simplify the interface and avoid
unnecessary text.
Fixes: https://github.com/resin-io/etcher/issues/742
Changelog-Entry: Use info icon instead of "SHOW FULL FILE NAME" in first step.
> feat(GUI): use info icon instead of "SHOW FULL FILE NAME"

- scripts/build/darwin.sh
- scripts/build/linux.sh
We translate function arguments (e.g: `$1`, `$2`, etc) to readable names
using shell variables in the top of every shell function in the build
scripts.
Since we were not declaring these variables as `local`, two functions
using the same "argument name" would override each other.
For example:
```sh
function foo() {
variable=$1
}
function bar() {
variable=$1
}
foo "Hello World"
echo $variable
> Hello World
bar "Changed variable"
echo $variable
> Changed variable
```
> refactor: use local variables in shell functions in build scripts

- scripts/build/linux.sh
AppImages need to be marked as executables before they can be used.
Distributing them directly means that virtually all web browsers will
automatically remove the execution permissions, leading us to have to
explain users how to add it back with `chmod`, etc.
For simplicity purposes, we'll be distributing AppImages inside ZIPs,
which ensure the execution permissions are added back when the user
decompresses it.
> chore: distribute AppImage inside a zip

- appveyor.yml
- docs/RUNNING-LOCALLY.md
- scripts/build/windows.bat
This PR zips the package that is built by running:
```sh
.\scripts\build\windows.bat package <arch>
```
And puts it in `etcher-release/installers`.
Fixes: https://github.com/resin-io/etcher/issues/760
Changelog-Entry: Publish standalone Windows builds.
> chore: create standalone Windows builds

- lib/src/child-writer/writer-proxy.js
- scripts/build/AppImages/desktopintegration
If we pass relative paths as arguments to the AppImage, they get
resolved from `/tmp/.mount_XXXXXX/usr`. We can exploit this to run the
Etcher CLI directly from the AppImage, rather than having to mount it
ourselves:
```sh
ELECTRON_RUN_AS_NODE=1 Etcher-linux-x64.AppImage bin/resources/app.asar [OPTIONS]
```
By using this little trick, we get rid of both our custom mounting logic
and the need of surrounding the command to run in single quotes,
therefore avoiding a whole new kind of escaping issues.
Since running the CLI directly from the AppImage means that the
`desktopintegration` will be ran for the CLI, we pass the `SKIP`
environment variable to avoid having it prompt the user for
installation.
We also updated the `desktopintegration` script to the latest version,
which reduces the …
> feat(GUI): spawn CLI directly from the AppImage in GNU/Linux

- scripts/build/linux.sh
When running the install script as root (e.g. inside a Docker container), bower complained that it
"shouldn't" be run with sudo. When running the x86 install multiple times, it tried to move
Etcher-linux-ia32 inside the existing Etcher-linux-x86/ folder, rather than renaming it, which meant
later commands failed.
> chore: Fix minor install script problems

- scripts/build/darwin.sh
- scripts/build/linux.sh
- scripts/build/windows.bat
This works towards #763 on Windows, in theory. I haven't tested it (because installing the dependencies would be a pain) but it seems to be the right thing to do. This does not make any changes for other OSes.
> Include Etcher version in installer/archive names

- lib/src/child-writer/utils.js
- lib/src/child-writer/writer-proxy.js
This PR makes sure every command line argument that represents an
absolute path is surrounded by double quotes, to avoid any potential
escaping issue.
This simplifies a lot the various special character escaping routines we
had in place, since we now only have to make sure double quotes inside
the paths are escaped.
Fixes: https://github.com/resin-io/etcher/issues/773
Changelog-Entry: Prevent escaping issues during elevation by surrounding paths in double quotes.
> fix(GUI): surround paths in double quotes before elevating

- scripts/build/linux.sh
While the previous fix in #777 fixed repeated builds, it accidentally broke the first build!
> chore: fix linux x86 build script

- docs/USER-DOCUMENTATION.md
The AppImage `desktopintegration` prompt can also be disabled by setting
the `SKIP` environment variable.
As a matter of fact, we use this trick inside Etcher itself when
executing the Etcher CLI as a child process of the Etcher GUI.
> docs(GUI): skip AppImage desktop integration prompt with SKIP

- docs/USER-DOCUMENTATION.md
We're now including the version as part of the filename, which means
`Etcher-linux-x64` is no longer 100% accurate. As a solution, we include
a filename with "placeholders" for the version and architecture, to
avoid harcoding a specific version.
See: https://github.com/resin-io/etcher/commit/18e9d1eb11104daab92448f07a3cdfeaa4735c15#commitcomment-19619181
See: https://github.com/resin-io/etcher/pull/764
Signed-off-by: Juan Cruz Viotti jviotti@openmailbox.org
> docs(GUI): generic appimage name in desktopintegration SKIP instructions

- lib/gui/modules/drive-scanner.js
- npm-shrinkwrap.json
- package.json
- tests/gui/modules/drive-scanner.spec.js
If a drive contains multiple partitions that Windows recognises and
mounts, then `drivelist` will incorrectly display separate drive objects
for each partition, causing `ngRepeat` to complain in the drive selector
component.
The issue was fixed by grouping the mountpoints of all recognised
partitions in a single drive object, as we do with the other supported
operating systems.
After the fix, `drivelist` also removed its `name` property (since its
now always equal to `device`), so some extra logic to compute an
appropriate display name for the drive has been introduced to
`DriveScannerService`.
Fixes: https://github.com/resin-io/etcher/issues/720
See: https://github.com/resin-io-modules/drivelist/pull/100
Changelog-Entry: Fix duplicate drives in Windows.
Signed-off-by: …
> fix(GUI): duplicate drives in Windows

- docs/USER-DOCUMENTATION.md
The usual case is images requiring special treatment. We recommend the
users to use specialised tooling for those cases.
Signed-off-by: Juan Cruz Viotti jviotti@openmailbox.org
> docs(GUI): explain why some drives are not bootable out of the box

- .hound.yml
We are not using Hound CI to display lint warnings anymore. The CI
servers are in charge of running the linters now.
> chore: remove `.hound.yml`

- README.md
- lib/gui/components/update-notifier/templates/update-notifier-modal.tpl.html
- lib/gui/index.html
The current url we use, http://etcher.io, now redirects to
https://www.etcher.io.
Fixes: https://github.com/resin-io/etcher/issues/794
> chore: update homepage URL to https://www.etcher.io

- docs/USER-DOCUMENTATION.md
The ZIP including the AppImage contains the version, but not the
AppImage itself.
See: https://github.com/resin-io/etcher/pull/786#issuecomment-257275494
> docs(GUI): remove `<version>` from AppImage name

- appveyor.yml
Setting a Chocolatey cache and Making sure it gets persisted means that
future builds don't have to download every Chocolatey package from the
internet every time.
> chore: persist a chocolatey cache Appveyor CI builds

- docs/CLI.md
The `docs/CLI.md` points to user to `docs/CONTRIBUTING.md` for
instructions in how to install dependencies. This document previously
included the explicit `npm` commands to run, but was then changed to
point to the platform scripts, which means that if the user follows the
current instructions but has a NodeJS version which is not ABI
compatible with the NodeJS version used by the currently used Electron
version, the user will get an incompatibility error.
Fixes: https://github.com/resin-io/etcher/issues/801
> docs(CLI): describe proper way to install dependencies

- lib/cli/cli.js
`yargs` wraps help output lines, causing the examples to be displayed
like this:
```
Examples:
/usr/bin/nodejs bin/etcher
raspberry-pi.img
/usr/bin/nodejs bin/etcher --no-check
raspberry-pi.img
/usr/bin/nodejs bin/etcher -d /dev/disk2
ubuntu.iso
/usr/bin/nodejs bin/etcher -d /dev/disk2
-y rpi.img
```
As a solution, we can set `.wrap(null)` to completely disable wrapping.
Fixes: https://github.com/resin-io/etcher/issues/810
> style(CLI): don't wrap CLI help outputdrives

- lib/src/child-writer/index.js
Currently, we are not making sure the IPC server we start at
`lib/src/child-writer/index.js` gets closed when the child process exits
(successfully or not). This eventually causes issues when the user click
"flash again", since the stateful `ipc` global exposed by `node-ipc`
gets initialised again, causing the module to get to an invalid state
that eventually results in `this.log is not a function`.
- We've added `ipc.server.stop()` to both the `error` and `close` event
handlers (which are self exclusive, according to the docs).
- We've added `child.kill()` to the child `stderr` handler, since that
function causes the `close` event to be triggered, which in turns
calls `ipc.server.stop()`.
Changelog-Entry: Fix `this.log is not a function` error when clicking "flash …
> fix(GUI): close IPC server after writing

- npm-shrinkwrap.json
- package.json
- This new version passes `force` to `diskutil unmountDisk`
Changelog-Entry: Fix `at least one volume could not be unmounted` error in OS X.
> upgrade: `umount` to v1.1.4

- lib/gui/pages/main/controllers/image-selection.js
The new ordering of the main supported extensions will be: `img`, `iso`,
`zip`.
We make use of `_.intersection` in order to ensure that the values we're
hardcoding indeed exist in the list of all supported format extensions,
otherwise they won't appear at all. This ensures we never show
extensions that are not supported.
Partly fixes: https://github.com/resin-io/etcher/issues/787
> style(GUI): improve ordering of supported extensions

- lib/gui/pages/settings/controllers/settings.js
There are some settings, such as "unsafe mode", that prompt the user for
confirmation before actually confirming the setting. In these cases,
when the user attempts to check the checkbox, the checkbox remains
checked unless the user rejects the confirmation dialog, in which case
the checkbox value is reverted.
In order to provide a better UX, we now keep the checkbox unchecked
until the user confirms.
See: https://github.com/resin-io/etcher/issues/729
> minifix(GUI): keep settings checkboxes unchecked until user confirms

- package.json
This dependency is already being listed in `optionalDependencies`, which
the place it really belongs to.
> chore: remove `removedrive` from `dependencies`

- README.md
- package.json
Repository description says "Flash OS images to SD cards & USB drives,
safely and easily.", while `package.json` currently says "An image
flasher with support for Windows, OS X and GNU/Linux.", and `README.md`
contains "Flash OS images to SD cards & USB drives, safe & easy."
See: https://github.com/resin-io/etcher/issues/797
> chore: update package.json and README.md to match repo description

- lib/gui/components/warning-modal/services/warning-modal.js
The `settings-dangerous-modal` modal size class doesn't exist anymore,
and was renamed to `warning-modal`. This was causing the exclamation
sign from the header to not be displayed in red, as it should.
> minifix(GUI): warning modal size class

- npm-shrinkwrap.json
- package.json
We're interested in the following change, which causes the last
unaligned block on an image to be aligned to 512K instead of to 1M if
its smaller than 512K, and to 1M otherwise.
- https://github.com/resin-io-modules/etcher-image-write/pull/58
Fixes: https://github.com/resin-io/etcher/issues/685
Changelog-Entry: Fix "Not Enough Space" error when flashing unaligned images.
> upgrade: `etcher-image-write` to v8.1.4

- build/css/main.css
- lib/gui/components/drive-selector/controllers/drive-selector.js
- lib/gui/components/warning-modal/controllers/warning-modal.js
- lib/gui/components/warning-modal/services/warning-modal.js
- lib/gui/components/warning-modal/styles/_warning-modal.scss
- lib/gui/components/warning-modal/templates/warning-modal.tpl.html
- lib/gui/pages/settings/controllers/settings.js
- lib/gui/pages/settings/templates/settings.tpl.html
- Change dialog message to "Are you sure you want to turn this on? You
will be able to overwrite your system drives if you're not careful."
- Remove "CANCEL" button and put a cross at the top right corner.
- Change dialog button label from "YES, CONTINUE" to "ENABLE UNSAFE
MODE"
In order to adapt to changes described above:
- `WarningModalService.display()` now takes an object including
`description`, and `confirmationLabel`
Fixes: https://github.com/resin-io/etcher/issues/729
> minifix(GUI): improve unsafe mode setting dialog

- lib/gui/components/update-notifier/templates/update-notifier-modal.tpl.html
Every modal in the application should contain the same "close" X at the
top right corner, for consistency purposes. The only modal lacking this
button was the update notifier modal.
> style(GUI): unify "close" top right corner X in all modals

- npm-shrinkwrap.json
- package.json
The changes we're interested in are:
- Escape device paths containing spaces.
Changelog-Entry: Fix unmount issues in GNU/Linux and OS Xwhen paths contain spaces.
> upgrade: `umount` to v1.1.5

- package.json
This key is added as the long description of the Debian package.
Omitting this option means that `description` is duplicated two times,
which is of course not the desired outcome.
See: https://github.com/resin-io/etcher/issues/632
> chore: add `productDescription` to `package.json`

- docs/PUBLISHING.md
Publishing to Homebrew Cask involves changing a Cask file in the
official Cask registry pull request updating the `version` and `sha256`
properties.
See: https://github.com/caskroom/homebrew-cask/pull/26319
> docs(GUI): publishing a new version to homebrew cask

- tests/gui/pages/main.spec.js
This was a small issue affected due to the change in order of the
supported extensions in the ImageSelectionController.
Since we want to test that the array contents are equally the same
independently on the order, we sort both sides of the assertion.
This issue was not caught before since `electron-mocha` was reporting
exit code 0 even when there were changes failing, causing the CI
services to incorrectly support success.
See: https://github.com/resin-io/etcher/pull/854
See: https://github.com/resin-io/etcher/pull/806
> test: fix failing ImageSelectionController tests

- npm-shrinkwrap.json
- package.json
The current version would exit with error code 0 even when the tests
failed, causing CI servers to report false positives.
> upgrade: `electron-mocha` to v3.1.1

- lib/gui/pages/finish/templates/success.tpl.html
Currently, the wording "same" versus "new" on the completion screen
is ambiguous when they respectively mean use the same image file, or use a new
and different image file. Therefore, change the wording from "new" to
"different".
Closes: https://github.com/resin-io/etcher/issues/839
Changelog-Entry: Clarify wording on completion page.
> fix(gui): clarify wording at finished flash prompt (new → different)

- README.md
Use full URL with port for key server. Also use port 80 to work around firewalls and proxies.
Fixes: #859
> docs: more explicit key server

- lib/cli/unmount.js
- lib/cli/writer.js
- npm-shrinkwrap.json
- package.json
- tests/cli/unmount.spec.js
- Move UNIX unmount functionality to the CLI module
- Run `electron-mocha` for the CLI code
- Make unmount command templates that take a `drivelist` object as input
> refactor(CLI): move UNIX umount functionality to repository

- lib/cli/etcher.js
The CLI requires elevation permissions to actually be able to write to
drives. For this reason, it makes sense that we introduce such a check
early on.
See: https://github.com/resin-io/etcher/issues/726
Changelog-Entry: Check available permissions in the CLI early on.
> fix(CLI): check CLI elevation early on

- lib/src/child-writer/writer-proxy.js
Turns out that when the parent process gets SIGKILL, the children
process would still remain alive.
In order to mitigate this, we force the IPC client opened by the child
writer to not attempt to reconnect to the IPC server if this one dies,
so we can catch the "disconnect" event and kill the children as a
result.
Fixes: https://github.com/resin-io/etcher/issues/850
Changelog-Entry: Fix writing process remaining alive after the GUI is closed.
> fix(GUI): kill CLI processes when child writer dies

- lib/cli/unmount.js
- lib/gui/modules/drive-scanner.js
- npm-shrinkwrap.json
- package.json
- tests/gui/modules/drive-scanner.spec.js
- Fix internal SDCard reader descriptions in GNU/Linux.
- Transform `mountpoint` into an array of mountpoints.
Changelog-Entry: Fix internal SDCard drive descriptions.
> upgrade: `drivelist` to v5.0.1

- npm-shrinkwrap.json
- package.json
See: https://github.com/resin-io-modules/drivelist/pull/120
Fixes: https://github.com/resin-io/etcher/issues/870
Changelog-Entry: Fix `0x80131700` error when scanning drives on Windows.
> upgrade: `drivelist` to v5.0.3

- lib/src/child-writer/index.js
If the child process (e.g: writer proxy, or CLI) emits either an error,
or an invalid output, the error will be emitted to the GUI, which will
report it to the state machine, however the IPC server will keep
receiving further messages, which will be passed to the GUI, which will
keep trying to update the state, in which case Redux will rightfully
complain that we can't update the flashing state if there is no flash in
process.
As a solution, we make sure the IPC server is terminated on every
possible error code flow, and to do this effectively, we needed to
manually destroy every connected socket before actually closing the
server.
Changelog-Entry: Fix "Can't set the flashing state when not flashing" error.
> fix(GUI): terminate IPC server on any errors

- lib/gui/components/modal/services/modal.js
Pressing the ESC key in any modal dialogue currently just emits a
message. This change actually cancels the modal, closing it.
Closes: https://github.com/resin-io/etcher/issues/874
Changelog-Entry: Allow the user to press ESC to cancel a modal dialog.
> fix(GUI): pressing escape cancels modal dialogue

- lib/gui/components/modal/services/modal.js
Currently we resolve `false`, which might not mean very much to some
modal use cases. `undefined` is a much more generic falsy value.
> refactor(GUI): resolve undefined on modal keyboard bindings

- scripts/build/darwin.sh
- scripts/darwin/dependencies.sh
- scripts/darwin/installer-dmg.sh
- scripts/darwin/installer-zip.sh
- scripts/darwin/package.sh
- scripts/darwin/sign.sh
This is the first step towards decoupling the build system as many
different scripts, for maintainability and convenience purposes.
> refactor: extract OS X build script into many files

- build/css/main.css
- lib/gui/components/drive-selector/styles/_drive-selector.scss
Drives with long names or descriptions expand outside the drivelist,
this commit fixes that using CSS `word-break: break-all`.
Changelog-Entry: Wrap drive names and descriptions in drivelist.
> fix(GUI): wrap long words in drivelist

- scripts/darwin/dependencies.sh
We don't really do x64 builds for OS X at the moment, but nice to make
the build scripts consistent.
> chore: add x86 architecture support for darwin/dependencies.sh

- npm-shrinkwrap.json
- package.json
These dependencies are suddently causing issues when running `npm
install` in platforms other than OS X.
> chore: add `appdmg` and `ds-store` to `shrinkwrapIgnore`

- npm-shrinkwrap.json
- package.json
- https://github.com/resin-io-modules/drivelist/pull/125
Changelog-Entry: Fix drive scanning exceptions on GNU/Linux systems with `net.ifnames` enabled.
> upgrade: `drivelist` to v5.0.4

- lib/cli/cli.js
This is a great simplification to the logic previously included in the
Yargs `.parse()` function on the Etcher CLI.
There is no scenario where the CLI script will be executed in a
standalone fashion (e.g: `etcher.js <options>`), so we can always safely
drop the first two elements from `process.argv`.
Changelog-Entry: Fix command line arguments not interpreted correctly when running the CLI with a custom named NodeJS binary.
> fix(CLI): always omit first two elements of process.argv

- scripts/build/darwin.sh
- scripts/build/linux.sh
- scripts/unix/package-cli.sh
This is the first step towards properly publishing the Etcher CLI. The
option is not present in Windows yet, and its intentionally undocumented
for the time being.
See: https://github.com/resin-io/etcher/issues/355
> chore: add "cli" command to GNU/Linux and OS X build script

- scripts/build/linux.sh
- scripts/linux/package.sh
In order to take a whitelisting approach to dependencies, the
`unix/dependencies.sh` script is ran as part of packaging as well, but
passing the `-p` (production) flag.
In the future, the current `install`, `package`, and `installer` targets
will be deplaced by `develop-<type>`, `installer-<type>`.
> refactor: get rid of `electron-packager` in GNU/Linux

- .travis.yml
- docs/PUBLISHING.md
- docs/RUNNING-LOCALLY.md
- scripts/build/linux.sh
- scripts/linux/installer-appimage.sh
- scripts/linux/package.sh
The GNU/Linux build script (as the rest of the OSes will in the near
future), now accepts the following command:
- `develop-electron`
- `develop-cli`
- `installer-cli`
- `installer-appimage`
- `installer-debian`
Each of the commands is now completely independent from the others.
> chore: adopt new build script command convention in GNU/Linux

- package.json
- scripts/darwin/sign.sh
Making use of `codesign` directly allows us to have much more
flexibility in how we sign things, which will prove very valuable when
adapting this `sign.sh` script to code sign the Etcher CLI.
> refactor: ditch `electron-osx-sign` for OS X signing

- .travis.yml
- docs/PUBLISHING.md
- docs/RUNNING-LOCALLY.md
- scripts/build/darwin.sh
- scripts/darwin/installer-dmg.sh
- scripts/darwin/package.sh
- scripts/linux/package.sh
- scripts/unix/create-asar.sh
The `darwin.sh` script now accepts the following commands:
- `develop-electron`
- `installer-dmg`
- `installer-zip`
In order to accomplish this, `./scripts/darwin/package.sh` is no longer
relying on `electron-packager`.
> chore: adopt new build command convention for OS X

- scripts/build/linux.sh
We were accidentally hardcoding the installer generation to `x64`.
See: https://github.com/resin-io/etcher/pull/896#discussion_r89999295
> fix: don't lock `installer-cli` architecture to x64 in build scripts

- scripts/build/darwin.sh
- scripts/build/linux.sh
- scripts/darwin/installer-dmg.sh
- scripts/darwin/installer-zip.sh
- scripts/darwin/package.sh
- scripts/darwin/sign.sh
- scripts/linux/installer-appimage.sh
- scripts/linux/installer-deb.sh
- scripts/linux/package.sh
- scripts/publish/aws-s3.sh
- scripts/publish/bintray-debian.sh
- scripts/unix/create-asar.sh
- scripts/unix/dependencies.sh
- scripts/unix/download-electron.sh
- scripts/unix/package-cli.sh
This refactors the way that the build shell-scripts check for dependencies
in order to cut down on code duplication, and also adds additional
dependency-checks that were missing previously.
> chore: refactor and enhance dependency checking in build scripts

- build/css/main.css
- lib/gui/components/drive-selector/styles/_drive-selector.scss
The cursor is incorrectly a pointer on hover over a disabled and
unselectable drive in the drive selector widget. This patch changes the
cursor to `not-allowed`, providing the user with visual feedback that it is
not selectable.
Fixes: https://github.com/resin-io/etcher/issues/865
Changelog-Entry: Use not-allowed cursor over disabled drives in the
drive selector widget.
> fix(GUI): show not-allowed cursor over unselectable drives

- lib/gui/components/drive-selector/controllers/drive-selector.js
- lib/gui/components/drive-selector/templates/drive-selector-modal.tpl.html
The user can now double-click to swiftly select a drive in the
drive widget instead of having to toggle a drive and then clicking the
continue button to close the modal and finalize the drive selection.
Closes: https://github.com/resin-io/etcher/issues/880
Changelog-Entry: Implement double-click to quick-select drives in the
drive widget.
> feat(GUI): allow double-click to quick-select drives

- scripts/build/windows.bat
- scripts/windows/dependencies.bat
The logic to install dependencies on Windows now separately lives in
`scripts/windows/dependencies.bat`, similarly to what we've been done
with other operating systems.
> chore: extract dependencies.bat from windows.bat

- scripts/build/darwin.sh
- scripts/build/linux.sh
- scripts/darwin/configure-electron.sh
- scripts/linux/configure-electron.sh
- scripts/unix/create-electron-app.sh
- scripts/unix/dependencies.sh
Previously, the build scripts would override the top level
`node_modules` and `bower_components`. After this commit, the
dependencies are installed directly in the Electron package.
> chore: install dependencies directly in package

- appveyor.yml
We tried to save the Chocolatey cache in a previous PR, but it looks
like its not working properly. This PR implements the "correct" way to
cache Chocolatey installs, as recommended in Appveyor forums.
The arrows mean that the cache is invalidated if the file in the right
side (`appveyor.yml`) in this case, is changed.
See: http://help.appveyor.com/discussions/suggestions/592-speeding-up-chocolatey-downloads-and-installs
See: https://github.com/resin-io/etcher/commit/e603cb0838b005f1c8430bbce4c98b431d9c1ba9
> chore: cache chocolatey installs as recommended by Appveyor

- scripts/build/darwin.sh
- scripts/build/linux.sh
- scripts/unix/dependencies-bower.sh
- scripts/unix/dependencies-npm.sh
The purpose of this change is to stay true to the Makefile approach,
where each rule is meant to create a single directory/file.
Currently, `unix/dependencies.sh` resulted in `bower_components` and
`node_modules`. Splitting this rule also means that we don't have to
install bower dependencies where we don't need them (e.g: the CLI).
> chore: split `dependencies.sh` into bower and npm scripts

- scripts/darwin/configure-electron.sh
- scripts/darwin/installer-dmg.sh
- scripts/darwin/installer-zip.sh
- scripts/darwin/sign.sh
- scripts/linux/configure-electron.sh
- scripts/linux/installer-appimage.sh
- scripts/linux/installer-deb.sh
- scripts/unix/create-asar.sh
- scripts/unix/create-electron-app.sh
- scripts/unix/dependencies-npm.sh
- scripts/unix/download-electron.sh
- scripts/unix/package-cli.sh
We're currently exitting with error code 0 when displaying the usage
information on build scripts, which means that if the user forgets or
mistypes an option argument, the script will carry on its way.
> chore: exit with error code 1 on build script usage section

- scripts/build/linux.sh
- scripts/linux/electron-installer-appimage.sh
Currently, `installer-appimage` creates only the AppImage, and we rely
on code outside the main task to package it up as a Zip. Since Zip is
a required step for AppImage deployment (since the AppImage will lose
its execution permissions if its moved around), we integrate Zip
generation into the AppImage task itself.
> chore: move GNU/Linux zip generation to `installer-appimage`

- Makefile
- scripts/unix/dependencies-bower.sh
- scripts/unix/dependencies-npm.sh
- scripts/unix/electron-create-resources-app.sh
Currently, we create a "resources app" and install dependencies on it.
This means that to create another "resources app", the whole dependency
installation process needs to be repeated.
As a solution, we cache dependencies at
`release/electron-$(TARGET_PLATFORM)-$(TARGET_ARCH)-dependencies/` and
copy them to the resources apps as we need them.
This has the additional benefit that the resources app depends on the
dependencies rather than the other way around (dependencies depend on
the resources app), which didn't feel right.
In order to accomodate to these changes, the dependencies scripts are
now in charge of taking their corresponding manifests with them when the
prefix option is passed, given that neither `npm` nor `bower` allow to
customise the output location.
Signed-off-by: Juan …
> chore: reuse npm/bower dependencies across builds

- scripts/linux/electron-installer-appimage.sh
We currently hardcode the temporary directory location to `/tmp`. Some
Linux systems define `$TMPDIR`, so we should attempt to re-use that
first.
> chore: attempt to re-use $TMPDIR in `installer-appimage.sh`

- scripts/publish/bintray-debian.sh
This change prevents the script erroring with `BINTRAY_USER: unbound variable` when `$BINTRAY_USER` isn't defined, and instead displays the "Please define the following ..." message as expected.
> chore: fix the bintray-debian publishing script

- scripts/unix/dependencies-npm.sh
NPM might create an empty `etc/` directory when calling it with the
`--prefix` option and we have a check to see if this directory indeed
exists and its empty in order to proceed and delete it.
We currently use `rm -rf` for it, even though `rmdir` is sufficient.
See: https://github.com/resin-io/etcher/pull/923#discussion_r90570968
> chore: use `rmdir` to delete empty npm `etc/` directory

- build/css/main.css
- lib/gui/components/modal/styles/_modal.scss
- lib/gui/components/update-notifier/templates/update-notifier-modal.tpl.html
We add a blue clickable link to the Github changelog in the update dialog
below the modal body text.
Closes: https://github.com/resin-io/etcher/issues/905
Changelog-Entry: Add a changelog link to the update notifier modal.
> feat(gui): add changelog link to update notifier

- build/css/main.css
- lib/gui/app.js
- lib/gui/components/modal/styles/_modal.scss
- lib/gui/components/warning-modal/services/warning-modal.js
- lib/gui/components/warning-modal/templates/warning-modal.tpl.html
When Etcher is writing to a drive and the user closes the window,
currently there is no confirmation. This commit changes that and
the user has to confirm the exit.
Other changes include the warning modal taking a `rejectionLabel` option
that shows a reject button when provided.
Closes: #744
Changelog-Entry: Confirm before user quits while writing.
> feat(GUI): confirm before quitting etcher while writing

- scripts/unix/dependencies-bower.sh
The reason for this change is to make things more explicit.
See: https://github.com/resin-io/etcher/pull/923#discussion_r90571316
> chore: move `bower.json` removal after popd in `dependencies-bower.sh`

- Makefile
- scripts/darwin/electron-configure-package-darwin.sh
- scripts/linux/electron-configure-package-linux.sh
- scripts/unix/electron-download-package.sh
Currently, `scripts/unix/electron-download-package.sh` contains its own
logic to determine if the package was already downloaded.
This commit takes the electron package uncompressing task to the
configure scripts, and reduce `electron-download-package.sh` to a script
that simply downloads the zip to a certain location, since this change
allows us to have a separate Make rule to download the Electron zip (and
thus have Make take care of caching).
After this change, the `electron-configure-package-*.sh` scripts are no
longer routines that modify a certain directory, but scripts that take
the zip as an input and actually create the package directory, which
aligns better with Make's design.
> chore: move electron package caching responsibility to GNU Make

- .travis.yml
After our recent changes, the command to install dependencies for both
OS X and GNU/Linux has been unified as `make electron-develop`, so there
is no longer a need to have multiple conditionals for each OS in
`.travis.yml`.
> chore: simplify .travis.yml dependencies installation across OSes

- scripts/unix/dependencies-npm.sh
We currently use the `--prefix` option in `dependencies-npm.sh` to
install dependencies in another directory, however that function causes
ENOSELF to be thrown on Windows under Msys. As a solution, we take the
same `pushd`/`popd` approach as we do in `dependencies-bower.sh`.
> chore: use `pushd`/`popd` instead of `--prefix` on `dependencies-npm.sh`

- Makefile
- scripts/darwin/electron-create-readonly-dmg.sh
- scripts/darwin/electron-create-readwrite-dmg.sh
- scripts/darwin/electron-sign-dmg.sh
Code-signing in OS X now relies on the presence of a
`CODE_SIGN_IDENTITY` variable. If it doesn't exist, all the builds will
gracefully complete without code-signing.
As a consequence of this change, the `electron-installer-dmg.sh` script
has been divided into `electron-create-readwrite-dmg.sh`,
`electron-create-readwrite-dmg.sh`, and `electron-sign-dmg.sh`.
> chore: make code-signing optional in OS X

- scripts/unix/electron-create-asar.sh
This change is needed to make `electron-create-asar.sh` output valid
asar packages on Windows (Msys).
> chore: don't include *.dll files inside the asar archive 

- lib/gui/app.js
- lib/gui/components/update-notifier/controllers/update-notifier.js
- lib/gui/components/update-notifier/services/update-notifier.js
- lib/gui/components/update-notifier/templates/update-notifier-modal.tpl.html
We show the Etcher version string in the update notifier modal, by giving
the version string to the template through options similar to the warning
modal.
- We memoize the version Promise and assume the update version won't change
during runtime.
Changelog-Entry: Show available Etcher version in the update notifier.
> feat(gui): show available version in update notifier modal

- appveyor.yml
- docs/RUNNING-LOCALLY.md
- scripts/unix/dependencies-npm.sh
This version was not working the last time we checked, but it looks like
there were some advancements in node-gyp in the previous months, and all
dependencies have upgraded to it already.
> chore: upgrade Etcher build system to use Visual Studio 2015

- Makefile
Also sets `help` as the default target, so that typing just `make` displays
the list of possible targets. Also customises the list of targets based on
TARGET_PLATFORM (because you can't build e.g. `electron-installer-dmg` when
you're on Linux).
> chore: add `help` Makefile target to show available targets

- .travis.yml
- Makefile
- docs/RUNNING-LOCALLY.md
By changing the `Makefile` to use `jq` instead of `node` for getting settings
from `package.json`, the time to do `make help` drops from over 1.5 seconds to
under 0.05 seconds!
> chore: speed up `make` startup time by using `jq`

- docs/PUBLISHING.md
We are now going to be adding links to files published in AWS S3 in
GitHub Releases, so that people used to finding pre-built versions of
the software in GitHub Releases will be re-directed to the right place,
while we still keep the analytics advantages that S3 provides us.
> docs: remind to add S3 links to GitHub Releases entries

- Makefile
- docs/PUBLISHING.md
Currently `publish-aws` and `publish-debian` for Linux, and `publish-aws`
for OSX. Like all phony targets, these get displayed by `make help`.
> chore: add publishing Makefile targets

- scripts/build/dependencies-npm.sh
- The Electron npm headers can now be downloaded from
https://atom.io/download/electron
- We can configure gyp to build from source by using the
`npm_config_build_from_source` environment variable rather than having
to pass `--build-from-source`
> chore: update npm configuration in `dependencies-npm.sh`

- scripts/build/check-dependency.sh
- scripts/build/dependencies-bower.sh
- scripts/build/dependencies-npm.sh
- scripts/build/download-tool.sh
- scripts/build/electron-configure-package-darwin.sh
- scripts/build/electron-configure-package-linux.sh
- scripts/build/electron-create-asar.sh
- scripts/build/electron-create-readonly-dmg-darwin.sh
- scripts/build/electron-create-readwrite-dmg-darwin.sh
- scripts/build/electron-download-package.sh
- scripts/build/electron-installer-app-zip-darwin.sh
- scripts/build/electron-installer-appimage-linux.sh
- scripts/build/electron-installer-debian-linux.sh
- scripts/build/electron-sign-app-darwin.sh
- scripts/build/electron-sign-dmg-darwin.sh
- scripts/build/electron-sign-exe-win32.sh
- scripts/build/package-cli.sh
- scripts/publish/bintray-debian.sh
We have a little snippet to check if a dependency is installed on the
system that we're literally copy-pasting in every single script in the
build system script collection.
For re-usability purposes, this snippet has been extracted to a
`check-dependency.sh` that is called by every script that needs it.
> chore: create re-usable check-dependency.sh script

- scripts/build/electron-sign-dmg-darwin.sh
`electron-sign-dmg-darwin.sh` was incorrectly referring to
`scripts/build/electron-sign-app-darwin.sh` as
`scripts/darwin/electron-sign-app.sh`, causing the DMG builds to fail in
OS X.
> chore: fix `electron-sign-app-darwin.sh` reference

- Makefile
`$(error ...)` (and `$(warning ...)`) functions in a Makefile can't be indented - if they are make displays a `*** commands commence before first target. Stop.` error.
> chore: fix error functions in Makefile

- scripts/build/check-dependency.sh
- scripts/build/download-tool.sh
It was much easier to just use `"$@"` directly (which is only used in one place anyway), than it was to try and copy the `"$@"` array to a differently-named array variable.
> chore: fix `check-dependency.sh` to work with arguments containing spaces

- Makefile
- appveyor.yml
This will allow us to later publish development builds for both
architectures from Appveyor. In order to easily do so, the Makefile is
used instead of the current `./scripts/build/windows.bat`.
> chore: run tests in x64 and x86 in Appveyor

- Makefile
This new target also deletes the `node_modules` and `bower_components`
directories, taking the project directory to a totally pristine state.
> chore: add `distclean` target to Makefile

- Makefile
They're unnecessary, and actually cause the backslash to get printed.
> chore: remove backslash-escaping in Makefile errors & warnings

- scripts/build/download-tool.sh
This avoids the failure-mode where wget got interrupted (e.g. network error
or server timeout), which caused the download-tool.sh to stop, which caused
the current make to stop. However if you then ran make again, it would see
that the file existed (and not know that it was incomplete / corrupt) and so
not try downloading it again. This commit fixes the problem by modifying
download-tool.sh to download to a temporary filename, and only rename to the
final destination filename after the checksum has been verified.
> chore: download files to a temporary filename first, then rename

- Makefile
- docs/RUNNING-LOCALLY.md
- scripts/build/electron-create-appdir.sh
- scripts/build/electron-create-appimage-linux.sh
- scripts/build/electron-installer-appimage-zip.sh
Currently, `electron-installer-appimage.sh` deletes temporary stuff it
needs as it goes (like the AppDir, AppImageAssistant, or even the
AppImage after creating a ZIP). Since this is not very Make-friendly,
the script has been split into the following smaller scripts that
perform a single task:
- `electron-create-appimage-linux.sh`
- `electron-create-appdir.sh`
Utilising them in different Makefile rules effectively results in Make
persisting the "temporary artifacts".
See: https://github.com/resin-io/etcher/pull/913#discussion_r90801230
> chore: persist temporary artifacts during AppImage builds

- Makefile
- package.json
- scripts/build/electron-configure-package-win32.sh
This script configures an Electron package on Windows.
> chore: implement `electron-configure-package-win32.sh`

- docs/CONTRIBUTING.md
Because of NPM shrinkwrap, we recommend having a clean dependency tree
in `CONTRIBUTING.md` before upgrading a dependency. We currently
recommend maually wiping out `node_modules`, but since the
`electron-develop` make target already does that, is more user friendly
to recommend that instead.
> doc: recommend `make electron-develop` to clean dependency tree

- docs/RUNNING-LOCALLY.md
Asar is needed by all the `electron-installer-*` targets
> doc: Move the asar requirement from "Windows" to "Common"

- lib/gui/components/drive-selector/templates/drive-selector-modal.tpl.html
- lib/gui/models/selection-state.js
- tests/gui/models/selection-state.spec.js
System drives in the drive-list widget now have a red warning label
beneath. Also new is the `isSystemDrive()` method under
`SelectionStateModel` and its unit-tests.
See: https://github.com/resin-io/etcher/issues/888
Changelog-Entry: Label system drives in the drive-list widget
> feat(gui): label system drives in drive-list widget

- lib/gui/components/update-notifier/templates/update-notifier-modal.tpl.html
- lib/gui/index.html
We add referers to the two etcher.io links in the interface—one for the
update link, and one for the footer logo link.
Closes: https://github.com/resin-io/etcher/issues/987
Changelog-Entry: Add referers to the etcher.io links
> feat(gui): add referers to etcher.io links

- lib/gui/os/dialog/services/dialog.js
We sort the supported file extensions listed in the file picker
in alphabetical order.
See: https://github.com/resin-io/etcher/issues/984
Changelog-Entry: Sort supported extensions alphabetically in the
file-picker.
> feat(gui): sort file picker extensions alphabetically

- appveyor.yml
Running `npm install -g npm` causes npm to be upgraded to v4, which
seems to have the following bug when running `npm install`:
```
npm ERR! Callback called more than once.
```
Not upgrading npm on our Appveyor builds causes npm to stay at v3, and
the problem dissapears.
> chore: don't upgrade npm to latest on Appveyor

- lib/src/child-writer/writer-proxy.js
The GUI executes the CLI and pipes every line of output coming from
either `stdout` or `stderr` to the IPC server as "messages."
In some scenarios, the child process data handler might receive multiple
lines of output at the same time. Since the CLI outputs stringified JSON
objects each in a different line, trying to parse two JSON objects
separated by a new line causes the parser to crash.
As a solution, we split the data coming in by new lines (`\r\n` in
Windows), and emit a message for only the last one.
Fixes: https://github.com/resin-io/etcher/issues/898
Changelog-Entry: Fix "Invalid message" error caused by the IPC client emitting multiple JSON objects as a single message.
> fix(GUI): multiple JSON objects coming up at once from the IPC client

- lib/cli/writer.js
- npm-shrinkwrap.json
- package.json
This version includes support for retrying up to ten times when EIO
errors are encountered during reading.
See: https://github.com/resin-io-modules/etcher-image-write/pull/70
Fixes: https://github.com/resin-io/etcher/issues/981
Changelog-Entry: Fix sporadic "EIO: i/o error, read" errors during validation.
> upgrade: `etcher-image-write` to v9.0.0

- .travis.yml
- Makefile
This change makes Travis CI spawn 3 jobs:
- GNU/Linux with TARGET_ARCH=x64
- GNU/Linux with TARGET_ARCH=x86
- macOS with TARGET_ARCH=x64
We add `make info` before starting the build for convenience.
> chore: build x64 and x86 jobs for GNU/Linux

- npm-shrinkwrap.json
- package.json
- https://github.com/resin-io-modules/drivelist/pull/129
Changelog-Entry: Fix system drives detected as removable drives on Mac Mini.
See: https://github.com/resin-io/etcher/issues/983
> upgrade: `drivelist` to v5.0.5

- lib/shared/child-writer/utils.js
- lib/shared/child-writer/writer-proxy.js
- tests/shared/child-writer/utils.spec.js
We've recently PRed a commit that handles multiple IPC messages being
triggered at the same time, confusing `JSON.parse()`. As a solution to
such problem, we are splitting the CLI output on new lines, based on the
assumption that each line represents a different object, however we
didn't consider that in the case of errors, we include an `stacktrace`
property which usually includes new line characters, causing such
information to be completely garbled and cause `JSON.parse()` once again
to get confused.
As a solution, we only split by new lines that are not surrounded by
quotes (since they represent a JSON property).
See: https://github.com/resin-io/etcher/pull/997
> fix(GUI): don't split robot input by new lines inside properties

- lib/gui/css/main.css
- lib/gui/scss/main.scss
We've recently moved the compiled CSS output to `lib/gui/css/main.css`,
however we didn't update the relative path to Bootstrap icon web font,
causing every icon to break.
See: https://github.com/resin-io/etcher/pull/1002
> fix(GUI): fix path to Glyphicons Bootstrap font

- lib/gui/os/dialog/services/dialog.js
The image selection dialog is attached to the parent window so it is a modal.
> fix: make the image selection window a modal (#932)

- docs/ARCHITECTURE.md
- docs/CLI.md
- lib/cli/cli.js
- lib/cli/etcher.js
- lib/shared/child-writer/index.js
- lib/shared/child-writer/utils.js
- lib/shared/child-writer/writer-proxy.js
- lib/shared/robot.js
- tests/shared/robot.spec.js
The `--robot` option of the CLI causes the program to output
machine-parseable strings, which can be easily consumed by the GUI to
update progress and other information.
The problem is that if the CLI fails to parse its command line arguments
when being called from the GUI for whatever reason, the `.fail()` Yargs
handler will be called, which doesn't output error information in the
usual "robot" format, causing the GUI to not understand the error
message.
Since the `.fail()` Yargs handler doesn't have access to the passed
options, we moved the "robot" functionality to an environment variable,
which we can easily check from there.
As a bonus, this PR refactors the whole robot logic into
`lib/shared/robot.js` and adds unit tests to it.
See: https://github.com/resin-io/etcher/issues/986 …
> feat(CLI): replace `--robot` with an `ETCHER_CLI_ROBOT` env var

- package.json
The "min" mocha reporter clears the screen after each run, causing any
error/warning from the renderer process tests to be visually overwritten
by the main process tests.
Therefore, we now make use of the "spec" mocha reporter.
> chore: make use of the "spec" mocha reporter

- lib/gui/etcher.js
We were previously using the `undocked` mode, which would open DevTools
in a seaprate window, however the user was still allows to pick a new
mode, causing DevTools to be shown inside the main application and
completely ruining the UI.
The `detach` mode in the other hand, completely prevents user from
putting DevTools in the main application, therefore allowing no way to
make the UI look broken.
See: http://electron.atom.io/docs/api/web-contents/
> fix(GUI): open DevTools in `detach` mode

- npm-shrinkwrap.json
Somehow some development dependencies slipped into the shrinkwrap file,
and in some cases, dependencies we don't use anymore didn't remove its
own now unneeded dependencies when running `npm uninstall`.
This PR carefully removes the packages that are not needed anymore,
which are a lot.
See: https://github.com/resin-io/etcher/issues/820
> chore: remove unnecessary modules from `npm-shrinkwrap.json`

- npm-shrinkwrap.json
- package.json
- https://github.com/resin-io-modules/drivelist/issues/130
Changelog-Entry: Fix "This key is already associated with an element of this collection" error when multiple partitions point to the same drive letter on Windows.
Fixes: https://github.com/resin-io/etcher/issues/1004
> upgrade: `drivelist` to v5.0.6

- lib/cli/etcher.js
- lib/gui/app.js
- lib/gui/components/drive-selector/controllers/drive-selector.js
- lib/gui/pages/main/controllers/flash.js
- lib/gui/pages/main/controllers/image-selection.js
- lib/shared/messages.js
- tests/shared/messages.spec.js
There are certain application messages that should be re-used between
the CLI and the GUI. In order to allow such re-usability, we extract out
the application messages used in JavaScript into
`lib/shared/messages.js` as a collection of Lodash `_.template`
templates.
Notice this file doesn't include application messages included in
Angular templates directly since it'd be hard to refactor all of them.
We plan to move to React soon, which will allow moving the remaining
messages very easily.
> refactor: extract application messages to `lib/shared/messages.js`

- lib/gui/models/flash-state.js
- lib/shared/units.js
- tests/gui/utils/byte-size.spec.js
- tests/shared/units.spec.js
This commit extracts the byte-related conversions from the `byte-size`
AngularJS module and the `FlashStateModel` to a re-usable generic
CommonJS module at `lib/shared/units.js`, than can also be used by the
CLI.
> refactor: move all byte-size conversion logic to lib/shared/units.js 

- lib/gui/components/modal/styles/_modal.scss
- lib/gui/css/main.css
The `.modal-menu` class holds buttons that are shown at the bottom of
the modal. If there are two buttons, the class will show them side by
side with equal sizes, however if there is only one button, it will be
incorrectly resized to 50% of the available space.
Changelog-Entry: Fix alignment of single call to action buttons inside modals.
> fix(GUI): expand button in modal menu if its the only one

- .travis.yml
- scripts/build/docker/Dockerfile-i686
- scripts/build/docker/Dockerfile-x86_64
- scripts/build/docker/Dockerfile.template
- scripts/build/docker/README.md
- scripts/build/docker/compile-template.js
- scripts/build/docker/run-command.sh
This commit makes Travis CI run GNU/Linux tests inside Ubuntu 14.04
i386/x86_64 docker containers.
It includes a set of Dockerfiles with everything needed to
run/build/package Etcher while a nice `run-command.sh` script that can
be used to easily run a command on such Dockerfiles with access to the
Etcher source code.
The main motivation behind change is that generating cross-architecture
AppImages is not possible at the moment (although there are PRs on the
way), so this permits us to configure Travis CI to build and publish
AppImages for all architectures.
> chore: run Travis CI GNU/Linux tests in Docker containers 

- lib/shared/drive-constraints.js
- tests/shared/drive-constraints.spec.js
Currently the `DriveConstraintsModel` errors when given an `undefined`
drive, or image; this commit changes that behaviour. Comes with tests.
Changelog-Entry: Don't throw errors when drives and/or images are undefined in
the DriveConstraintsModel.
> fix: allow undefined drives and images in DriveConstraintsModel

- lib/shared/child-writer/writer-proxy.js
We recently sent a PR to handle multiple buffered IPC messages being
reported as a single message, confusing `JSON.parse()` in
`lib/shared/child-writer/index.js`, by only sending the last message,
and ignoring the rest, under the assumption that the loss of some state
messages is not critical for the application and the writing process to
work property.
As @lurch pointed out, however, a buffer set of messages might contain
an error object somewhere, and by ignoring all but the last message, we
ignore any error that happened in the way.
See: https://github.com/resin-io/etcher/issues/898
> fix(GUI): don't ignore any `robot` message from the CLI

- lib/gui/css/main.css
- lib/gui/scss/modules/_bootstrap.scss
Instead of letting Bootstrap tooltip text overflow, allow breaks to occur in
words.
Closes: https://github.com/resin-io/etcher/issues/1032
Changelog-Entry: Fix overflowing tooltip text by allowing breaks in words.
> fix(gui): break and wrap bootstrap overflowing tooltip text

- Makefile
We have a big comment block in the `electron-develop` target which gets
printed everytime the target gets executed.
After some research, turns out GNU Make will ignore the comments if they
are not indented.
See: http://stackoverflow.com/a/18363477/1641422
> chore: don't print Makefile comments

- lib/gui/components/flash-error-modal/templates/flash-error-modal.tpl.html
- lib/shared/messages.js
The current validation message is obscure and tends to lead users to
believe there is a problem with Etcher.
Fixes: https://github.com/resin-io/etcher/issues/735
Changelog-Entry: Improve validation error message.
> fix(GUI): improve validation error message

- lib/gui/pages/main/controllers/flash.js
There exists a change the user will run out of space on his drive when
flashing an image format for which we can't guarantee its uncompressed
size (e.g: gzip and bzip2).
When that happens, we show a friendly error message explaining what
happened, however we should also be emitting an analytics event.
Changelog-Entry: Emit an analytics event on `ENOSPC`.
> fix(GUI): emit an analytics event on ENOSPC

- lib/cli/writer.js
- lib/gui/os/dialog/services/dialog.js
- lib/image-stream/archive.js
- lib/image-stream/handlers.js
- lib/image-stream/index.js
- npm-shrinkwrap.json
- package.json
- tests/image-stream/bz2.spec.js
- tests/image-stream/gz.spec.js
- tests/image-stream/img.spec.js
- tests/image-stream/tester.js
- tests/image-stream/xz.spec.js
- tests/image-stream/zip.spec.js
The `image-stream` module currently returns a readable stream, a
transform stream, a "size", and an optional "estimatedUncompressedSize".
Based on this information, its hard to say what "size" represents. Some
format handlers return the compressed size and provide a decompression
transform stream while others return the decompressed stream directly
and put the decompressed size in "size".
As a way to simplify this, every format handler now returns a "size"
object with the following properties:
- `original`: The original compressed size
- `final.estimated`: Whether the final size is an estimation or not
- `final.value`: The final uncompressed size
As a bonus, we extract the file size retrieval logic to
`imageStream.getFromFilePath()`, which is the onlt part where the
concept of a file …
> refactor(image-stream): stream original/final sizes

- npm-shrinkwrap.json
- package.json
Changelog-Entry: Fix 'MySQL' is not recognised as an internal or external command error on Windows.
See: https://github.com/resin-io-modules/drivelist/issues/133
Fixes: https://github.com/resin-io/etcher/issues/1025
> upgrade: `drivelist` to v5.0.8

- tests/gui/models/drives.spec.js
We have a test to ensure a drive is not auto-selected when its
protected, however the real functionality of this test was not being
tested given that the size the fake drive had was not enough to hold the
image.
> test(GUI): fix non-running test in DrivesModel test suite

- lib/gui/components/drive-selector/templates/drive-selector-modal.tpl.html
- lib/gui/models/store.js
- lib/shared/drive-constraints.js
- npm-shrinkwrap.json
- package.json
- tests/gui/models/drives.spec.js
- tests/gui/models/selection-state.spec.js
- tests/shared/drive-constraints.spec.js
Currently Etcher will allow you to flash an image to the same drive that
contains the image. As a way to protect against that case we introduce
the concept of a "source drive", which means a drive that contains the
source image.
This commit adds the following logic around this new concept:
- Don't auto-select a source drive
- De-select an already selected drive if an image inside it is selected
- Disable the drive in the drive selector modal
- Add a "Source Drive" badge to the drive in the drive selector modal
Fixes: https://github.com/resin-io/etcher/issues/830
Changelog-Entry: Prevent flashing the drive where the source image is located.
> fix(GUI): prevent flashing the drive where the source image is located

- lib/gui/index.html
- npm-shrinkwrap.json
- package.json
This version doesn't throw an error if there is `stderr` output from the
scripts but the scripts exit with code zero.
Instead, the module prints the `stderr` output to a `debug` channel, so
we enable debug information by setting a `localStorage` value in order
to see what's going on.
Fixes: https://github.com/resin-io/etcher/issues/1034
Changelog-Entry: Ignore `stderr` output from drive detection scripts if they exit with code zero.
> upgrade: `drivelist` to v5.0.9

- lib/gui/components/progress-button/styles/_progress-button.scss
- lib/gui/css/main.css
- lib/gui/index.html
- lib/gui/pages/main/styles/_main.scss
- lib/gui/pages/main/templates/main.tpl.html
- lib/gui/scss/modules/_space.scss
- lib/gui/scss/modules/_theme.scss
We match the main page design to its updated style.
* Remove help icon text.
* 'Change' image/drive buttons are now violet blue.
* Remove step number icons and accompanying descriptions.
* Flash progress button now turns into a striking orange, from blue.
Changelog-Entry: Minor design improvements to the main page.
> feat(gui): update main page design

- README.md
- docs/CONTRIBUTING.md
- package.json
No one on the team is using this and the adaptor we're using proved to
be suboptimal. We might consider this again once we develop a good
Commitizen adapter integrated more closely with Versionist.
> chore: get rid of commitizen

- lib/gui/models/store.js
- tests/gui/models/drives.spec.js
Currently Etcher will auto-select a system drive if its the only
available one when the "unsafe mode" is enabled, which doesn't feel
right.
Changelog-Entry: Don't auto select system drives in unsafe mode.
See: https://github.com/resin-io/etcher/pull/1061
> fix(GUI): don't auto select system drives in unsafe mode

- lib/gui/modules/error.js
- lib/gui/pages/main/controllers/main.js
- lib/gui/pages/main/main.js
- lib/gui/pages/main/templates/main.tpl.html
- npm-shrinkwrap.json
- package.json
- tests/gui/modules/image-writer.spec.js
Angular 1.5 has a bug that causes angular's `$exceptionHandler`
to be called for rejected `$q` promises even if they have
a rejection handler. This bug caused duplicate error messages
in Etcher.
A consequence of upgrading to Angular 1.6 is that `$q` promises
without a rejection handler will throw `Possibly unhandled rejection`
errors. To avoid these errors, this commit moves code responsible
for opening a tooltip from the template to the controller and handles
the rejection.
Other packages upgraded:
- angular-moment to v1.0.1
- angular-ui-router to v0.4.2
- angular-mocks to v1.6.1
Changelog-Entry: Fix duplicate error messages
Fixes: https://github.com/resin-io/etcher/issues/1082
See: https://github.com/angular/angular.js/issues/7992
See: …
> upgrade: angular to v1.6.1; angular-ui-bootstrap to v2.5.0

- lib/gui/app.js
- lib/gui/os/dialog/services/dialog.js
- lib/shared/messages.js
For better OS integration purposes.
This commit also fixes a bug where the dialog would be shown for some
milliseconds even if the application is not flashing.
Changelog-Entry: Use a OS dialog to show the "exit while flashing" warning.
> style(GUI): use a OS dialog to show the "exit while flashing" warning

- lib/gui/components/update-notifier/styles/_update-notifier.scss
- lib/gui/components/update-notifier/templates/update-notifier-modal.tpl.html
- lib/gui/css/main.css
This is a small step towards unifying all the modal skeletons that we
use through the application.
By moving the checkbox to the modal body we can declare the footer and
the header once in a single place.
> style(GUI): move update notifier checkbox inside modal body

- docs/COMMIT-GUIDELINES.md
See: https://github.com/resin-io/etcher/pull/1084
> docs: clarify that a "style" commit type applies to code annotations

- docs/RUNNING-LOCALLY.md
We need this dependency to create ZIP packages on Windows.
> docs: add msys-zip as a required Windows dependency

- lib/gui/css/main.css
- lib/gui/pages/main/controllers/main.js
- lib/gui/pages/main/styles/_main.scss
- lib/gui/pages/main/templates/main.tpl.html
- tests/gui/pages/main.spec.js
We revert the drive and image selection step order swap back from drive
selection first and image second, to image first and drive second.
See: https://github.com/resin-io/etcher/pull/1049
Changelog-Entry: Revert the drive/image selection step order swap.
> refactor(gui): revert drive/image selection step order swap

- lib/gui/pages/finish/templates/success.tpl.html
- package.json
- scripts/html-lint.js
This PR creates a script at `scripts/html-lint.js` that runs a NodeJS
HTML linter package that understands AngularJS on top of all our HTML
templates.
The following error was detected and fixed:
```
1 errors at lib/gui/pages/finish/templates/success.tpl.html
[4:63] Duplicate attribute “class”.
```
This script will run as part of `npm run lint`, but you can call it
independently as `npm run htmllint`.
> chore: add an HTML linter and fix its warnings

- lib/gui/components/drive-selector/styles/_drive-selector.scss
- lib/gui/components/drive-selector/templates/drive-selector-modal.tpl.html
- lib/gui/css/main.css
The rules inside this class should be moved to
`.modal-drive-selector-modal`.
> refactor(GUI): remove component-drive-selector-body outdated class

- npm-shrinkwrap.json
- package.json
This version contains a fix to omit drive letters assigned to partitions
without a valid file system (read "valid for Windows"), causing our
unmounting routine to fail in these cases.
Changelog-Entry: Fix "Error: Command Failed" error when unmounting on Windows.
Fixes: https://github.com/resin-io/etcher/issues/1019
> upgrade: `drivelist` to v5.0.10

- npm-shrinkwrap.json
Looks like this dependency was not updated correctly on the shrinkwrap
file. Probably happened in the linked pull request, where the shrinkwrap
file was hand edited at some point (see PR discussion).
See: https://github.com/resin-io/etcher/pull/1083
> chore: update `angular-ui-router` in `npm-shrinkwrap.json`

- npm-shrinkwrap.json
- package.json
Changelog-Entry: Omit empty SD Card readers in the drive selector on Windows.
> upgrade: `drivelist` to v5.0.11

- docs/RUNNING-LOCALLY.md
Its not possible to build Etcher without it. For some reason, the Visual
Studio Community 2015 installer is not ticking it by default anymore..
See: https://github.com/resin-io/etcher/pull/1110
> docs: C++ are not auto-selected by Visual Studio anymore 

- npm-shrinkwrap.json
- package.json
This version fixes an `EACCES` issue when spawning the platform scripts
in OS X and GNU/Linux, which caused because previous versions were
published to NPM from Windows, and Windows seems to mess up the file
permissions (the execution bit in this particular case).
I'm not adding a changelog entry given this issue happen on `master` and
didn't affect any release.
> upgrade: `drivelist` to v5.0.13

- .travis.yml
The `electron-installer-debian` is not needed for OS X builds. On top of
that, it seems that we're installing it twice.
> chore: don't install `electron-installer-debian` in OS X builds

- lib/gui/components/update-notifier/services/update-notifier.js
Etcher checks what is the latest version by making an HTTP request to S3
in order to see if it should present the update notifier modal at
startup.
If the user is not connected to the internet, or is on an unstable
connection, the request might fail completely or timeout, leading to a
weird error message being presented to the user:
```json
{
"data": null,
"status": -1,
"config": {
"method": "GET",
"transformRequest": [null],
"transformResponse": [null],
"url": "https://resin-production-downloads.s3.amazonaws.com",
"headers": {
"Accept": "application/json, text/plain, */*"
}
},
"statusText": ""
}
```
To solve the error, we tweak `UpdateNotifierService.getLatestVersion()`
to resolve the current version if there was a problem making the request
(e.g: the response didn't come through at …
> fix(GUI): update notifier transformRequest error at startup

- .travis.yml
- appveyor.yml
- scripts/ci/ensure-staged-sass.sh
We recently encountered a UI regression caused by forgetting to commit
the generated CSS files.
The solution is to make the CI servers run `npm run sass` and check if
there are unstaged files afterwards. If so, the tests halt.
In order to avoid duplication between Travis CI and Appveyor CI, this
logic has been encoded into a bash script at `scripts/ci`.
See: https://github.com/resin-io/etcher/pull/1120
> chore: ensure `npm run sass` was ran and the results committed

- dictionary
- package.json
codespell works by having a dictionary of pairs of malformed words and
their correct equivalents. This means that codespell will not catch most
issues out of the box, but we can train it based on the common spelling
issues we encounter along the way.
The plan is to add a pair to `dictionary` every time we encounter a typo
during a code review, and we ensure that error will not happen again
anymore.
See: https://github.com/resin-io/etcher/pull/1084
> chore: start codespell dictionary file in the root of the project

- npm-shrinkwrap.json
- package.json
See: https://github.com/resin-io-modules/drivelist/pull/146
Changelog-Entry: Don't ignore errors coming from the Windows drive detection script.
> upgrade: `drivelist` to v5.0.14

- Makefile
- scripts/build/electron-sign-exe-win32.sh
- Add missing backslash that caused the command to not be interpreted
completely
- Update `electron-sign-exe.exe` to `electron-sign-exe-win32.exe` in
Makefile
- Use hyphen options instead of Windows slash style, which confuses bash
> chore: fix various code-signing Windows issues

- scripts/build/dependencies-bower.sh
- scripts/build/dependencies-npm.sh
Cygwin can't resolve them correctly, causing cryptic errors during
build.
> chore: don't use symbolic links on Windows builds

- Makefile
We use that variable in the Makefile but we're not defining it, which
means that maintainers publishing Etcher need to remember to pass that
as an option.
> chore: define `S3_BUCKET` in Makefile

- scripts/publish/aws-s3.sh
- scripts/publish/bintray-debian.sh
Not including the colon means that the option parsing mechanism is not
expecting an argument for the `-t` and the `-p` option (for
`bintray-debian.sh` and `aws-s3.sh` respectively), and thus `$OPTARG`
will be undefined.
> chore: add missing `:` after options in publish scripts 

- lib/gui/app.js
- lib/gui/components/drive-selector/templates/drive-selector-modal.tpl.html
- lib/gui/pages/main/templates/main.tpl.html
We change the drive selector button text to be a static 'select drive'
and allow the user to open the dialog even if there are no drives,
displaying the 'no drives' warning inside the modal.
Closes: https://github.com/resin-io/etcher/issues/884
Changelog-Entry: Allow opening of drive selector modal when there are no
drives.
> feat(GUI): allow opening drive selector modal when no drives

- lib/child-writer/writer-proxy.js
I couldn't find an ESLint rule that would protect us from this in the
future.
See: https://github.com/resin-io/etcher/pull/1148#discussion_r103525165
> style(GUI): fix small chain indentation issue

- lib/cli/options.js
- lib/cli/unmount.js
- lib/gui/components/drive-selector/controllers/drive-selector.js
- lib/gui/components/tooltip-modal/controllers/tooltip-modal.js
- lib/gui/components/update-notifier/controllers/update-notifier.js
- lib/gui/components/warning-modal/controllers/warning-modal.js
- lib/gui/models/store.js
- lib/gui/os/dialog/dialog.js
- lib/gui/os/notification/notification.js
- lib/gui/os/window-progress/services/window-progress.js
- lib/gui/os/window-progress/window-progress.js
- lib/gui/pages/finish/controllers/finish.js
- lib/gui/pages/finish/finish.js
- lib/gui/pages/main/main.js
- lib/gui/pages/settings/controllers/settings.js
- lib/gui/utils/byte-size/byte-size.js
- lib/gui/utils/manifest-bind/manifest-bind.js
- lib/gui/utils/path/path.js
- The type in `@type` should be surrounded by curly braces
- We should use `@type` in some cases where we used `@property`
- `@module` descriptions should go above such tag
- Namespaces should not declare their access type
> chore: fix JSDoc warnings

- lib/gui/modules/analytics.js
- lib/image-stream/archive.js
- tests/gui/modules/analytics.spec.js
These errors happen when the user selects an archive that contains no
image, or multiple images, and represents a user error, rather than an
unhandled exception.
For this reason, we should not report this to TrackJS.
This means, however, that we need a reliable way to know whether an
error should be reporter or not. This commit implements
`AnalyticsService.shouldReportError()` for this purpose, which will
check an optional `report` property of the error object.
In order to ensure that errors that we don't control are reported, the
function will return `true` if the error object doesn't have that
property.
Changelog-Entry: Don't report "invalid archive" errors to TrackJS.
Fixes: https://github.com/resin-io/etcher/issues/1103
Signed-off-by: Juan Cruz Viotti …
> fix(GUI): don't report "invalid archive" errors to TrackJS

- npm-shrinkwrap.json
- package.json
We're mainly interested in the following change:
- https://github.com/resin-io-modules/drivelist/pull/148
Fixes: https://github.com/resin-io/etcher/issues/1126
Changelog-Entry: Fix errors when unplugging drives exactly when the drive scanning scripts are running.
> upgrade `drivelist` to v5.0.15

- npm-shrinkwrap.json
- package.json
We're particularly interested in:
- https://github.com/resin-io-modules/etcher-image-write/pull/84
Which fixes ENOSPC alignment issues.
This new version upgrades all its dependencies, which is the reason why
`npm-shrinkwrap.json` contains a lot of changes.
Fixes: https://github.com/resin-io/etcher/issues/1109
Changelog-Entry: Fix `ENOSPC` image alignment errors.
> upgrade: `etcher-image-write` to v9.0.1

- npm-shrinkwrap.json
- package.json
See: https://github.com/resin-io-modules/drivelist/pull/150
Fixes: https://github.com/resin-io/etcher/issues/1159
Changelog-Entry: Fix GNU/Linux udev error when `net.ifnames` is set.
> upgrade: `drivelist` to v5.0.16

- npm-shrinkwrap.json
- package.json
We recently started hitting the following errors in all our CI builds:
```
TypeError: angular.module(...).info is not a function
at /etcher/node_modules/angular-mocks/angular-mock
```
The `.info()` function was released in AngularJS 1.6.3. We declare
`angular-mocks@^1.6.1` as a development dependency, which means that
once 1.6.3 was out, npm started resolving `angular-mocks@1.6.3`, however
that version is incompatible with the main Angular version we're
shrinkwrapping (1.6.1), and thus the error.
As a solution, I've upgraded both `angular` and `angular-mocks` to
1.6.3, but also locked down `angular-mocks`, since similar errors will
happen again unless we manually keep these versions in sync.
> upgrade: `angular` and `angular-mocks` to v1.6.3

- lib/gui/app.js
If the drive scanning scripts cause an error, the error will be
presented to the user over and over again. Not only this is terrible UX,
which even makes hard to close the application since dialogs keep coming
in, but it also spams TrackJS, our error reporting service, and makes it
seem that errors happened dozens of times, and thus obscuring real
trending errors.
Changelog-Entry: Stop drive scanning loop if an error occurs.
> fix(GUI): stop drive scanning loop if an error occurs

- scripts/build/docker/run-command.sh
This speeds up the 'docker build' step, as it reduces the amount of 'build
context' that needs to be sent to docker.
Unfortunately we can't append `.git` (a 53MB directory) to the end of `.dockerignore`, because it's needed by the `ensure-staged-sass.sh` script ;-)
> chore: create a temporary .dockerignore during the docker build step

- Makefile
- scripts/build/architecture-convert.sh
- scripts/build/dependencies-npm.sh
- scripts/build/electron-download-package.sh
- scripts/build/electron-installer-debian-linux.sh
- scripts/publish/bintray-debian.sh
This is the architecture of the Raspberry Pi 3. The following changes
were necessary:
- Detect the architecture using `uname -m`
- Set the Debian equivalent architecture to `armhf`
- Handle the new architecture correctly on `dependencies-npm.sh` and
`electron-download-package.sh`, referring to it as simply `arm` (which
is what `node-gyp` expects)
Steps to test this PR:
- `make electron-installer-debian` from a Raspberry Pi 3
This PR also includes `architecture-convert.sh`, which is a script to
find an architecture equivalence for Node and Debian.
> chore: support generating armv7l .deb packages

- lib/gui/index.html
I've noticed that errors reported to TrackJS appear twice. Turns out
that TrackJS pipes output of `console.error()` as errors, rather than as
extra logging.
The `AnalyticsService.logException()` function reports the exception to
TrackJS using `$window.trackJS.track()`, but then prints it to `stderr`
as well (so it appears on DevTools), causing TrackJS to report that one
too.
The solution is to disable the `console.error` boolean property of the
`_trackJs` object. From the TrackJS documentation:
```
// By default any calls to console.error() will automatically trigger an
// error. Set this to false if you don't want console.error() to
// trigger errors.
error: true,
```
See: http://docs.trackjs.com/tracker/configuration
> fix(GUI): avoid duplicated TrackJS errors

- lib/gui/modules/analytics.js
- lib/shared/utils.js
- npm-shrinkwrap.json
- package.json
- tests/shared/utils.spec.js
The image path contains user information that should not be logged
in Mixpanel. Instead, just log the image filename.
Changelog-Entry: Don't include user paths in usage reports
> feat(GUI): don't log absolute paths in Mixpanel

- .travis.yml
- Makefile
- appveyor.yml
- package.json
- scripts/ci/ensure-npm-dependencies-compatibility.sh
We've recently had an incident were the `angular-mocks` version we were
running was incompatible with the `angular` version.
Each AngularJS core module is versioned equally, therefore we can write
a small scripts that automatically test that they match, so we're
guarded against forgetting to similarly upgrade different dependencies.
See: https://github.com/resin-io/etcher/pull/1168
> chore: automatically enforce compatible angular core module versions

- Makefile
- docs/CONTRIBUTING.md
- npm-shrinkwrap.json
- scripts/build/dependencies-npm.sh
- scripts/ci/ensure-npm-shrinkwrap-versions.sh
- scripts/clean-shrinkwrap.js
We've been recently hitting a weird `lzma-native` build error on Windows
(both locally and on Appveyor CI):
```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
build
The input line is too long.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\projects\etcher\node_modules\lzma-native\build\liblzma.vcxproj]
```
After a lot of experimentation, we realised the issue was gone if we
removed `node-sass` from the development dependencies.
The issue is that `node-gyp` was recently upgraded to v3.6.0, which was
picked up by `node-sass`, which declares `node-gyp` as a dependency. For
some reason, if `node-sass` causes `node-gyp` to be updated, then …
> chore: fix `lzma-native` build issues on Windows

- docs/RUNNING-LOCALLY.md
Add Visual C++ 2015 Build Tools as a lighter option to a full blown Visual Studio installation for development requirements on Windows.
> doc: Add MSVC Build Tools option to Windows requisites

- lib/gui/pages/main/templates/main.tpl.html
We show the friendly drive name on the main page with the drive's device name
or mount point now inside a tooltip. Drive names longer than 11 characters are
truncated with a middle ellipsis.
Changelog-Entry: Show friendly drive name instead of device name.
Closes: https://github.com/resin-io/etcher/issues/1170
> feat(GUI): show drive name instead of device name

- appveyor.yml
- docs/RUNNING-LOCALLY.md
- scripts/build/docker/Dockerfile-i686
- scripts/build/docker/Dockerfile-x86_64
- scripts/build/docker/Dockerfile.template
- scripts/build/electron-configure-package-win32.sh
- scripts/build/electron-create-appdir.sh
upx allows to reduce the package size by some mega bytes, but also
considerably slows down the application start time.
This commit ditches upx, since we can re-gain those benefits (and even
increase them) by other means (e.g: minifying JavaScript).
See: https://github.com/resin-io/etcher/issues/1138
> chore: don't compress binaries/libraries with upx
