balena-io/etcher

npm-shrinkwrap.json
package.json

We believe this issue fixes the "rawr i'm a dinosaur" error on certain
problematic images.
Gives this only happens on a minority of images, we couldn't confirm
that the fix really solves the issue, but we'll include the upgrade on
the next Etcher version and see how it goes in the real world.
Changelog-Entry: Fix "rawr i'm a dinosaur" bzip2 error.
Fixes: https://github.com/resin-io/etcher/issues/734

upgrade: `unbzip2-stream` to v1.0.11

---

.gitattributes
Makefile
appveyor.yml
scripts/ci/ensure-all-file-extensions-in-gitattributes.sh

This allows `npm run lint` to pass regardless of the `core.autocrlf` setting in git
See https://help.github.com/articles/dealing-with-line-endings/ and http://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/ for more info.
The CSS and SCSS needs to always be LF, because `node-sass` outputs a horrid mix of CRLF and LF (which confuses `git status`) if any of the input files contain CRLF.

chore: setup .gitattributes to perform correct line-ending conversions

---

.travis.yml
appveyor.yml
docs/RUNNING-LOCALLY.md

This commit addresses some issues with snapshot builds that we didn't
caught given we never ran the deployment step in a "real" deployment
scenario.
- On Travis CI, the service reverts all changes in the source tree
before starting the `deploy` section, which seems to trigger some
issues when deleting `node_modules`. The solution is to set the
`skip_cleanup` option
See
https://s3.amazonaws.com/archive.travis-ci.org/jobs/213614487/log.txt
```
...
warning: failed to remove node_modules/helper-date/node_modules/moment/locale/es.js
warning: failed to remove node_modules/helper-date/node_modules/moment/locale/ky.js
warning: failed to remove node_modules/helper-date/node_modules/moment/locale/pt-br.js
warning: failed to remove node_modules/helper-date/node_modules/moment/locale/hu.js
warning: …
```

chore: fix errors during snapshot deployments

---

docs/PUBLISHING.md

- Mention the production and snapshot S3 bucket
- Remove the note that `aws-s3.sh` doesn't run on Windows
- Don't document `./scripts/publish/aws-s3.sh`. Encourage maintainers to
use `make publish-aws-s3` instead
See: https://github.com/resin-io/etcher/pull/1078#discussion_r107259159

docs: revise PUBLISHING.md S3 section

---

scripts/build/docker/Dockerfile-i686
scripts/build/docker/Dockerfile-x86_64
scripts/build/docker/Dockerfile.template

`pip install awscli` outputs the following warning:
```
Running setup.py install for PyYAML
checking if libyaml is compilable
i686-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/check_libyaml.c -o build/temp.linux-x86_64-2.7/check_libyaml.o
build/temp.linux-x86_64-2.7/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
#include <yaml.h>
^
compilation terminated.
libyaml is not found or a compiler error: forcing --without-libyaml
(if libyaml is installed correctly, you may need to
specify the option --include-dirs or uncomment and
modify the parameter include_dirs in setup.cfg)
```
The installation gracefully continues anyway (the `--without-libyaml` is …

chore: add `libyaml-dev` to GNU/Linux Docker dependencies

---

.travis.yml

You don't need to have the whole commit history of `nvm`, let's speed up the clone process.

Update .travis.yml to not clone entire nvm history

---

.travis.yml

This changes the `.travis.yml` to use the `node_js` language as a base instead of `cpp` to avoid installing & setting up node manually.

chore(travis): Use `node` base, instead of `cpp`

---

lib/image-stream/index.js

When fetching metadata, a stream is opened, but never consumed. This destroys the stream when retrieving metadata to avoid dangling open file descriptors and such.

fix(image-stream): Destroy unused image streams

---

docs/RUNNING-LOCALLY.md

This adds the option to install the Windows C++ Build Tools via npm to the RUNNING-LOCALLY docs.

doc: Add option to install win build tools via npm

---

Makefile
scripts/build/dependencies-npm.sh

As removing the `node_modules` completely and then re-installing is quite time consuming and SSD-thrashing, resort to pruning and rebuilding native add-ons when switching targets.

chore(scripts): Rebuild instead of removing `node_modules`

---

lib/gui/etcher.js

Users can currently force the browser window to reload by using Cmd+R in
macOS. The `will-navigate` even handler in this same file is supposed to
protect us from this case, however its not fired at all just in macOS
for some reason.
As a solution, we attach dummy keyboard shortcut handlers for Cmd+R,
Ctrl+R, and F5, to override the normal browser window behaviour.
The reason behind disallowing reloads is that a reload during a critical
operation such as writing, validation, elevating, unmounting, drive
scanning, etc will cause undefined behaviour, resulting in non sense
errors that we can't solve coming to TrackJS.
See: https://github.com/electron/electron/issues/8841
Fixes: https://github.com/resin-io/etcher/issues/1210

fix(GUI): disallow reloading the app in macOS using Cmd+R

---

lib/gui/etcher.js

This issue only affects GNU/Linux and macOS. If the user sends SIGINT to
the application, the main process dies, but we get an orphaned blank
browser window. The problem only seems to occur when there is a
`beforeunload` window event handlers, which we use to warn the user when
quitting while flashing.
Changelog-Entry: Prevent blank application when sending SIGINT on GNU/Linux and macOS.
Fixes: https://github.com/resin-io/etcher/issues/1028

fix(GUI): prevent blank application when sending SIGINT

---

package.json

In order to package the Etcher CLI, we concatenate all the code from the
`lib/cli/etcher.js` entry point using browserify.
There are some dependencies down the hierarchy that dynamically require
other dependencies, by enclosing `require()` calls in `try`/`catch`
blocks. The dynamic dependencies these modules require are not even
present in the `package.json`, and thus rightfully confuse browserify.
See https://github.com/ForbesLindesay/spawn-sync/blob/master/lib/spawn-sync.js#L10
See https://github.com/IndigoUnited/node-cross-spawn/blob/master/index.js#L32
There are two solutions to this problem:
- Make browserify stub these problematic dependencies with a blank file
by using `--ignore`
This approach initially looks like the way to go, however it means that
every module that requires this …

chore(package.json): add dynamic dependencies as optional dependencies

---

docs/CLI.md
lib/cli/utils.js
lib/shared/errors.js
tests/shared/errors.spec.js

Currently, the Etcher CLI will print scary stack traces for every single
error (e.g: if you forgot to pass an image to the tool), given that
`errors.getDescription()` will return a stack trace if no other
description could be found.
This commit introduces an `ETCHER_CLI_DEBUG` environment variable, which
when set, it will cause the Etcher CLI to output stack traces, plus a
boolean `userFriendlyDescriptionsOnly` option to
`errors.getDescription()`, so we can control whether
`errors.getDescription()` returns things like stack traces, or
stringified error objects.
Changelog-Entry: Don't print stack traces by default in the CLI.

fix(CLI): don't print stack traces by default

---

lib/cli/writer.js

The CLI sill happily let you flash an image that doesn't fit on the
drive. This commit prevents such scenario right before flashing, but we
should still implement a smarter CLI drive detection widget for when the
user runs the CLI interactively.
Changelog-Entry: Prevent flashing an image that is larger than the drive with the CLI.
Fixes: https://github.com/resin-io/etcher/issues/858

fix(CLI): prevent flashing an image that is larger than the drive

---

.gitattributes
.travis.yml
appveyor.yml
scripts/ci/deploy-appveyor.bat
scripts/ci/deploy-travis.sh

We're passing a shell conditional to `deploy.script`, however Travis CI
seems to get confused about this in the deploy section, causing
GNU/Linux to run `make publish-aws-s3` directly on the Travis CI build
instead of in the Docker container, which causes the deployment to
eventually fail because of missing dependencies.
According to Travis CI:
> `deploy.script` must be a scalar pointing to an executable file or
> command.
See https://travis-ci.org/resin-io/etcher/jobs/214723725 for a failure
example.
We also move the Appveyor deploy script to a separate file for symmetry
purposes.

chore(travis): move deploy command to a separate script

---

lib/gui/pages/main/templates/main.tpl.html

In the main page we show the drive description, and on hover a tooltip
shows the drive name. This behaviour is changed to show both in the
tooltip, un-truncatetd.
Closes: https://github.com/resin-io/etcher/issues/1170
Changelog-Entry: Display both drive name and description in the drive tooltip.

feat(GUI): display drive name and description in tooltip

---

README.md

We have inline instructions to install Etcher from package managers.
This commit extends them to quickly mention how to uninstall as well.
Fixes: https://github.com/resin-io/etcher/issues/1225

docs(README): uninstall instructions for debian/brew

---

npm-shrinkwrap.json
package.json

These are dynamic dependencies we've recently added to the list of top
level optional dependencies in order to be able to resolve them when
using browserify to package the Etcher CLI.
The issue is that `thread-sleep` is using a very old `node-pre-gyp`
version (0.6.9) that doesn't support Electron at all, thus resulting in
the following error when setting `npm_config_runtime=electron`:
```
node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack Error: Unknown Runtime: 'electron'
```
This commit makes these dependencies production dependencies, so we can
tweak the `node-pre-gyp` version to make it work.
See: https://github.com/resin-io/etcher/pull/1228
See: https://github.com/mapbox/node-pre-gyp/issues/281

chore: make `thread-sleep` and `spawn-sync` production dependencies

---

lib/image-stream/index.js
package.json

The dependency is not yet removed from `npm-shrinkwrap.json` given that
there another one that keeps requiring it.

refactor(image-stream): get rid of `isstream`

---

docs/CONTRIBUTING.md
package.json
scripts/clean-shrinkwrap.js

Previously dependencies weren't actually removed from `node_modules`,
this runs `npm rm` on the optional dependencies, effectively excluding
them, and their dependencies from the shrinkwrap file.
Also the script has been hooked to the `preshrinkwrap` hook,
to remove the need of having to run it manually.
**NOTE:** This depends on #1234 being merged first, to avoid mangling the `npm-shrinkwrap.json` several times.
Connects-To: #1234

chore(package): Make clean-shrinkwrap remove optional dependencies

---

lib/image-stream/index.js
lib/image-stream/utils.js
npm-shrinkwrap.json
package.json
tests/image-stream/utils.spec.js

We also took the opportunity to make `utils.getArchiveMimeType()`
asynchronous.

refactor(image-stream): get rid of read-chunk

---

lib/gui/components/progress-button/templates/progress-button.tpl.html

We limit the progress button width by limiting the progress to a maximum
value of 100.
Changelog-Entry: Limit button progress and width to 100.

fix(GUI): limit button progress and width to 100

---

lib/cli/writer.js
lib/gui/models/selection-state.js
lib/gui/models/store.js
lib/gui/os/dialog/services/dialog.js
lib/gui/os/dropzone/directives/dropzone.js
lib/gui/pages/main/controllers/image-selection.js
lib/gui/pages/main/templates/main.tpl.html
lib/image-stream/archive.js
lib/image-stream/handlers.js
lib/shared/drive-constraints.js
tests/gui/models/drives.spec.js
tests/gui/models/selection-state.spec.js
tests/gui/os/dropzone.spec.js
tests/gui/pages/main.spec.js
tests/image-stream/bz2.spec.js
tests/image-stream/gz.spec.js
tests/image-stream/img.spec.js
tests/image-stream/xz.spec.js
tests/image-stream/zip.spec.js
tests/shared/drive-constraints.spec.js

`image-stream` returns image objects that look like this:
```js
{
stream: <readable stream>,
transform: <transform stream>,
size: {
original: <number>,
final: {
value: <number>,
estimation: <boolean>
}
},
...
}
```
While the GUI handles image objects that look like this:
```sh
{
path: <string>,
size: <number>,
...
}
```
It looks like we should share a common structure between both, so we can
use `image-stream` images in `drive-constraints`, for example.
Turns out that we actually transform `image-stream` image objects to GUI
image objects when the user selects an image using the image selector
dialog, which is another indicator that we should normalise this
situation.
As a solution, this commit does the following:
- Add `path` to `image-stream` image object
- Reuse `image-stream` image …

refactor: unify image objects across GUI and image-stream

---

.travis.yml

See https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
We regularly have OSX builds failing with:
```
Makefile:125: No code-sign identity found (CODE_SIGN_IDENTITY is not set)
Application version : 1.0.0-beta.19+c817076
Release type        : snapshot
Host platform       : darwin
Host arch           : x64
Target platform     : darwin
Target arch         : x64
Makefile:125: No code-sign identity found (CODE_SIGN_IDENTITY is not set)
./scripts/build/dependencies-npm.sh \
-r "x64" \
-v "1.4.4" \
-t electron \
-s "darwin"
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: …
```

chore: Stop OSX builds on Travis frequently timing out

---

.travis.yml
appveyor.yml

This means that if any architecture build fails, then we stop the other
ones right away, for performance reasons.
See: atom/atom@ce51074
See: https://blog.travis-ci.com/2013-11-27-fast-finishing-builds/

chore: make the CI servers fail-fast if one of their builds fails

---

lib/child-writer/index.js
lib/shared/robot/README.md
lib/shared/robot/index.js

This adds a new command recognition for message type "log",
to enable `console.log()`ing arbitrary data to the parent process console.
Not sure if we'd really want this in, but it's very handy for debugging,
and would keep us from writing these 3 lines every time
we want to inspect something in between those processes.

feat(robot): Support logging arbitrary data to the console

---

lib/gui/components/update-notifier/controllers/update-notifier.js
lib/gui/components/update-notifier/services/update-notifier.js
lib/gui/components/update-notifier/update-notifier.js
lib/gui/models/settings.js
lib/gui/modules/analytics.js
lib/gui/modules/drive-scanner.js
lib/gui/modules/image-writer.js
lib/gui/pages/finish/controllers/finish.js
lib/gui/pages/finish/finish.js
lib/gui/pages/main/controllers/drive-selection.js
lib/gui/pages/main/controllers/flash.js
lib/gui/pages/main/controllers/main.js
lib/gui/pages/main/main.js
lib/gui/pages/settings/controllers/settings.js
lib/gui/pages/settings/settings.js
tests/gui/components/update-notifier.spec.js
tests/gui/models/settings.spec.js
tests/gui/pages/main.spec.js

We remove the usage of Angular in SettingsModel in our efforts to make
Etcher as agnostic as possible as we make our move to React.
Changelog-Entry: Remove Angular usage from SettingsModel

refactor(GUI): remove angular from SettingsModel

---

npm-shrinkwrap.json
package.json

This version contains a fix to make the module work fine on a
concatenated JavaScript file.
See: https://github.com/resin-io-modules/mountutils/pull/23

upgrade: `mountutils` to v1.0.3

---

lib/child-writer/writer-proxy.js
lib/cli/etcher.js
lib/shared/permissions.js
npm-shrinkwrap.json
package.json

This commit implements our own version of the `is-elevated` module. The
reason behind this is that `is-elevated` relies on lots of unnecessary
modules, that eventually require `spawn-sync` and `try-thread-sleep`,
which conditionally require dependencies that are not even declared in
their `package.json`, causing issues when concatenating the Etcher CLI.
See: https://github.com/resin-io/etcher/pull/1235
See: https://github.com/resin-io/etcher/pull/1228

refactor: get rid of `is-elevated`

---

tests/image-stream/archive-hooks/zip.spec.js
tests/image-stream/bz2.spec.js
tests/image-stream/gz.spec.js
tests/image-stream/img.spec.js
tests/image-stream/metadata/zip.spec.js
tests/image-stream/tester.js
tests/image-stream/utils.spec.js
tests/image-stream/xz.spec.js
tests/image-stream/zip.spec.js

This changes the test cases to just return the Promises, to avoid timing out on failures and to provide better error messages and stack traces.

test: Use mocha with promises instead of callbacks

---

lib/gui/components/progress-button/templates/progress-button.tpl.html

We replace the erroneous direct Math.min usage in ProgressButton's
template with a wrapped version on the controller.
Changelog-Entry: Wrap Math.min on ProgressButton's controller.

fix(GUI): wrap Math.min on ProgressButton controller

---

scripts/ci/ensure-all-node-requirements-available.sh

After a lot of experimentation, I eventually found out why https://github.com/resin-io/etcher/pull/1208#issuecomment-291585481 failed on Travis but still passed on Appveyor.
Turns out that `set -e` doesn't work properly in Bash scripts on Windows (I dunno why), so the `exit 1` was only exiting the inner subshell, and not exiting the whole script (the same behaviour could be observed on Linux by commenting out the `set -e` line).
This PR fixes things properly, so that even under Bash on Windows, the `exit 1` error code will still get bubbled all the way up to the top, which would cause `make` to fail, which would cause the Appveryor build to fail as expected.
AFAICT `ensure-all-node-requirements-available.sh` was the only script affected by this issue, as it's the only one that has a …

chore: fix a CI script to 'properly fail' on Windows

---

lib/gui/app.js
lib/gui/components/flash-error-modal/flash-error-modal.js
lib/gui/components/flash-error-modal/services/flash-error-modal.js
lib/gui/models/flash-state.js
lib/gui/modules/image-writer.js
lib/gui/pages/finish/controllers/finish.js
lib/gui/pages/finish/finish.js
lib/gui/pages/main/controllers/flash.js
lib/gui/pages/main/controllers/main.js
lib/gui/pages/main/main.js
tests/gui/models/flash-state.spec.js
tests/gui/modules/image-writer.spec.js
tests/gui/pages/main.spec.js

We remove the usage of Angular from 'FlashStateModel' and its usage
throughout the project comes under the new 'flashState' moniker.
Changelog-Entry: Remove the usage of Angular from 'FlashStateModel' and
rename its usage to 'flashState'.
Depends: #1261

refactor(GUI): remove Angular from FlashStateModel and rename

---

.gitattributes
lib/image-stream/utils.js
tests/image-stream/iso.spec.js
tests/image-stream/utils.spec.js

This is a regression caused by
https://github.com/resin-io/etcher/pull/1257, which introduced a new way
to detect mime types by using the `mime-types` module.
This module, contrary to `file-type`, will detect certain ISO files as
`application/x-iso9660-image`, which Etcher doesn't know how to handle,
and will therefore should at the user that the format is unsupported.
Changelog-Entry: Don't interpret certain ISO images as unsupported.

fix(image-stream): interpret iso9660 as application/octet-stream

---

lib/image-stream/handlers.js
tests/image-stream/dmg.spec.js

The `application/x-apple-diskimage` handler doesn't return a path,
causing an issue when fetching the image metadata, and trying using the
path to determine if its a supported image type.
Changelog-Entry: Fix "Path must be a string. Received undefined" when selecting Apple images.

fix(image-stream): return a path from the handler

---

lib/image-stream/index.js
tests/image-stream/directory.spec.js

If the user tries to drag and drop a directory to the application, then
he'll get a scary `EISDIR` error message. This commit catches this
error, and display a nice user friendly message instead.
Changelog-Entry: Prevent uncaught `EISDIR` when dropping a directory to the application.

fix(image-stream): throw user error if image is a directory

---

lib/cli/options.js

Consider the following scenario:
- The user selects an image from an external drive
- The user selects a drive
- The user unmounts/ejects the external drive
- The user clicks flash
The application state will contain an image path that is no longer
accessible, causing an ENOENT error when spawning the CLI process.
Changelog-Entry: Display a user error if the image is no longer accessible when the writer starts.

fix(CLI): throw error if image is inaccessible

---

package.json

This avoids codespell printing warnings for binary files
which have been added recently (`.iso`, `.dmg`), as well as dotfiles (i.e. `.DS_Store`).

chore(package): Fix codespell binary file warnings

---

scripts/build/debian/etcher-electron.sh

The rc2 debian package is not working because the path where the package files
is installed has changed. The change in paths comes from an upstream change
in the electron-installer-debian node package. So, updating the path here to
match the actuall install location.

Fix debian package run script

---

npm-shrinkwrap.json
package.json

This version fixes the release not being sent to Mixpanel.
Changelog-Entry: Upgrade `resin-corvus` to 1.0.0.beta-24

upgrade: resin-corvus to 1.0.0.beta-24

---

npm-shrinkwrap.json
package.json

This version contains a fix for when unmounting a physical drive with no
logical volumes attached.
See: http://github.com/resin-io-modules/mountutils/pull/24
Changelog-Entry: Fix "Unmount failed, invalid drive" error on Windows.

upgrade: `mountutils` to v1.0.4

---

npm-shrinkwrap.json
package.json

This release fixes an uncaught error when there is a validation error.
See: https://github.com/resin-io-modules/etcher-image-write/pull/94
Changelog-Entry: Fix "function createError(opts) {}" error on validation failure.

upgrade: `etcher-image-write` to v9.0.2

---

tests/image-stream/directory.spec.js

See: https://github.com/resin-io/etcher/pull/1279#discussion_r110880004

tests(image-stream): remove unnecessary big timeout

---

tests/image-stream/tester.js

This would have prevented https://github.com/resin-io/etcher/pull/1278
from happening.

tests(image-stream): ensure imageStream.getFromFilePath() returns a path

---

package.json

This version contains a patch to output debugging information.
See: https://github.com/resin-io-modules/elevator/pull/9

upgrade: `elevator` to v2.2.0

---

npm-shrinkwrap.json
package.json

This version handles better non-error objects sent to Sentry.
Changelog-Entry: Upgrade `resin-corvus` to 1.0.0-beta.25.

upgrade: resin-corvus to 1.0.0-beta.25

---

package.json

This version improves the error message if the elevate.exe utility
failed.
See: https://github.com/resin-io-modules/elevator/pull/10

upgrade: `elevator` to v2.2.1

---

lib/child-writer/index.js
lib/shared/robot/index.js
tests/shared/robot.spec.js

Currently, if the child writer receives a message from the writer
process that is not a valid robot object, then it will throw an error.
Now, we check if the message is a robot message, and if so, we try to
parse it (throwing errors if its indeed a malformed/incomplete robot
message), however we log it if not.
The main motivation behind this feature is that it will allows us to
print debugging information on the mountutils module, and have it
redirected to DevTools.

feat(child-writer): log non-robot messages for debugging purposes

---

lib/gui/pages/main/controllers/flash.js
lib/shared/messages.js
npm-shrinkwrap.json
package.json

This commit shows a user friendly message when Etcher loses access to
the drive while flashing/validating, and prevents the cryptic errors
from getting to Sentry.
See: https://github.com/resin-io-modules/etcher-image-write/pull/96
Changelog-Entry: Show a user friendly message when the drive is unplugged half-way through.

fix(GUI): show a friendly message when the drive is unplugged half-way through

---

lib/cli/writer.js
npm-shrinkwrap.json
package.json

This version accepts a `MOUNTUTILS_DEBUG` environment variable to make
the module output extra logging information, which we enable in this
commit as well.
See: https://github.com/resin-io-modules/mountutils/pull/25

upgrade: `mountutils` to v1.0.5

---

lib/child-writer/writer-proxy.js
lib/cli/writer.js
lib/start.js

Windows will not react to dynamically set environment variables (e.g:
`process.env.MOUNTUTILS_DEBUG = '1'`), so in order to workaround this
limitation, we set `MOUNTUTILS_DEBUG` in
`lib/child-writer/writer-proxy.js` when spawning the CLI, and we also
set `DEBUG='*'` in `lib/start.js`, so it gets picked up by the child
writer module, which spawns the writer proxy by inheriting the
environment.

fix(GUI): correctly log debugging messages on Windows

---

package.json

This version prints debug messages to `stdout`.
See: https://github.com/resin-io-modules/elevator/pull/11

upgrade: `elevator` to v2.2.2

---

npm-shrinkwrap.json
package.json

This version includes a fix to throw an `EUNPLUGGED` error instead of an
`UNKNOWN` one when unplugging an SD Card from an internal reader on
Windows.
Changelog-Entry: Fix "UNKNOWN: unknown error" error when unplugging an SD Card from an internal reader on Windows.
See: https://github.com/resin-io-modules/etcher-image-write/pull/97

upgrade: `etcher-image-write` to v9.1.1

---

lib/image-stream/README.md
lib/image-stream/supported.js
npm-shrinkwrap.json
tests/shared/supported-formats.spec.js

This fixes two things: The format detection, and a bug in `udif`.
First, by categorizing the `.dmg` extension as compressed image,
`.isSupportedImage()` would attempt to detect the format after stripping
the extension, causing it to be misdetected.
Second, `udif`'s ReadStream didn't add the `dataForkOffset` to its
position when reading blocks, causing the wrong data to be read for some images,
in turn causing zlib to error on invalid headers.
Changes:
- Classify `.dmg` as `type: 'image'`
- Update `udif` to 0.8.0
Changelog-Entry: Fix Apple disk image detection & streaming

fix(image-stream): Fix Apple disk image detection & reading

---

npm-shrinkwrap.json
package.json

This version solves the issue regarding some messages
getting console logged (and reaching Sentry) as "[object Object]".
Changelog-Entry: Upgrade `resin-corvus` to 1.0.0-beta.26.

upgrade: resin-corvus to 1.0.0-beta.26

---

lib/gui/pages/main/controllers/flash.js

If the user cancels the elevation dialog, then no event is emitted,
making it hard to track down what happened after the flash button was
pressed.

fix(GUI): send an "elevation cancelled" analytics event

---

lib/gui/pages/main/controllers/flash.js
lib/shared/messages.js

If we get EIO at this point, then it means that the writer did
everything it could to recover (like multiple retries), and the error
is truly an input/output error coming from the operating system.
In this commit, we show a nice user friendly message explaining what
happened, and advising users to try again with another drive, reader, or
port instead of showing an uncaught EIO error.
Changelog-Entry: Show a friendly user message on EIO after many retries.

fix(GUI): catch EIO errors and display a user friendly message

---

package.json
scripts/build/docker/Dockerfile-i686
scripts/build/docker/Dockerfile-x86_64
scripts/build/docker/Dockerfile.template
scripts/build/electron-installer-debian-linux.sh

We currently require this module to be available in the environment in
order to be able to build debian packages.
This commit adds it as a development dependency, so we can have control
over the version that we use, to prevent any potential incompatibility.
We also update the `udif` package.json version to match what its on the
shrinkwrap file to avoid npm complaining about version mismatches.
See: https://github.com/resin-io/etcher/pull/1290

chore: make electron-installer-debian a development dependency

---

scripts/build/docker/Dockerfile-i686
scripts/build/docker/Dockerfile-x86_64
scripts/build/docker/compile-template.js
scripts/build/docker/run-command.sh

We recently hit an issue where Etcher builds produced on Ubuntu relied
on a too new glibc version, making them incompatible with GNU/Linux
distributions such as Debian Jessie.
As a solution, we will start producing builds on Debian Jessie, which
ensures that the builds will be compatible with the majority of
GNU/Linux versions out there.

chore: perform GNU/Linux builds on Debian Jessie docker containers

---

lib/child-writer/writer-proxy.js
lib/cli/etcher.js
lib/cli/options.js
lib/cli/writer.js
lib/gui/models/store.js
lib/gui/pages/main/controllers/image-selection.js
lib/gui/utils/manifest-bind/directives/manifest-bind.js
lib/image-stream/archive-hooks/zip.js
lib/image-stream/archive.js
lib/image-stream/index.js
lib/shared/errors.js
lib/shared/robot/README.md
lib/shared/robot/index.js
lib/shared/utils.js
tests/shared/errors.spec.js

Currently, both of these functions accept two arguments: the error
title, and the error description. This function signature makes is hard
to keep adding options to these error creation functions, like an error
code, so this commit refactors them to take a single argument: an
options object containing `title` and `description` properties.

refactor(errors): createError and createUserError accept an object

---

package.json

This version contains a fix where an elevation error was not yielded
correctly.
See: https://github.com/resin-io-modules/elevator/pull/12

upgrade: `elevator` to v2.2.3

---

.travis.yml
appveyor.yml
docs/RUNNING-LOCALLY.md
package.json
scripts/build/docker/Dockerfile-i686
scripts/build/docker/Dockerfile-x86_64
scripts/build/docker/Dockerfile.template
scripts/build/electron-create-asar.sh

To prevent any potential version incompatibility caused by simply installing
the latest version of the packages in the CI services.
See: https://github.com/resin-io/etcher/pull/1326

chore: make `asar` a development dependency

---

lib/gui/pages/main/controllers/flash.js

This event property will allow us to inspect how many people are running
Etcher without the validation mechanism.
See: https://github.com/resin-io/etcher/issues/1293

feat(GUI): add a validateWriteOnSuccess property to the flash event

---

package.json

Optional dependencies (and their dependencies) are not tracked by the
shrinkwrap file. In order to prevent incompatibilities, we lock the
versions of all optional dependencies.
See: https://github.com/resin-io/etcher/pull/1304

chore: lock optional dependencies versions

---

scripts/clean-shrinkwrap.js

Newer npm versions (4.4+ I believe) even remove dependencies
not shrinkwrapped yet while pruning causing newly installed dependencies
to not always be shrinkwrapped / updated in the shrinkwrap.
Removing the prune allows for this to work properly again and in the future,
with the drawback that care must be taken to not have extraneous dependencies
in the module tree.

chore(scripts): Remove prune from shrinkwrap cleanup

---

npm-shrinkwrap.json
package.json

- https://github.com/resin-io-modules/etcher-image-write/pull/99
- https://github.com/resin-io-modules/etcher-image-write/pull/98
See: https://github.com/resin-io-modules/etcher-image-write/blob/master/CHANGELOG.md
Changelog-Entry: Show user friendly messages for `EBUSY, read` and `EBUSY, write` errors on macOS.

upgrade: `etcher-image-write` to v9.1.2

---

npm-shrinkwrap.json
package.json

This updates `udif` from 0.8.0 -> 0.9.0, fixing a stall when flashing
certain dmg images due to `UDIF.ReadStream()` overrunning block regions.
See jhermsmeier/node-udif#5
Changelog-Entry: Fix stall / freezing when flashing certain dmg images
Connects To: #1342

chore(package): Update udif to 0.9.0

---

npm-shrinkwrap.json
package.json

- https://github.com/resin-io-modules/mountutils/pull/26
Changelog-Entry: Fix "Unmount failed" on Windows where the PC is connected to network drives.

upgrade: `mountutils` to v1.0.6

---

lib/child-writer/writer-proxy.js
lib/shared/permissions.js
tests/shared/permissions.spec.js

The elevation mechanism currently embedded in
`lib/child-writer/writer-proxy.js` is extracted as a separate re-usable
function in `lib/shared/permissions.js`.
This change hugely simplifies the writer proxy, while allowing us to
iterate faster on the elevation core functionality.

refactor: extract elevation routines to lib/shared/permissions.js

---

scripts/build/concatenate-javascript.sh

This is causing all the snapshot builds to fail when a PR is merged to
master.

chore: make use of browserify as a development dependency

---

docs/MAINTAINERS.md
docs/PUBLISHING.md
docs/USER-DOCUMENTATION.md
lib/gui/app.js
lib/gui/components/update-notifier/services/update-notifier.js
lib/gui/components/update-notifier/templates/update-notifier-modal.tpl.html
lib/gui/components/update-notifier/update-notifier.js
lib/gui/css/main.css
lib/gui/models/store.js
lib/gui/pages/settings/styles/_settings.scss
lib/gui/pages/settings/templates/settings.tpl.html
lib/shared/release.js
lib/shared/s3-packages.js
npm-shrinkwrap.json
package.json
tests/gui/components/update-notifier.spec.js
tests/shared/release.spec.js
tests/shared/s3-packages.spec.js

`etcher-latest-version` was kept in a separate repository in order to
re-use it with the Etcher website, however the Etcher website is not
using it at all, and we're moving towards having the website in the main
repository.
Therefore, this commit brings back the logic from
`etcher-latest-version`, but introduces it as
`lib/shared/s3-packages.js`, in order to not tie ourselves to the
AngularJS framework, and as a step towards the Etcher SDK.
As a nice little bonus, this commit adds support for an
`ETCHER_FAKE_S3_LATEST_VERSION` environment variable that can be used to
trick Etcher that there is an available update, and therefore show the
update notifier modal.
Also, this commit adds support for snapshot builds update-checks, by
checking the `resin-nightly-downloads` S3 bucket if the …

refactor(GUI): integrate `etcher-latest-version` into the main repo

---

lib/shared/errors.js
tests/image-stream/directory.spec.js
tests/shared/errors.spec.js

This utility function is useful to avoid duplicating the logic of
checking whether an error is a user error across the code base.

refactor(errors): add isUserError utility function

---

.gitattributes

This adds a `diff` tag to binary files in `.gitattributes`,
enabling git to use an external tool to generate diffable output for binary files
by adding a handler to the local or global git config, i.e:
```
[diff "hex"]
textconv = hexdump
binary = true
```

chore(gitattributes): Add "hex" diff tag to binary files

---

scripts/build/docker/Dockerfile-i686
scripts/build/docker/Dockerfile-x86_64
scripts/build/docker/Dockerfile.template
scripts/build/docker/compile-template.js
scripts/build/docker/run-command.sh

We recently discovered that users not running latest GNU/Linux
distributions were having problems when Etcher tried to load native
modules. We used to build packages on Ubuntu 16.04, which ships with
GLIBC 2.23.
In order to solve that issue, we moved our build Docker containers to
Debian Jessie, which ships with GLIBC 2.19, however we noticed that
users running even older Linux distributions were still having the same
issue, so this commit switched the Docker containers to Ubuntu 12.04,
which ships with GLIBC 2.15.
See: https://github.com/resin-io/etcher/pull/1319

chore: build on Ubuntu 12.04 Docker base images

---

package.json

This version is no longer used, and was removed from the shrinkwrap
file, but for some reason, we forgot to remove it from package.json.
See: https://github.com/resin-io/etcher/pull/1183

chore: remove `etcher-latest-version` from package.json

---

npm-shrinkwrap.json
scripts/ci/ensure-npm-valid-dependencies.sh

The `npm ls` command will exit with an error code if there are invalid
or extraneous dependencies.
This commits adds that command to `make sanity-checks`, so we can catch
those cases early one.

chore: ensure there are no extraneous or invalid npm dependencies

---

npm-shrinkwrap.json

Our `npm-shrinkwrap.json` file contains two entries for the `isstream`
dependency. One of them is in the top level of the file, and marks
`isstream` as a development dependency.
The `request` module makes use of `isstream`, so there is another
instance of `isstream` nested inside `request` which is marked as a
production dependency.
Most NPM versions will realise that there are two instances of
`isstream`, and since one of them is a production development, it will
include it in the final package.
However, there are some NPM version, like 4.6.1, which will only
consider the top level entry, and completely omit `isstream` on the
final package, causing a "Cannot find module 'isstream'" error.
The solution was to manually update the shrinkwrap file to remove the
nested instance, and make the …

chore: make `isstream` a top level production development

---

.gitattributes
.gitignore
.travis.yml
Makefile
appveyor.yml
binding.gyp
docs/RUNNING-LOCALLY.md
lib/shared/bindings.js
lib/shared/permissions.js
package.json
scripts/build/dependencies-npm.sh
scripts/build/docker/Dockerfile-i686
scripts/build/docker/Dockerfile-x86_64
scripts/build/docker/Dockerfile.template
src/elevator_init.cpp
src/os/elevate.cpp
src/os/elevate.h
src/utils/v8utils.cpp
src/utils/v8utils.h

Sentry error reports showcase that elevation errors on Windows are one
of the most frequent Windows errors.
In order to perform Windows elevation, we ship compiled EXEs of a third
party CLI elevation application (http://code.kliu.org/misc/elevate/)
that has several limitations:
- We have the scan the output of the script to determine if a user
cancelled the elevation request, which causes all sorts of issues on
computers where English is not the main language
- The application displays a `cmd.exe` window for some milliseconds,
which is bad UX, that we have to workaround by distributing a patched
version of the tool
- The CLI application has to be spawned, which seems to be problematic
if users have anti-virus software, leading to hard to debug issues
- We don't have any control if …

feat(GUI): implement Windows elevation using a native module

---

docs/CONTRIBUTING.md

This adds instructions on how to set up human-readable binary diffs
with git for Etcher, which is useful when altering test images etc.
Connects-To: #1367

doc(contributing): Add section about binary diffs

---

.travis.yml
Makefile
appveyor.yml
scripts/ci/appveyor-deploy.bat
scripts/ci/appveyor-install.bat
scripts/ci/appveyor-test.bat
scripts/ci/travis-deploy.sh
scripts/ci/travis-install.sh
scripts/ci/travis-test.sh

We forgot to do so on the PR that introduces this script.
This commit also moves all the CI code to separate scripts.
See: https://github.com/resin-io/etcher/pull/1371

chore: add ensure-npm-valid-dependencies.sh to sanity-checks make target

---

lib/gui/pages/settings/templates/settings.tpl.html

To make it clear that this actually controls the reporting of errors back to resin.io, and not the reporting of errors to the user.
See #1383 
If we wanted to be even more explicit, we could even change this to "Report errors and statistics back to resin.io" or "Report errors and anonymous statistics back to resin.io" ?  This would better protect the users' privacy, but also _might_ result in more people unticking the box, leading to less reliable statistics?

style(settings): Clarify meaning of the "Report Errors" button

---

npm-shrinkwrap.json
package.json

This version gets rid of the `diskpart` optional dependency:
- https://github.com/resin-io-modules/etcher-image-write/pull/101
which will simplify the way we manage our `npm-shrinkwrap.json` file.
See: https://github.com/resin-io/etcher/pull/1379

upgrade: `etcher-image-write` to v9.1.3

---

lib/shared/messages.js

* Specify that Rufus is only an option for Windows.
* Suggest Apple Boot Camp Assistant (built-in) as an alternative for macOS users.
Not sure what to suggest for Linux other than possibly the following online search:
[`Linux "ms-sys" bootable Windows ISO`](https://duckduckgo.com/?q=Linux%20%22ms-sys%22%20bootable%20Windows%20ISO)

Suggest macOS alternative to Rufus

---

Makefile
scripts/build/concatenate-javascript.sh
scripts/build/docker/Dockerfile-i686
scripts/build/docker/Dockerfile-x86_64
scripts/build/docker/Dockerfile.template
scripts/ci/appveyor-install.bat
scripts/ci/travis-install.sh

UglifyJS v3 was recently released, which includes support for
compressing ES6 code.
This commit introduces the following changes:
- Add a boolean `-m` option to `concatenate-javascript.sh`, which when
set, will minify the final concatenated JavaScript file
- Install `uglify-es` in the CI servers
See: https://news.ycombinator.com/item?id=14285179
See: https://github.com/mishoo/UglifyJS2/tree/harmony

chore(CLI): minify Etcher CLI code

---

npm-shrinkwrap.json
package.json

This version includes the following fix:
- https://github.com/resin-io-modules/drivelist/pull/164
The above change is also a huge step forward to finalizing the Etcher
CLI packaging story.
See: https://github.com/resin-io/etcher/issues/355
See: https://github.com/resin-io-modules/drivelist/blob/master/CHANGELOG.md
Fixes: https://github.com/resin-io/etcher/issues/1395
Changelog-Entry: Fix error on startup when Windows username contained an ampersand.

upgrade: `drivelist` to v5.0.20

---

npm-shrinkwrap.json

Ensure that the `npm-shrinkwrap.json` is up to date.
These changes were backported from
https://github.com/resin-io/etcher/pull/1379, since it will take a while
for that PR to get merged.

chore: upgrade `npm-shrinkwrap.json` file

---

npm-shrinkwrap.json
package.json

This version upgrades `drivelist` to v5.0.20, which inlines the scripts
as a JSON file.
See: https://github.com/resin-io-modules/resin-cli-visuals/pull/41
See: https://github.com/resin-io-modules/resin-cli-visuals/blob/master/CHANGELOG.md
See: https://github.com/resin-io/etcher/issues/355
[1.3.0]: https://github.com/resin-io/resin-cli-visuals/compare/v1.2.9...v1.3.0

upgrade: `resin-cli-visuals` to v1.3.1

---

scripts/build/node-static-entry-point-download.sh

See: https://github.com/resin-io/etcher/pull/1365

chore: replace `wget` with `curl` on `node-static-entry-point-download.sh`

---

Makefile

The `cli-develop` target was pointing `node-gyp` to the Electron
headers, which caused native add-ons to not work.

chore(CLI): fix `cli-develop` Make target headers version

---

.gitattributes
Makefile
patches/cli/lzma-native-index-static-addon-require.patch
scripts/build/concatenate-javascript.sh
scripts/build/dependencies-npm-extract-addons.sh

For some strange reason, Browserify will hardcode absolute paths from
the machine that generated the bundle to be able to resolve `__dirname`
and `__filename` calls. This makes no sense, given that it means that
the Browserify bundle will not work when we move it to another machine,
which went undetected probably for months.
The Browserify community apparently makes modules to fix this particular
issue (like `bundle-collapser`, and `intreq`), however none of this seem
to solve the problem for the Etcher CLI bundle.
I also gave https://github.com/zeit/pkg a go, however I gave up after
not being able to make use of native modules (nothing seems to work; the
packager result will simply not find the addons).
Finally, I ended up making the following workarounds:
- Edit the Browserify bundle …

fix(CLI): workaround absolute paths in Browserify bundles

---

.github/ISSUE_TEMPLATE.md

This adds another field to the issue template, where a user is prompted to specify the image being flashed, as this question quite often arises and is rarely specified by the user up front.

doc(github): Add question about flashed image to issue template

---

lib/shared/permissions.js

Etcher will get stuck at "Starting..." when executing the application on
a directory that contains spaces, like "C:\Program Files (x86)".
The problem is that the command is not quoted correctly when passed to
`cmd.exe /c`. This commit addresses the following specific problems:
- Quote the whole argument to `cmd.exe /c`
- Quote each individual argument after `call`
Changelog-Entry: Fix application stuck at "Starting..." on Windows.
See: https://github.com/resin-io/etcher/pull/1376

fix(GUI): handle spaces in installation path when elevating on Windows

---

lib/shared/s3-packages.js
tests/shared/s3-packages.spec.js

Querying S3 to determine the latest available versions might throw
`ECONNRESET` and `ECONNREFUSED`. This commit extends the
`s3Packages.getRemoteVersions()` function to handle these errors and
return no available version if so, like we already do with other similar
HTTP errors.
Changelog-Entry: Fix `ECONNRESET` and `ECONNREFUSED` errors when checking for updates on unstable connections.
Fixes: https://github.com/resin-io/etcher/issues/1396
Fixes: https://github.com/resin-io/etcher/issues/1388

fix(GUI): ignore ECONNRESET and ECONNREFUSED when querying S3

---

lib/cli/writer.js

If the user has the "Unmount on success" setting enabled, then Etcher
will unmount the drive after ther flashing process completed, right
after closing the drive file descriptor.
Turns out macOS will attempt to re-mount a drive once its file
descriptor gets closed, which means that if we try to unmount too fast,
then the drive will get re-mounted again.
As a naive solution, we add a timeout before finally unmounting the
drive. Keep in the mind this is only a temporary solution until we fix
mountutils to do the right thing.
See: https://github.com/resin-io/etcher/pull/1414
Fixes: https://github.com/resin-io/etcher/issues/1385
Changelog-Entry: Prevent drive from getting re-mounted in macOS even when the unmount on success setting is enabled.
Signed-off-by: Juan Cruz …

fix: add a delay before the final unmount on success

---

docs/CLI-INSTALLATION.md

Due to display on the website, the headings need to be level 3, rather than level 2.

doc(CLI-INSTALLATION): Make headings h3

---

Makefile
scripts/build/dependencies-npm.sh
scripts/build/docker/Dockerfile-i686
scripts/build/docker/Dockerfile-x86_64
scripts/build/docker/Dockerfile.template

There are various problems that contributed to this issue:
- `node-pre-gyp` doesn't detect the 6.10.3 node version. We reverted to
6.1.0, which the module recognised, and which shares the same v8 ABI
- Passing `--force` to `npm install` causes npm to swallow any errors
and silently continue
- The x86 Docker container has problems writing to `$HOME/.node-gyp`.
The solution is to enable `unsafe-perm` given that the container is
running as `root`
Fixes: https://github.com/resin-io/etcher/issues/1444

chore: fix lzma-native not building for the x86 Linux CLI

---

.travis.yml
Makefile
appveyor.yml
scripts/ci/appveyor-build-installers.bat
scripts/ci/travis-build-installers.sh

This allows us to catch changes that break our installer builds before
merging the problematic changes.
As a way to simplify the CI configuration files, this commit introduces
an `installers-all` Makefile target that builds all installers.
This commit also replaces all the `cp -rf` calls with `cp -RLf` in
Makefile to avoid some weird hard link Appveyor issues.
See: https://github.com/resin-io/etcher/pull/1078
See: https://github.com/resin-io/etcher/pull/1354

chore: create installers (but don't publish) on every pull request

---

.dockerignore
.gitattributes
docs/RUNNING-LOCALLY.md
requirements.txt
scripts/build/docker/Dockerfile-i686
scripts/build/docker/Dockerfile-x86_64
scripts/build/docker/Dockerfile.template
scripts/ci/appveyor-install.bat
scripts/ci/travis-install.sh

We're currently hardcoding various pip dependencies in
`appveyor-install.bat` and `travis-install.sh`.
This commit moves all the dependencies to a `requirements.txt` file in
the root of the project, and makes every install script run `pip install
-r requirements.txt`.
See: https://github.com/resin-io/etcher/pull/1401#discussion_r116547053

chore: track python dependencies with pip

---

lib/shared/s3-packages.js
tests/shared/s3-packages.spec.js

When the user is behind a firewall, then the HTTP request to query the
latest available version from S3 may throw an EACCES error, eventually
causing a confusin "You don't have access to this resource" error
window.
Changelog-Entry: Fix "You don't have access to this resource" error at startup when behind a firewall.
Fixes: https://github.com/resin-io/etcher/issues/1458

fix(GUI): catch EACCES when querying S3 packages

---

npm-shrinkwrap.json
package.json
scripts/build/concatenate-javascript.sh

We encountered a Browserify bug when releasing the CLI, where absolute
paths would be hard-coded in the final bundle. Since we were in the
middle of a release process, we added a quick and dirty
search-and-replace workaround on `concatenate-javascript.sh`.
After the release, we submitted a PR to Browserify which fixes the
issue. This commit makes use of my personal fork to be able to use such
fix while it gets merged to the main project.
See: https://github.com/substack/node-browserify/pull/1725
See: https://github.com/resin-io/etcher/pull/1409
Fixes: https://github.com/resin-io/etcher/issues/1429

fix(CLI): get rid of Browserify absolute path workaround

---

lib/gui/os/notification.js
lib/gui/pages/main/controllers/flash.js
lib/shared/messages.js

We add the image filename, its destination drive, and application icon
to the notifications.
See: #1443
Changelog-Entry: Add image name, drive name, and icon to notifications.

feat(GUI): add metadata and icon to notifications

---

scripts/build/docker/Dockerfile-i686
scripts/build/docker/Dockerfile-x86_64
scripts/build/docker/Dockerfile.template

Previously it was using http://ubuntu.stu.edu.tw but this host is no longer
active, which was causing all the 32bit Linux TravisCI builds to fail.

chore(docker): Change APT mirror used by the Ubuntu12.04 32bit docker image

---

lib/gui/components/drive-selector/styles/_drive-selector.scss
lib/gui/components/drive-selector/templates/drive-selector-modal.tpl.html
lib/gui/css/main.css

We make the size number in the drive selector stay whole through
the `word-break: keep-all` CSS property, ensuring that it doesn't
partially overflow to the next line.
See: https://github.com/resin-io/etcher/issues/1437
Changelog-Entry: Don't break up size number in drive selector.

fix(GUI): don't break up size number in drive selector

---

scripts/build/docker/Dockerfile-i686
scripts/build/docker/Dockerfile-x86_64
scripts/build/docker/Dockerfile.template
scripts/build/docker/compile-template.js

Resin.io already publishes multi-arch Docker base images running Jessie,
which is Debian version we wanted before falling back to Ubuntu 12.04.
The main reason behind this change is to be able to use other resin.io
base images (like ARM ones) without requiring a lot of per-base-image
changes.

chore: make use of resin.io's Docker base images

---

lib/gui/css/main.css
lib/gui/pages/settings/styles/_settings.scss
lib/gui/pages/settings/templates/settings.tpl.html

By removing the 'advanced' sub-header we stop the settings from
overflowing into the footer.
See: https://github.com/resin-io/etcher/issues/1383
Changelog-Entry: Stop settings from overflowing into the footer.

fix(GUI): stop settings overflow into footer

---

lib/gui/css/main.css
lib/gui/pages/finish/styles/_finish.scss

We make the fonts a regular weight instead of bold on the success page's
fallback banner.
Changelog-Entry: Make the fallback success page banner message a normal font
weight.

style(GUI): normal weight message on success page

---

lib/gui/pages/main/controllers/flash.js

We update the relative icon path to the correct relative path containing
the Etcher icon.
See: https://github.com/resin-io/etcher/issues/1443
Changelog-Entry: Correct the relative notification icon path.

fix(GUI): correct relative notification icon path

---

npm-shrinkwrap.json
package.json

This updates `mountutils` from 1.0.6 to 1.2.0, which includes
various fixes and adds AsyncWorkers:
- fix(windows): Replace use of `wsprintf()`
- fix(darwin): Add local context to avoid global state
- feat(src): Use Nan::AsyncWorker
Change-Type: upgrade

chore(package): Update mountutils to 1.2.0

---

lib/shared/s3-packages.js
tests/shared/s3-packages.spec.js

This error may get thrown when fetching the list of S3 packages when the
user is behind a proxy tht causes the SSL certificate to incorrectly not
be trusted.
See: https://github.com/atom/apm/issues/103
See: https://github.com/resin-io/etcher/issues/1465
Changelog-Entry: Fix `UNABLE_TO_VERIFY_LEAF_SIGNATURE` error at startup.

fix(GUI): ignore UNABLE_TO_VERIFY_LEAF_SIGNATURE HTTP issues

---

lib/gui/css/main.css
npm-shrinkwrap.json
package.json

This updates `node-sass` from v3.x to v4.x in anticipation
of addition of Electron ABI versions in an upcoming version.

upgrade(package): Update node-sass to 4.5.3

---

lib/gui/app.js
lib/gui/components/safe-webview.js
lib/gui/components/safe-webview/safe-webview.js
lib/gui/etcher.js
lib/gui/index.html

We reload and reset the webview to its original URL when the user
navigates away from the success screen.
Changelog-Entry: Reset webview after navigating away from success
screen.

feat(GUI): reset webview after navigating away

---

npm-shrinkwrap.json
package.json

- https://github.com/resin-io-modules/drivelist/pull/168
Changelog-Entry: Fix occasional increased CPU usage because of perl regular expression in macOS.
Fixes: https://github.com/resin-io/etcher/issues/1288

upgrade: `drivelist` to v5.0.22

---

package.json

The ampersand confuses nupkg when generating Windows installers from
`electron-builder`.
The referenced issue talks about an issue where the ampersand is present
on the application name, but anything that gets into the `.nuspec` XML
file, including the description, triggers the issue.
See: https://github.com/electron-userland/electron-builder/issues/517

chore: remove ampersand from package description

---

.gitignore
Makefile
docs/PUBLISHING.md

This is the directory where `electron-builder` will output build
artifacts.

chore: output build artifacts to dist/

---

Makefile
lib/child-writer/writer-proxy.js
package.json

This commit re-organizes various metadata properties in package.json so
that the structure better matches what `electron-builder` expects, to
ease the transition.
- Move `.companyName` to the Makefile (we don't need this in
package.json)
- Move `.displayName` to `.build.productName`
- Move `.copyright` to `.build.copyright`
- Move category to `.build.mac.category`
- Move bundle id to `.build.appId`

chore: re-organize package.json in a way similar to electron-builder

---

Makefile
docs/CONTRIBUTING.md
docs/MAINTAINERS.md
package.json
scripts/ci/ensure-staged-sass.sh
scripts/ci/test.sh

We currently have various npm script target, and some of them are
getting complex enough that making sense out of them in package.json is
not a trivial task.
This commit moves all npm targets that are not directly recognisable by
npm (like `start`, `test`, `preshrinkwrap`, etc) into the Makefile.

chore: move npm targets to Makefile

---

Makefile

The `./` prefix is unnecessary.
See: https://github.com/resin-io/etcher/pull/1505#pullrequestreview-43444274

chore: don't use ./ when generating sass files

---

Makefile
scripts/build/node-package-cli.sh

This makes it more consistent with the other Makefile rules

chore: move `mkdir` call from node-package-cli.sh to Makefile

---

lib/gui/models/settings.js
lib/gui/models/store.js
tests/gui/models/settings.spec.js

This commit is the first on a series of commit to incrementally
implement support for configuration files (so we avoid a huge PR like we
have at the moment).
Once of the first things we can do is replace the `SET_SETTING` redux
action with an atomic `SET_SETTINGS` action that sets all the settings
for the application at once.
The purpose of this change is that later the `SET_SETTINGS` action can
be modified to stringify all the settings and store them in a
configuration file, without having to deal with merges, conflicts, etc
(since the client application if forced to resolve those problems before
calling the `SET_SETTINGS` action.)
The behaviour of the code remains almost the same, with the exception
that the user can now set settings that we don't know about, so the user
can switch …

refactor(GUI): replace SET_SETTING with an atomic SET_SETTINGS action

---

docs/RUNNING-LOCALLY.md
scripts/ci/install.sh

chore(travis): remove unused afsctool macOS dependency

---

lib/gui/pages/main/templates/main.tpl.html

We swap the placement of the progress speed and time residing below the
progress bar.
Changelog-Entry: Swap speed and time below the progress bar.
Closes: https://github.com/resin-io/etcher/issues/1312

feat(GUI): swap progress bar speed and time

---

package.json

Turns out add-ons are loaded just fine from the asar now.
See: https://github.com/electron-userland/electron-builder/issues/1723

chore: don't extract native dependencies out of the asar

---

Makefile

This target builds a package for the current operating system, but
doesn't create an installer out of it, which is useful for debugging
purposes.

chore: make use of electron-builder for the package-electron target 

---

Makefile
electron-builder.yml
lib/child-writer/writer-proxy.js
package.json
requirements.txt

The electron-builder configuration we're putting in package.json is
growing. To make it easier to read and edit, we'll move the whole
`build` property into a configuration file called
`electron-builder.yml`.

chore: move all electron-builder configuration to electron-builder.yml

---

scripts/build/dependencies-npm.sh

CI servers fail with timeouts, or network issues quite frequently,
requiring maintainers to manually restart failed builds.
Hopefully these npm settings will help mitigating these issues.

chore: increase npm retries and max timeout

---

scripts/build/dependencies-npm.sh
scripts/ci/install.sh

This adds the `--silent` flag to several npm commands,
ideally making the output less verbose, for better overview in CI logs.

chore(scripts): Make npm output less verbose

---

.travis.yml
appveyor.yml
scripts/ci/install.sh

This enables caching of `node_modules`, and `ccache` directories,
as well as installation of ccache on Mac OS.

chore(ci): Enable node_modules & ccache caching

---

.travis.yml

This disabled caching of the `node_modules` directory again,
as this is causing failures on Travis CI while building the installers.
Connects To: #1553

chore(package): Disable node_modules caching on Travis CI

---

package.json
scripts/ci/build-installers.sh
scripts/clean-shrinkwrap.js

If we include a platform specific optional dependency in the shrinkwrap
file, then npm will insist in installing it even if the platform doesn't
match. As a solution, we figured out we can avoid putting this platform
specific optional dependencies in the npm-shrinkwrap.json file.
In order to do this, we currently have a script called
`clean-shrinkwrap.js` that runs *before* any `npm shrinkwrap` file (its
a `preshrinkwrap` npm script) that deletes all the platform specific
modules we know about using `npm rm`.
The problem with this approach is that `npm rm` will remove the module's
code from `node_modules`, which means that if we run `npm shrinkwrap`,
we will lose certain optional dependencies, that may be needed at a
later stage.
The solution is to modify the `clean-shrinkwrap.js` script …

chore: don't remove optional dependencies in clean-shrinkwrap.js

---

scripts/ci/ensure-npm-valid-dependencies.sh

As part of our CI sanity checks, we run `npm ls`, to ensure we don't
have any extraneous dependencies (the command fails if so), however by
its own definition, `npm ls` prints the whole dependency tree, which
spams the builds.
This commit redirects stdout to /dev/null, which contains the dependency
tree, but still prints and extraneous dependency warning, which is
printed to stderr instead.

chore: pipe stdout from npm ls to /dev/null

---

electron-builder.yml

One-click installers are a "modern" version of usual wizard installers,
and somewhat resemble the Squirrel.Windows installers you can see in
apps like Atom.
As the name implies, the user needs to agree the license, and that's
all, the remaining installer is non-interactive, leading to a very
smooth user experience.

chore:(windows): make use of NSIS one-click installers

---

scripts/build/dependencies-npm.sh
scripts/ci/install.sh

This silences `npm install`'s stdout to omit noisy output, and only show warnings & errors

chore(scripts): Silence stdout for npm install

---

lib/gui/components/safe-webview.js

We add the API version sent to the banner via a GET search parameter,
allowing for more intricate control over what data needs or can be sent.
Changelog-Entry: Add Webview API version parameter.

feat(GUI): add webview api version parameter

---

src/elevator_init.cpp
src/os/elevate.h
src/os/win32/elevate.cpp
src/utils/v8utils.cpp
src/utils/v8utils.h

Switching the Windows language to a language encoded using UTF-16 (like
Japanese) revealed that our native elevator module garbles language
specific strings, making the child writer process unable to find an
image inside a language specific directory, and thus resulting in a
"File is not accessible" error.
As a solution, we make use of `std::wstring` and wide character Windows
API functions in the elevator module.
Changelog-Entry: Fix "file is not accessible" error when flashing an image that lives inside a directory whose name is UTF-16 encoded on Windows.
Fixes: https://github.com/resin-io/etcher/issues/1459

fix(elevator): make use of wide characters everywhere

---

Makefile
electron-builder.yml
lib/gui/models/store.js
npm-shrinkwrap.json
package.json

- Exclude \*.dll/\*.exe files from the asar in non-Windows operating
systems (from 19.8.0)
- Correctly parse boolean flags in `--extraMetadata` (in v19.9.0)
See: https://github.com/electron-userland/electron-builder/releases/tag/v19.9.1

upgrade: `electron-builder` to v19.9.1

---

lib/gui/pages/main/controllers/image-selection.js

I must have screwed something up during a rebase,
this mends the partition table an windows image checks.

fix(gui): Fix image checks in image selections

---

dictionary
lib/gui/app.js
lib/gui/models/local-settings.js
lib/gui/models/settings.js
lib/gui/models/store.js
npm-shrinkwrap.json
package.json
tests/gui/models/settings.spec.js

We're currently persisting the user settings in localSettings by using a
redux plugin called redux-localstorage. As a way to decouple the redux
store from a technology that is browser specific, this commit makes the
following changes:
- Create local-settings.js, which is concerned with managing settings in
a persisting location
- Decouple the redux store from the persisting storage method
- Extend the settings model to persist settings, cache reads, etc

refactor(GUI): decouple localStorage from the redux store

---

lib/gui/app.js
lib/gui/models/available-drives.js
lib/gui/models/flash-state.js
lib/gui/models/selection-state.js
lib/gui/models/settings.js
lib/shared/store.js
tests/gui/models/settings.spec.js

After https://github.com/resin-io/etcher/pull/1569, the redux store can
run outside of a browser context. This commit moves it to `lib/shared`,
where we will likely move all the other models as well. As an extra, I
renamed `Store` to `store`, since there was no reason for that variable
to be capitalized.

refactor(GUI): move redux store to lib/shared

---

appveyor.yml

We've been hitting some weird npm-shrinkwrap.json issues in our
shrinkwrap staged sanity checks, where Appveyor would complain that the
shrinkwrap is not up to date, while that wasn't the case either locally
or in Travis CI.
The issue is related to caching. If a commit changes a `from` entry of a
npm-shrinkwrap.json dependency, but the CI servers kept the cached
node_modules, then there will be a discrepancy between the `_from` field
from the `package.json` of a dependency in `node_modules` and what the
npm-shrinkwrap.json says. npm will obey `node_modules` over
`npm-shrinkwrap`, causing the invalid diff.
The fix is to make the Appveyor node_modules cached directory dependent
on any change to the npm-shrinkwrap.json file.
See: …

chore(appveyor): make node_modules cache depend on npm-shrinkwrap.json

---

.travis.yml
appveyor.yml

These directories contain files downloaded by electron-builder (like
electron itself), that we can cache in Travis CI and Appveyor CI to
speed up builds.

chore: cache as much as possible from electron-builder

---

lib/gui/etcher.js

The lib/gui/etcher.js file contained a workaround to an Electron issue
that have since then been solved. In summary:
- Replace the `did-finish-load` event of `webContents` with
`ready-to-show`, which is only emitted when the whole webview has
finished loading

refactor(GUI): remove flash of white electron webContents workaround

---

scripts/ci/install.sh

This dependency comes bundled with electron-builder, so there is no
reason to install it separately.
See: https://github.com/resin-io/etcher/pull/1582

chore: don't install NSIS in Appveyor CI

---

.travis.yml
scripts/ci/install.sh

- Homebrew now auto-updates before performing any installation, which
can take quite some time. We can disable this by enabling
HOMEBREW_NO_AUTO_UPDATE
- We can pass the --force-bottle option to `brew install` to force it to
download pre-compiled binaries, and don't attempt any compilations
See: https://github.com/resin-io/etcher/pull/1582

chore: avoid brew taking a long time on Travis CI

---

npm-shrinkwrap.json
package.json

This updates `udif` from 0.9.0 to 0.10.0, fixing two bugs;
* [57ddf788] fix(readstream): Avoid read-before-open situations
* [6333a183] fix(image): try/catch parsing the resource fork plist
[57ddf788]: https://github.com/jhermsmeier/node-udif/commit/57ddf788b72cc1ff17317e560532e5e89adf695c
[6333a183]: https://github.com/jhermsmeier/node-udif/commit/6333a183f6863348723f95b3c8183fea16a30703
Connects To: #1572

upgrade(package): Update udif 0.9.0 -> 0.10.0

---

.eslintrc.yml
lib/gui/components/safe-webview.js
lib/gui/components/svg-icon.js
lib/gui/pages/settings/controllers/settings.js
lib/image-stream/archive.js
lib/image-stream/handlers.js
lib/image-stream/parse-partitions.js
lib/shared/supported-formats.js
npm-shrinkwrap.json
package.json

This plugin helps us detect some things the built-in jsdoc rules can't,
like whether there is an example or not.
As expected, the addition of this plugin helped detect some minor JSDoc
issues.

chore: add eslint-jsdoc-plugin to eslint

---

lib/gui/etcher.js
npm-shrinkwrap.json
package.json

This version contains various improvements on the drive detection system
mainly on Windows. The improvements can be summarized as follows:
- Drivelist no longer spawns a .bat script to perform its job. This
means that a lot of spawning related issues are now fixed
- Drivelist doesn't fetch drive sizes from WMI anymore, which was known
to incorrectly report a very small size for certain drives, causing
the famous "0.0 GB" Windows issues (see
resin-io-modules/drivelist#142)
- Cleanup temporary scripts after execution
This PR also sets the DRIVELIST_DEBUG environment variable to enable
debug information from Windows' drivelist implementation.
Changelog-Entry: Implement Windows drive detection using C++
Changelog-Entry: Fix various Windows `.bat` spawning issues …

upgrade: drivelist to v5.0.25

---

lib/image-stream/handlers.js

This is a small initial step towards decoupling the image stream
handlers from the concept of a "file."

refactor(image-stream): rename file variable to imagePath

---

Makefile
lib/gui/app.js
package.json

This commit adds a `packageType` property to package.json, which is set
according to the package type of the Etcher target (e.g: dmg, nsis, deb,
etc).
This information is then sent to Mixpanel as the `packageType` property
of the "Application start" event.
Changelog-Entry: Send anonymous analytics about package types.
Fixes: https://github.com/resin-io/etcher/issues/1328

chore: send analytics about package types

---

.travis.yml

Our current Travis CI configuration caches temporary files created by
electron-builder, but only for GNU/Linux builds. In macOS, electron and
electron-builder store their cache at ~/Library/Caches, so we must cache
that as well.
This commit was motivated by the fact that most macOS builds are failing
for Electron package download timeouts.

chore: cache electron-builder temporary files in macOS

---

scripts/build/docker/Dockerfile-i686
scripts/build/docker/Dockerfile-x86_64
scripts/build/docker/Dockerfile.template
scripts/ci/install.sh

This helps reduce a bit of output in the CI servers.

chore: pass --quiet to pip install

---

tests/image-stream/dmg.spec.js

I caught an sporadic issue a couple of times, where the DMG tests would
exceed the default 2000ms mocha timeout. All the other image
decompression tests have a much higher timeout already, so this commit
adds the same timeout to the DMG tests file.

test(image-stream): increase DMG tests timeouts

---

.travis.yml
appveyor.yml

Looks like pkg downloads node binaries from GitHub Releases, and GitHub
may impose a rate limiting if we download too many things from them in a
short period of time (likely to happen when there are many concurrent
PRs).
In order to mitigate this issue, this commit adds `$HOME/.pkg-cache`,
the directory where pkg stores node binaries, to the CI services cache.
See: https://github.com/resin-io/etcher/pull/1594

chore: cache ~/.pkg-cache in Travis CI and Appveyor CI

---

tests/image-stream/archive-hooks/zip.spec.js
tests/image-stream/bz2.spec.js
tests/image-stream/dmg.spec.js
tests/image-stream/gz.spec.js
tests/image-stream/img.spec.js
tests/image-stream/iso.spec.js
tests/image-stream/tester.js
tests/image-stream/xz.spec.js
tests/image-stream/zip.spec.js

The image stream tests that extract images all have a 20s timeout, which
is manually set in all the suites related to extraction.
This commit extracts that number as a constant called DEFAULT_TIMEOUT.
See: https://github.com/resin-io/etcher/pull/1595

test(image-stream): move extraction timeout to a shared constant

---

lib/gui/pages/main/controllers/flash.js

This commit fixes a subtle issue where we are calling a non-existing
function of an error object, instead of using the exception reporter
module.

fix(GUI): incorrect function call in FlashController

---

npm-shrinkwrap.json
package.json

This new version contains the following PRs that we're interested about:
- https://github.com/resin-io-modules/drivelist/pull/196
To reduce the amount of debug logging we produce (see
https://github.com/resin-io/etcher/pull/1600).
- https://github.com/resin-io-modules/drivelist/pull/195
To properly handle spawning EAGAIN errors.
Fixes: https://github.com/resin-io/etcher/issues/1578
Changelog-Entry: Retry various times on EAGAIN when spawning drive scanning scripts.

upgrade: drivelist to v5.0.27

---

electron-builder.yml

Etcher has local native code that gets built to `build/`, but that's not
being included inside the final asar.
The fix is to manually add the `*.node` files inside `build/Release` by
adding the appropriate wilcard to the `files` section of
`electron-builder.yml`.

fix(windows): include local native modules in final asar

---

lib/gui/modules/image-writer.js

Simply running `_.merge` on an Error object results in an empty plain
object `{}` being sent to Mixpanel/Sentry.

fix(GUI): properly pass error object to "Flash error" event

---

npm-shrinkwrap.json
package.json

This version contains a fix to a set of very recurrent "Unmount failed"
macOS errors.
See: https://github.com/resin-io-modules/mountutils/pull/44
Changelog-Entry: Fix most "Unmount failed" errors on macOS.

upgrade: mountutils to v1.2.1

---

lib/image-stream/handlers.js
tests/image-stream/dmg.spec.js

This avoids running into the "flashstate percentage above 100%" error again.
See also: #1572

fix(writer): Use final size if it's not an estimation

---

docs/CONTRIBUTING.md

This adds a reference to the commit guidelines to the contributing guide.
Connects To: https://github.com/resin-io/etcher/issues/1494

doc: Add link to commit guidelines to contributing guide

---

lib/image-stream/gzip.js
lib/image-stream/handlers.js
lib/image-stream/mime.js
lib/image-stream/utils.js

This commit refactors the xz and gzip image handlers to pass/use a
custom read function to be able to determine the uncompressed size, and
other needed metadata.
By using this function (which currently only uses the `fs` module), we
can implement support for getting the uncompressed size of compressed
files using HTTP Ranges.

refactor(image-stream): parse xz and gzip metadata using a custom read function

---

lib/gui/app.js
lib/gui/components/update-notifier.js
lib/gui/models/local-settings.js
lib/gui/models/settings.js
tests/gui/models/settings.spec.js
tests/gui/pages/main.spec.js

This is part of the process of implementing support for a configuration
file. We previously decoupled the Redux store from localStorage by
moving the logic that actually persists the data to localStorage to a
local-settings.js file, however the localStorage API is synchronous, so
it follows that at the moment, all functions that interact with are also
synchronous.
Moving to storing the settings to a file means turning all these
functions to promises, which we do in this commit, in order to not mix
the addition of the configuration file feature with the huge amount of
refactoring it requires.
See: https://github.com/resin-io/etcher/issues/1356

refactor(GUI): make settings model setter asynchronous

---

.travis.yml
Makefile
appveyor.yml
scripts/ci/deploy.sh
scripts/publish/bintray.sh

This commit includes several changes to adapt the CI configuration files
and Bintray publish script to perform development deployments.
- Move our Bintray details to the Makefile
- Deploy to a new Bintray component if `RELEASE_TYPE` is `snapshot`
- Call `publish-bintray-debian` and `publish-bintray-redhat` in the CI
deployment script
- Call the Bintray deployment scripts for RPMs

chore: publish development Bintray packages

---

lib/image-stream/supported.js
tests/shared/supported-formats.spec.js

Support the rpi-sdcard image file type output by Yocto for
the Raspberry Pi device.
Changelog-Entry: Add support for .rpi-sdcard images.

feat: support rpi-sdcard image file type

---

lib/cli/etcher.js
lib/gui/components/drive-selector/templates/drive-selector-modal.tpl.html
lib/gui/modules/drive-scanner.js
lib/gui/pages/main/templates/main.tpl.html
lib/shared/messages.js
npm-shrinkwrap.json
package.json
tests/gui/modules/drive-scanner.spec.js

The `flashComplete` message takes the drive object and the image
basename as arguments. This was updated on the GUI, but causes the CLI
to throw an error upon completion.
Changelog-Entry: Fix "imageBasename is not defined" error on the CLI.

fix(CLI): pass required arguments to flashComplete message

---

lib/gui/components/svg-icon.js
lib/gui/components/svg-icon/styles/_svg-icon.scss
lib/gui/css/main.css
tests/gui/components/svg-icon.spec.js

We make the svg-icon component accept XML in its path argument to handle
archive-embedded SVG icons.
Changelog-Entry: Make archive-embedded SVG icons work again.
Fixes: https://github.com/resin-io/etcher/issues/1636

fix(GUI): make archive-embedded svgs work again

---

lib/gui/components/drive-selector/templates/drive-selector-modal.tpl.html
lib/gui/pages/main/templates/main.tpl.html
lib/gui/utils/byte-size/byte-size.js
lib/gui/utils/byte-size/filter.js
lib/gui/utils/byte-size/filters/closest-unit.js
lib/shared/units.js
npm-shrinkwrap.json
package.json
tests/gui/utils/byte-size.spec.js
tests/shared/units.spec.js

We make the size units used the closest relative unit through a new
filter `closestUnit` replacing the old `gigabyte` filter.
Changelog-Entry: Make the size units the closest relative.

feat(GUI): make size units closest relative

---

lib/shared/permissions.js

Changelog-Entry: Display a user-friendly error message if the user is not in the sudoers file.

fix(GUI): throw a user error if the user is not in the sudoers file

---

npm-shrinkwrap.json
package.json

This version contains the following fixes:
- Fix "Couldn't initialize the scanner: An unknown error occurred" error
- Fix "Couldn't scan the drives: An unknown error occurred" where there
is a mounted virtual drive
See: https://github.com/resin-io-modules/drivelist/blob/master/CHANGELOG.md
Changelog-Entry: Fix various drive scanning Windows errors.
Fixes: https://github.com/resin-io/etcher/issues/1646
Fixes: https://github.com/resin-io/etcher/issues/1639

upgrade: drivelist to v5.1.3

---

lib/shared/s3-packages.js
tests/shared/s3-packages.spec.js

There's not much we can do if we can't connect to S3 to determine the
latest available versions when checking if we should show an update
notification dialog or not.
As with similar errors, lets swallow this particular one, and try again
the next time Etcher runs.
Changelog-Entry: Fix `EHOSTDOWN` error at startup.
Fixes: https://github.com/resin-io/etcher/issues/1645

fix: ignore EHOSTDOWN errors when querying S3

---

lib/gui/app.js
lib/shared/errors.js
lib/shared/s3-packages.js
tests/shared/errors.spec.js
tests/shared/s3-packages.spec.js

We send an HTTP request to S3 to determine the latest available version.
There are various error that can happen that we don't have control over
(like `ETIMEDOUT`).
The current approach is to whitelist certain errors and pretend there is
no update available, however this commit improves that whole situation.
Instead of swallowing these errors, we throw a user error from the
function that determines the latest available version. From the
application code, we check if that function throws a user error, and if
so, instead of showing it to the user, we log a mixpanel event and carry
on.
This change is motivated by the latest reporter error we can't do
anything about: `UNABLE_TO_GET_ISSUER_CERT_LOCALLY`.
Fixes: https://github.com/resin-io/etcher/issues/1525
Changelog-Entry: …

fix(GUI): log known user errors when querying S3 for updates

---

lib/gui/components/svg-icon.js
lib/gui/css/main.css
lib/gui/pages/main/styles/_main.scss
lib/gui/scss/main.scss
tests/gui/components/svg-icon.spec.js

SVGs are displayed through IMG tags, but these do not support CSS
`fill`, and as such we work around it with `opacity`.
Changelog-Entry: Make disabled SVGs work in IMG tags.

fix(GUI): make disabled svgs work in img tags

---

Makefile
scripts/ci/deploy.sh

The CI servers currently call `installers-all` to deploy snapshot
builds, however that target builds the installers, but doesn't call the
phony rules that actually publishes them.

chore: add a publish-all make target

---

Makefile
scripts/publish/bintray.sh

Used to not hardcode the architecture type, and to be able to
conditionally set the Bintray Debian headers.
See: https://github.com/resin-io/etcher/pull/1611#discussion_r131349440

chore: add type option to bintray publish script

---

lib/gui/components/svg-icon.js
tests/gui/components/svg-icon.spec.js

This checks for `parsererror`s in the DOMParser's returned document,
to prevent re-use of the previous image and avoid displaying an error
document in the SVG icon slot.
Connects To: #1642

fix(svg-icon): Handle DOMParser parsererrors

---

lib/gui/etcher.js
lib/gui/index.html
lib/start.js

This disables full wildcard debug output by default now,
leaving the possibility to manually enable debug output
via the `DEBUG` environment variable.

refactor(gui): Only enable full debug output on demand

---

.eslintrc.yml
tests/gui/components/svg-icon.spec.js

We recently adopted the standardjs guidelines ESLint, which doesn't seem
to enforce single quotes, even though the guidelines mention it.
See: https://github.com/resin-io/etcher/pull/1663#discussion_r131623802

chore: enforce single quotes in ESLint

---

lib/gui/app.js
lib/gui/components/update-notifier.js
lib/shared/release.js
tests/shared/release.spec.js
tests/shared/s3-packages.spec.js

As another step towards moving to GitHub Releases, this commit makes the
application care much less about the actual release type of the current
version, instead checking if the application is stable or not, which is
more aligned to what GitHub provides us.

refactor: simplify release type handling within the app

---

.travis.yml

Let's see if we can reduce the time it gets to build and test Etcher on
GNU/Linux.
See: https://giorgos.sealabs.net/docker-cache-on-travis-and-docker-112.html

chore: cache Travis CI docker builds

---

.travis.yml
scripts/publish/bintray.sh

- Bintray deployments are broken because of some bash nested quoting
issue
- Travis CI will attempt to cache Docker layers on macOS
- Docker caches from different architectures will override each other

chore: fix build system

---

npm-shrinkwrap.json
package.json

See https://github.com/resin-io-modules/drivelist/pull/206
Changelog-Entry: Fix "Couldn't scan the drives: An unknown error occurred" error when there is a drive locked with BitLocker.
Fixes: https://github.com/resin-io/etcher/issues/1687

upgrade: drivelist to v5.1.5

---

lib/gui/modules/drive-scanner.js
lib/shared/sdk/index.js
lib/shared/sdk/standard/index.js
npm-shrinkwrap.json
package.json
tests/gui/modules/drive-scanner.spec.js

This is a major first step towards adopting an SDK architecture. This
commit creates an SDK adaptor with a `.scan()` function that uses
`drivelist` under the hood. Then, an SDK orchestrator is used to provide
drive scanning capabilities to the GUI.
Here's a list of some particularly interesting changes:
- The drives returned by the SDK adaptor now have a "pending" and an
"adaptor" property. The "pending" property is a boolean flag that
determines if the drive is ready to be used (this will come handy for
usbboot), while the "adaptor" property simply contains the name of the
adaptor that drive came from
- The GUI drive scanner Rx implementation was replaces with a "promise
loop." Before, the drive scanning routine would be called every 2
seconds (without waiting for the previous scan to …

refactor: use an SDK orchestrator to implement drive scanning

---

tests/shared/models/available-drives.spec.js

The usbboot integration will bring in drive objects that include a lot
more properties than the current drive objects. This commit ensures that
the redux store can handle those extra properties.

test(shared): ensure drive objects can contain extra properties

---

lib/shared/drive-constraints.js
tests/shared/drive-constraints.spec.js

We recently added a "pending" flag to all drives that represents whether
the drive is ready for selection or not. This flag will be used by the
"usbboot" flashing adaptor, which will emit various "pending" USB
devices while it converts them to block devices that can actually be
flashed.
In terms of the GUI, the following visible changes were made:
- Drives with a `pending: true` property will be disabled in the drive
selector window
- Drives with a `pending: true` property have a "PENDING" red badge
See: https://github.com/resin-io/etcher/pull/1707
See: https://github.com/resin-io/etcher/pull/1686

feat(GUI): support new "pending" drive flag

---

Makefile
scripts/build/architecture-convert.sh
scripts/build/docker/Dockerfile-armv7hf
scripts/build/docker/Dockerfile-i686
scripts/build/docker/Dockerfile-x86_64
scripts/build/docker/compile-template.js
scripts/build/docker/run-command.sh

This commit makes use of the `resin/armv7hf-debian` Docker image to
test and generate armhf builds.
We needed to add a slash before `build` in `.gitignore` given that git
was refusing to include any changes on `scripts/build` otherwise.

chore: build armhf on GNU/Linux

---

npm-shrinkwrap.json
package.json

Fixes: https://github.com/resin-io/etcher/issues/1699
Changelog-Entry: Try to use `$XDG_RUNTIME_DIR` to extract temporary scripts on GNU/Linux.

upgrade: drivelist to v5.1.8

---

npm-shrinkwrap.json
package.json

This updates `resin-corvus` to version 1.0.0-beta.29, switching
Mixpanel and Sentry analytics to HTTPS transports.
Changes:
- fix(sentry): Default to HTTPS transport
- fix(mixpanel): Use HTTPS transport
- test: Use standardjs for linting
- doc(README): Add CI & npm badges
- fix(ci): Fix Appveyor Node version matrix
- refactor: Ensure Node 4 compatibility
Connects To: #1718

chore(package): Bump resin-corvus to 1.0.0-beta.29

---

npm-shrinkwrap.json
package.json

See: https://github.com/resin-io-modules/mountutils/pull/45
Changelog-Entry: Retry ejection various times before giving up on Windows.

upgrade: mountutils to v1.2.2

---

Makefile

The current CLI releases are broken. Seems that `pkg` creates the
application snapshot based on the current working directory, so at the
moment, the snapshot gets created based on the root of the project,
rather than based on the dist/Etcher-cli-* directories, causing the
native add-ons to not be resolved correctly.
Fixes: https://github.com/resin-io/etcher/issues/1706

chore: fix CLI packaging snapshot relative directory

---

lib/image-stream/handlers.js

This removes `Bluebird.props()` from the image type handlers,
as it's just a remnant when some properties in the return value
were Promises that needed resolving.
Connects To: #1724

refactor(image-stream): Remove Promise props resolve

---

lib/image-stream/handlers.js
lib/shared/file-extensions.js
lib/shared/store.js
lib/shared/supported-formats.js
tests/shared/file-extensions.spec.js
tests/shared/models/selection-state.spec.js

This allows selection of images without a secondary file extension
(i.e. `example.gz`, compared to `example.img.gz`) by defaulting to `img`
in the image-stream handlers, should no secondary extension be found.
Further this adjusts `.getPenultimateFileExtension()` to return `null`
if the detected penultimate extension is not a known file extension.
Connects To: #1723

fix: Support raw images without secondary file extension

---

npm-shrinkwrap.json
package.json

This fixes RangeErrors occurring with some zip files.
**Changes:**
- Fixed compatibility with node.js v0.10
- Fix error unpacking archives with a special comment
- Fix descriptive error messages
Changelog-Entry: Fix Etcher being unable to read certain zip files
Connects To: #1729

upgrade(node-stream-zip): 1.3.4 -> 1.3.7

---

lib/image-stream/supported.js
tests/shared/supported-formats.spec.js

This adds support for selecting images with a `.bin` file extension.
Connects To: #1739

feat(image-stream): Support .bin image extension

---

npm-shrinkwrap.json
package.json

See: https://github.com/resin-io-modules/drivelist/pull/229
Changelog-Entry: Fix permission denied issues when XDG_RUNTIME_DIR is mounted with the `noexec` option.

upgrade: drivelist to v5.2.4

---

lib/shared/sdk/usbboot/usb.js

fix(sdk): set usbboot control transfer timeout to infinite

---

lib/shared/sdk/usbboot/protocol.js

We experienced timeouts when sending big files (ie ~14 MBs). Setting the
timeout to 0 makes the timeout infinite.

fix(sdk): increase bulk transfer usb timeouts

---

lib/gui/components/progress-button/styles/_progress-button.scss
lib/gui/css/main.css

At the moment the progress button which has slightly rounded corners allows the `__bar` to overflow. This causes the corners to become angular again which looks weird. I set the button's `overflow` to `hidden` to fix this issue.
*I wasn't able to test whether this fixes the issue for sure because I wasn't able to [make the development dependencies work](https://github.com/resin-io/etcher/blob/master/docs/CONTRIBUTING.md#developing) on my machine, but it should work.*

fix(GUI): make sure progress button is always rounded

---

lib/shared/drive-constraints.js
lib/shared/sdk/standard/index.js
lib/shared/sdk/usbboot/index.js
tests/gui/modules/drive-scanner.spec.js
tests/shared/drive-constraints.spec.js

This commit introduces a boolean `disabled` property rather than a
`pending` flag. Making this distinction clearer means that we can now
treat pending drives in different ways needed to improve the usbboot
experience.
Also, for usbboot, this commit removes the "pending" badge and uses a
more descriptive drive description instead.

refactor(GUI): generalize the concept of a "pending" drive

---

lib/gui/components/drive-selector/templates/drive-selector-modal.tpl.html

Some drives, like usbboot USB devices, don't have a size associated with
them, which results in the drive selection widget showing a hyphen with
nothing at the side, which looks a bit weird.

fix(GUI): don't display hyphen in drive selection entry if no size

---

lib/shared/drive-constraints.js
tests/shared/drive-constraints.spec.js

Some devices don't have a size, like USB devices in the usbboot adaptor.
The `.isDriveLargeEnough()` correctly returns `false` in this case,
however we don't want to show the `TOO SMALL` badge for aesthetics
purposes.
So if a drive has a size that equals `null`, we don't allow such drive
to be selected, and we don't show a badge for it.

fix(GUI): don't show the "too small" badge if the size is null

---

lib/shared/sdk/usbboot/index.js

We have a debug message that prints `device.name`, which is not a valid
property, and therefore the debug logs show `undefined` instead of the
USB id pair.

fix(usbboot): opening device debug message prints undefined

---

docs/CONTRIBUTING.md

This adds `libudev-dev` to the list of requirements for Linux in `CONTRIBUTING.md`
Connects To: #1771

doc(CONTRIBUTING): Add libudev requirement to docs

---

docs/CONTRIBUTING.md

This removes a confusing reference to an "install script"
in the dependency section. A change that was forgotten in #1787
Connects To: #1771, #1787

doc(CONTRIBUTING): Remove refence to "install script"

---

lib/shared/sdk/usbboot/index.js

This commit handles errors that can come up when unplugging the drive
halfway through the process. After tons of experimentation, the errors
than seem to occur are:
- `LIBUSB_TRANSFER_CANCELLED`
- `LIBUSB_ERROR_NO_DEVICE`
When these errors happen, we can omit the drive, and also not try to
close it, since given the device is no longer there, the close operation
bails out with a strange error message.
Changelog-Entry: Gracefully handle scenarios where a USB drive is disconnected halfway through the usbboot procedure.

fix(usbboot): handle device disconnections

---

lib/shared/sdk/usbboot/index.js

Consider the following scenario:
- Usbboot runs successfully on a device
- Before the block device gets a chance to appear, we run usbboot again
If we're fast enough, usbboot will try to claim the device interface,
but then the drive might not be there anymore, causing a
`LIBUSB_ERROR_NO_DEVICE`.
This commit addresses that scenario, and simply ignores the drive.
Changelog-Entry: Fix `LIBUSB_ERROR_NO_DEVICE` error at the end of usbboot.

fix(usbboot): handle LIBUSB_ERROR_NO_DEVICE when claiming a USB interface

---

npm-shrinkwrap.json
package.json

This updates resin-corvus to v1.0.0-beta.30, fixing an issue
with attempting to use https transport in browserland.

upgrade(package): Bump resin-corvus to beta.30

---

docs/CONTRIBUTING.md

This adds a small note about setting the `msvs_version`
in the npm config on Windows.

doc(CONTRIBUTING): Add note about msvs_version on Windows

---

lib/shared/sdk/usbboot/index.js

The combination of bus number and device address is the only way to
uniquely identify a USB device, so we'll use that for the `device` and
`raw` properties.
Also, we store the USB vendor and product IDs as properties of the
drives, since they will be handy when implementing the prepare function.

refactor(sdk): add bus number, device address, and ids in usb devices

---

lib/gui/components/drive-selector/styles/_drive-selector.scss
lib/gui/components/drive-selector/templates/drive-selector-modal.tpl.html
lib/gui/css/main.css
scripts/html-lint.js

We show a progress bar for any drive objects with a `progress` field
that isn't falsy, e.g. `undefined` or `0`.
Changelog-Type: minor
Changelog-Entry: Add optional progress bars to drive-selector drives.

feat(GUI): add optional progress bars to drive-selector drives

---

lib/shared/sdk/index.js
lib/shared/sdk/standard/index.js
lib/shared/sdk/usbboot/index.js
tests/gui/modules/drive-scanner.spec.js

This change will allow us to start emitting progress events out of the
adaptors scan functions.

refactor(SDK): make adapter scan functions event based

---

electron-builder.yml
lib/child-writer/renderer-utils.js
lib/child-writer/writer-proxy.js
lib/shared/messages.js
lib/start.js
npm-shrinkwrap.json
package.json

We prompt the user with a sudo-prompt upon launch on Linux-based systems
to ensure the program has enough permissions for features needed
throughout the program's runtime.
Changelog-Entry: Add a sudo-prompt upon launch on Linux-based systems.

feat: add sudo-prompt to start on linux

---

lib/shared/sdk/usbboot/index.js

This commit re-architects the usbboot adapter to prepare the drives in
the background, while emitting scan results every 2s, where each drive
has a `progress` percentage property.

feat(usbboot): add progress property to usbboot scanned drives 

---

lib/shared/sdk/usbboot/index.js

This is a workaround to prevent the USB device from disappearing after
the file server phase, until the resulting block device comes up.
By adding a delay after the file server phase, we prevent the USB
scanner from getting triggered again, therefore keeping the current USB
device visible in the drive selector modal.

style(usbboot): wait before scanning drives after the file server phase

---

Makefile

This adds excludes for .dtb, .dtbo, .dat, .elf, .bin, .foo, and xz-without-extension
to reduce unnecessary warning output in `make lint`.
```
WARNING: Binary file: lib/blobs/usbboot/bcm2709-rpi-2-b.dtb
WARNING: Binary file: lib/blobs/usbboot/bcm2710-rpi-cm3.dtb
WARNING: Binary file: lib/blobs/usbboot/bcm2708-rpi-cm.dtb
WARNING: Binary file: lib/blobs/usbboot/bcm2708-rpi-b.dtb
WARNING: Binary file: lib/blobs/usbboot/bcm2710-rpi-3-b.dtb
WARNING: Binary file: lib/blobs/usbboot/bcm2708-rpi-0-w.dtb
WARNING: Binary file: lib/blobs/usbboot/bcm2708-rpi-b-plus.dtb
WARNING: Binary file: lib/blobs/usbboot/overlays/dwc2.dtbo
WARNING: Binary file: lib/blobs/usbboot/raspberrypi/fixup_cd.dat
WARNING: Binary file: lib/blobs/usbboot/raspberrypi/start_cd.elf
WARNING: Binary file: …
```

test(Makefile): Update codespell excludes

---

lib/gui/components/drive-selector/controllers/drive-selector.js
lib/gui/components/drive-selector/templates/drive-selector-modal.tpl.html
lib/gui/components/svg-icon/styles/_svg-icon.scss
lib/gui/components/warning-modal/templates/warning-modal.tpl.html
lib/gui/css/desktop.css
lib/gui/css/main.css
lib/gui/index.html
lib/gui/os/open-external/directives/open-external.js
lib/gui/pages/main/templates/main.tpl.html
lib/gui/pages/settings/templates/settings.tpl.html
lib/gui/scss/components/_button.scss
lib/gui/scss/main.scss

We make navigating with the tab key easier by highlighting focused
elements more visibly, adding `tabindex` attributes to elements, and
making `open-external` links respond to keyboard events.
Changelog-Entry: Improve tab-key navigation through tabindex and visual
improvements.
Connects-To: #1734

feat(GUI): use tabindex and focus to navigate

---

lib/gui/app.js
lib/gui/index.html
lib/shared/sdk/usbboot/index.js
lib/start.js

We fix the DEBUG environment variable by setting it on the `electron.remote`
instead, and we also move the code to `lib/gui/app.js` and away from
`lib/gui/index.html`.
Changelog-Entry: Set the DEBUG environment variable on the remote
electron process.

fix: set debug env variable on remote electron process

---

scripts/build/docker/Dockerfile-armv7hf
scripts/build/docker/Dockerfile-i686
scripts/build/docker/Dockerfile-x86_64
scripts/build/docker/Dockerfile.template

This works around the "Cannot fetch index base URL http://pypi.python.org/simple/"
error by installing pip==9.0.1 directly from the pypi.python.org/packages/

fix(scripts): Fix pip install in docker

---

lib/gui/pages/main/controllers/flash.js
lib/shared/drive-constraints.js
lib/shared/models/selection-state.js
tests/shared/drive-constraints.spec.js

image.size is always an object, never a plain number

fix: Correct image.size usage in tests and code-comments

---

lib/shared/sdk/usbboot/index.js

Changelog-Entry: Remove duplicate debug enabling in usbboot module.

minifix: remove duplicate debug enable in usbboot

---

lib/cli/options.js

Check for "invalid" CLI options? #1454
Add an options check for the `drive` flag to appear with the `yes` flag. If the `yes` flag appears without the `drive` flag then a user error will be thrown as shown below.
```bash
$ ./bin/etcher -y ~/Downloads/ubuntu.iso
Usage: bin/etcher [options] <image>
Options:
--help, -h     show help  [boolean]
--version, -v  show version number  [boolean]
--drive, -d    drive  [string]
--check, -c    validate write  [boolean] [default: true]
--yes, -y      confirm non-interactively  [boolean]
--unmount, -u  unmount on success  [boolean] [default: true]
Examples:
bin/etcher raspberry-pi.img
bin/etcher --no-check raspberry-pi.img
bin/etcher -d /dev/disk2 ubuntu.iso
bin/etcher -d /dev/disk2 -y rpi.img
Exit codes:
0 - Success
1 - General Error
2 - Validation …
```

Add options check for drive flag with yes flag

---

lib/shared/sdk/index.js

Various GNU/Linux distributions require root access to be able to open
USB devices. This means that Etcher would need to be ran as root, which
is now not possible on Wayland based systems.
We declare usbboot as unsupported on GNU/Linux from the time being, but
we are currently working on a solution.

fix(SDK): disable usbboot adapter on GNU/Linux

---

lib/child-writer/constants.js
lib/child-writer/index.js
lib/child-writer/writer-proxy.js

This adds handling for cases where the writer child process
exits due to reception of a signal, while also adjusting some peripherals,
like the IPC socket directory and inherited process environment.
Another addition is that the child process is explicitly killed
should an error arise on the IPC.
Connects To: #1801
Obsoletes: #1801

fix(child-writer): Handle exits due to a signal

---

lib/child-writer/constants.js

There's a bug in node-ipc which doesn't allow it to handle
tmpdirs without trailing slashes; this works around this bug.
Connects To: #1340 #1690 
Changelog-Entry: Fix "hangs on starting" bug

fix(child-writer): Ensure tmpdir path has trailing slash

---

lib/writer/progress-stream.js

If the speed is zero, the eta becomes Infinity, which isn't transmitted
properly over IPC for at this time unknown reasons.
To prevent the "Missing state eta" error from popping up when the speed is
zero, we set the eta to zero as well in those cases.
Changelog-Entry: Fix "Missing state eta" error when speed is zero

fix(store): Fix "Missing state eta" error on Infinity/NaN

---

lib/gui/modules/drive-scanner.js

Due to the SDK keeping it's options once initialized,
the unsafe mode setting change was not reflected on subsequent scans.

fix(drive-scanner): Dynamically get unsafe mode setting

---

lib/gui/css/desktop.css
lib/gui/css/main.css
lib/gui/scss/main.scss

For the time being, the focus outlines are removed, until
we can improve the UX on this.
Connects To: #1745 #1734 #860

fix(gui): Disable outlines

---

lib/writer/checksum-stream.js
lib/writer/index.js

The checksum-stream being situated in front of the block-stream, which
ensures block size alignment to multiples of 512, and pads the last block,
caused the checksum to be incorrectly calculated for images where the last
block needed to be padded.

fix(writer): Don't calcluate checksum before block-stream

---

lib/writer/index.js

Due to the Blockmap.FilterStream not emitting a "checksum"
event (as it individually verifies specified ranges), the
flashing process would get stuck on finish.
This emits a "checksum" event on "finish" when blockmapping,
averting this issue.

fix(writer): Emit checksum event when verifying bmaps

---

lib/writer/index.js

This fixes read-lengths during verification for images that don't align to a 512 multiple.

fix(writer): Fix verify size for unaligned images

---

npm-shrinkwrap.json
package.json

This fixes pipage blowing up on unbzip2-stream because it's
based on through streams (which don't implement `.unpipe()`),
by utilizing a custom version based on core streams.
Changelog-Entry: Fix bzip2 streaming with the new pipelines

fix(writer): Use a core streams variant of unbzip2-stream

---

lib/child-writer/writer-proxy.js

As we're not escaping env vars properly in `permissions.getEnvironmentCommandPrefix()`,
passing the entire environment along can cause another instance of the "stuck at starting"
problem, thus we limit the vars explicitly passed along again, keeping PATH and DEBUG.
Tested on:
Connects To: #1851

fix(child-writer): Reduce env vars passed during elevation

---

npm-shrinkwrap.json
package.json

This updates `sudo-prompt` from v6.1.0 to v8.0.0
Changes:
- v8.0.0:
- Breaking: Windows: Set code page of command batch script to UTF-8
- v7.1.1:
- readme: explicitly mention that no child process is returned
- v7.1.0:
- Detect when PowerShell fails to launch command
- Escape ampersand and other characters special to PowerShell
- v7.0.0:
- Add status code to error on Windows and macOS
- v6.2.0:
- Rename OS X to macOS
Tested on:

upgrade(package): Bump sudo-prompt 6.1.0 -> 8.0.0

---

lib/writer/block-write-stream.js
lib/writer/index.js

As we've actually been displaying the read-speed in various
forms during the flashing process, this is a venture into
displaying the actual write-speed from the end of the pipeline.
Changelog-Entry: Display actual write speed

feat(writer): Display actual write speed

---

lib/cli/writer.js

We change from using `rs+` to a composition of read/write,
exlusive, sync & direct i/o flags, in order to avoid reading
stale data from the cache during verification.
Tested on:
Connects To: https://github.com/resin-io/etcher/issues/1523
Changelog-Entry: Fix verification step reading from the cache

fix(writer): Set flags manually to avoid verifying cache

---

lib/gui/components/drive-selector/templates/drive-selector-modal.tpl.html

We hide the separator hyphen between the name and size when there is no
size information available, in the drive selector modal.
Changelog-Entry: Hide the drive-selector separator hyphen when no drive
size is available.

minifix: hide drive selector hyphen when no size info

---

versionist.conf.js

There's a commit that slipped in (sorry) with a capitalised
Change-Type value of "Patch". This avoids versionist erroring,
by always lowercasing that value.
Change-Type: PATCH

fix(versionist): Ignore case of Change-Type value

---

npm-shrinkwrap.json
package.json

This version contains a couple of patches to ensure that the Mixpanel
library doesn't send any HTTP request to api.mixpanel.com unless the
user enabled analytics.
- https://github.com/resin-io-modules/resin-corvus/pull/35
- https://github.com/resin-io-modules/resin-corvus/pull/36
See: https://github.com/resin-io/etcher/issues/1772

upgrade: `resin-corvus` to v1.0.0-beta.31

---

lib/gui/app.js
lib/gui/index.html

We load localStorage settings into the Redux store in an asynchronous
way. This means that user settings might not be loaded by the time the
application starts, resulting in Mixpanel sending a few tracking events
before Etcher realises that the user opted out from anonoymous analytics
and error reporting.
In order to fix that, we remove `ng-app` and we manually bootstrap the
Angular.js application *after* the local settings are loaded.
Changelog-Entry: Don't send initial Mixpanel events before "Anonymous Tracking" settings are loaded.
Fixes: https://github.com/resin-io/etcher/issues/1772

fix(GUI): ensure settings are loaded before bootstrapping application

---

lib/writer/block-read-stream.js
lib/writer/block-write-stream.js
lib/writer/error-types.js

This adds write-retries and handling of potentially temporary errors,
as well as errors due to device disconnection.
Connects To: https://github.com/resin-io/etcher/issues/1881
Changelog-Entry: Fix handling of temporary write errors

fix(writer): Add missing write-retry handling

---

appveyor.yml
scripts/ci/build-installers.sh
scripts/ci/deploy.sh
scripts/ci/install.sh
scripts/ci/test.sh

We do this by using Appveyor's `platform` configuration variable instead
of always running on x64 and cross-compiling to x86.

chore(appveyor): build x86 on real x86 machines

---

lib/gui/components/drive-selector/controllers/drive-selector.js

Right now we emit "Toggle drive" analytics events even when clicking on
disable/unselectable drives.
The fix is to move the `analytics.logEvent` inside the code path that
applies if a drive selection is considered valid.
Changelog-Entry: Don't send analytics events when attempting to toggle a disabled drive.

fix(GUI): only emit toggle drive event if drive is selectable

---

Makefile
appveyor.yml
npm-shrinkwrap.json
package.json
tests/spectron/browser-window.js
tests/spectron/runner.spec.js

- Add a `make test-spectron` target
- Install `spectron` and `mocha` (since we don't need to run the tests
inside an Electron instance like in the case of `electron-mocha`)
- Add some example tests
Fixes: https://github.com/resin-io/etcher/issues/1870

chore: setup a Spectron integration test suite

---

npm-shrinkwrap.json
package.json
scripts/clean-shrinkwrap.js

This updates the `postshrinkwrap` script to traverse the dependency tree
and remove all `from` fields to avoid inconsistent diffs across platforms,
environments and installs when shrinkwrapping anew.

refactor(scripts): Update clean-shrinkwrap script

---

lib/writer/block-read-stream.js
lib/writer/block-write-stream.js

This adds minor backoff times to failed reads/writes that fall into the "transient" category, replicating the behavior of etcher-image-write.

feat(writer): Add read/write retry delays

---

npm-shrinkwrap.json

Out of order squash merging resulted in some from-lines
not being removed in the npm-shrinkwrap.

fix(package): Fix noodled merge of shrinkwrap file

---

package.json

Our Electron Concourse pipeline is completely independent from the
application its testing (ie we can apply it to any other Electron app we
build with ease).
In order to keep such genericity, the application under test should
provide certain npm scripts that tell Concourse how to do specific tasks
on the repo, like install dependencies, in a build-system independent
fashion.

chore: add Concourse related NPM scripts

---

package.json

The idea is that the `test` command will replace the recently introduced
`concourse-test` script.
`concourse-test` will become simply a call to `test` for now to ensure
backwards compatibility while we update Resin Concourse.

chore: make `test` npm script run everything we run on the CI services

---

package.json

Resin Concourse will make sure to provide these during build time.

chore: declare Concourse dependencies in package.json

---

lib/gui/modules/image-writer.js
lib/gui/pages/main/controllers/flash.js
lib/gui/pages/main/main.js
tests/gui/modules/image-writer.spec.js

We remove Angular from the `image-writer` module by using Redux store
updates, subscribing to them while flashing.
Changelog-Entry: Remove Angular dependency from image-writer.

feat(GUI): remove angular from image-writer

---

lib/shared/permissions.js
tests/shared/permissions.spec.js

This is a strange one. On Windows, putting a space before the
double-ampersand command concatenator makes the environment variable
value contain a trailing space. So for something like `set foo=bar &&
...` the variable `foo` will be `'bar '` instead of `'bar'`.
Changelog-Entry: Fix trailing space in environment variables during Windows elevation.

fix(shared): trailing space in Windows elevation env vars

---

npm-shrinkwrap.json
package.json

This version of drivelist also includes the perl-fix, which was causing high CPU load occasionally.
Connects To: #1288

upgrade(package): Bump drivelist 5.2.4 -> 5.2.12

---

npm-shrinkwrap.json
package.json

Electron changelog:
- Fixed crash in custom protocols
- Fixed webrtc crash
- Linux: Fixed subpixel font rendering with freetype
- Mac OS: Fixed rendering issues with Nvidia GPU on High Sierra
- Mac OS: Fixed incorrectly cropped TouchBar items

upgrade(package): Bump electron 1.7.9 -> 1.7.10

---

lib/gui/app.js
lib/gui/etcher.js
lib/gui/menu.js

This re-enables the application menu to allow for OS native shortcuts
to work again (i.e. hide/minimize window), which also allows us to
get rid of the global-shortcuts hack to prevent window reloads.
Also adds links to the website, Etcher Pro and GitHub issues in the help menu.
Menu:
- App (Mac OS): Quit, hide / show window, preferences
- App (Windows, Linux): Quit, preferences
- View: Enable showing DevTools without that global shortcut hack, disable content zoom and reloads
- Edit: Don't disable native copy/paste & shortcuts (needed in DevTools and when we'll add an "Open URL" etc)
- Window: Native window management shortcuts, like minimize / maximise and friends (dep. on OS)
Default state:
When hitting <kbd>Alt</kbd>:
Default state:
When hovering over the menu bar:
Connects To: #1883 …

fix(gui): Re-enable application menu

---

lib/gui/modules/child-writer.js
lib/gui/modules/image-writer.js

This was causing the stdout maxBuffer size to be exceeded
when flashing larger images (or having flashes that took a while).
Changlog Entry: Fix "stdout maxBuffer exceeded" error on Linux
Connects To: #1955

fix(writer): Silence IPC output on stdout

---

npm-shrinkwrap.json

The shrinkwrap still contained the commit hash of a commit
previous to an npm install bugfix

fix(shrinkwrap): Update unbzip2-stream branch commit

---

npm-shrinkwrap.json
package.json

Looks like this will fix an issue where the `electron-mocha` main
process fails with an EPERM error on Windows, which we've been
experiencing on our Concourse setup.
See: https://github.com/jprichardson/electron-mocha/issues/119

upgrade: `electron-mocha` to v5.0.0

---

lib/shared/sdk/usbboot/usb.js

Due to some Windows systems missing certain C runtime libraries
(Visual C/C++ 2012 / 2015 Redistributables), we ignore errors when loading
this module until we can ensure distribution of those along with it.
Changelog-Entry: Fix "The specified module could not be found" on Windows
Connects To: #1956

fix(usb): Ignore errors if winusb doesn't load

---

npm-shrinkwrap.json
package.json

This updates `drivelist` to v6.0.4, fixing a crash on Windows 7,
among other things:
- Fix(windows): Impl IsSystemDevice()
- Fix crash on Windows 7
- Fix(darwin): Use proper flag to enable extended regexes in `sed`
- Fix(darwin): Allow mountpoints containing space characters
Changelog-Entry: Fix Etcher not working / crashing on older Windows systems
Connects To: https://github.com/resin-io/etcher/issues/1971, https://github.com/resin-io/etcher/issues/1288

upgrade(package): Bump drivelist 6.0.0 -> 6.0.4

---

lib/gui/os/dialog.js

This fixes selection of images contained in directories with a file extension
(i.e. "openSUSE-Leap-42.3-DVD-x86_64.iso") in the open file dialog.
Changelog-Entry: Fix selection of images in folders with file extension
Connects To: https://github.com/resin-io/etcher/issues/1926

fix(gui): Allow selection of images in folders with extension

---

.resinci.json

This represents the Node.js version that will be used to compile the
Etcher CLI.

chore: add node-cli.node Resin CI option

---

npm-shrinkwrap.json
package.json

This updates `mountutils` from 1.3.8 -> 1.3.10;
- fix(linux): Fix partial unmounts on Linux
- fix(windows): Link to appropriate libraries
Changelog-Entry: Fix incomplete unmounts after flashing on Linux
Connects To: https://github.com/resin-io/etcher/issues/1911

upgrade(package): Bump mountutils 1.3.8 -> 1.3.10

---

lib/shared/drive-constraints.js
lib/shared/sdk/usbboot/index.js
lib/shared/store.js
tests/shared/drive-constraints.spec.js
tests/shared/models/available-drives.spec.js
tests/shared/models/selection-state.spec.js

This fixes the camelcasing of the `.isReadOnly` property
of detected storage devices.

fix(lib): Fix readonly property typo

---

npm-shrinkwrap.json
package.json

This updates Electron to v1.7.11, mitigating CVE-2018-1000006.
Note: As we don't use custom protocol handlers, Etcher is not vulnerable at this time.
See: https://electronjs.org/blog/protocol-handler-fix
Changelog-Entry: Update Electron to v1.7.11

upgrade(package): Update electron 1.7.10 -> 1.7.11

---

Makefile
package.json

- The `concourse-dependencies` and `concourse-build-installers` scripts
are not necessary anymore, given that the Electron pipeline already
knows how to perform these tasks
- The `concourse-test` script will be renamed to
`concourse-test-electron` to include the pipeline name (electron), so a
single project can be served by more than one pipeline. I'll keep the
old `concourse-test` for a bit for backwards compatibility until all
Etcher PRs are rebased
- There is a new `concourse-test-node-cli` script that will be used by
the Node.js CLI pipeline
- There is a new `test-cli` target that is supposed to host CLI tests.
For now, it just runs the SDK tests in a Node.js environment (instead of
in Electron)

chore: revise Concourse CI related npm scripts

---

Makefile
patches/lzma-native-index-static-addon-require.patch

So that the build system doesn't need to know in advance at which
directory the paths needs to be applied.
This will make it easier to add patches support to the Concourse
pipelines.

chore: encode complete paths to patched file in patches/

---

npm-shrinkwrap.json
package.json

This updates `debug` to 3.1.0 due to a RegExp DOS vulnerability.

upgrade(package): Bump debug 2.6.8 -> 3.1.0

---

lib/gui/menu.js

This replaces use of `electron.app.getName()` with the package.json's `.displayName`
property to ensure the correct application name is displayed when packaged.

fix(gui): Fix menu's application name

---

lib/gui/index.html

We specify the encoding to be UTF-8 with a meta tag such that Electron
won't get confused and try any other encodings.
Changelog-Entry: Specify UTF-8 encoding with meta tag.

fix: specify utf-8 encoding with meta tag

---

lib/cli/options.js
npm-shrinkwrap.json
package.json

This updates `yargs` to 11.0.0, while also fixing #1452:
Before:
```
$ ELECTRON_RUN_AS_NODE=1 node_modules/.bin/electron lib/cli/etcher.js
Usage: node_modules/electron/dist/Electron.app/Contents/MacOS/Electron lib/cli/etcher.js [options] <image>
Options:
--help, -h     show help  [boolean]
--version, -v  show version number  [boolean]
--drive, -d    drive  [string]
--check, -c    validate write  [boolean] [default: true]
--yes, -y      confirm non-interactively  [boolean]
--unmount, -u  unmount on success  [boolean] [default: true]
Examples:
node_modules/electron/dist/Electron.app/Contents/MacOS/Electron lib/cli/etcher.js raspberry-pi.img
node_modules/electron/dist/Electron.app/Contents/MacOS/Electron lib/cli/etcher.js --no-check raspberry-pi.img …
```

upgrade(package): Update yargs 4.7.1 -> 11.0.0

---

.editorconfig
.github/ISSUE_TEMPLATE.md

This updates the instructions to open the Developer Tools in the issue template,
as the keyboard shortcuts have changed to their defaults on Linux & Windows
from <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>I</kbd> to <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>.
Further, the editor config is updated to allow trailing spaces in Markdown
files to add trailing spaces to the list items in the issue template, in
order to avoid people not putting whitespace in between, causing the formatting
to not be parsed properly.
Connects To: https://github.com/resin-io/etcher/issues/2001
See also: https://github.com/resin-io/etcher/pull/1997

doc(github): Update instructions in ISSUE_TEMPLATE

---

lib/gui/app/index.html

We move the `tabindex` attributes to the button element directly from
elements contained within the button element – this is to satisfy the
HTML linter.
Changelog-Entry: Move tabindex attributes to button elements from
contained elements.

fix: move tabindex attrs to button from within

---

lib/gui/app/pages/main/controllers/main.js
lib/gui/app/pages/main/templates/main.tpl.html
lib/shared/drive-constraints.js

We add an icon next to the drive size that is displayed when there is a
drive-image compatibility status message available. We display the first
one in the list and importance is then enforced by the order they are
added to the list in `drive-constraints`.
Changelog-Entry: Add icon next to drive size when compatibility warnings exist.

feat: add icon next to drive on warnings

---

lib/gui/menu.js

This adds a `ref` param to the URLs in the menu,
in order to see where page views are coming from.

feat(gui): Add ref params to homepage links in menu

---

lib/gui/app/pages/main/templates/main.tpl.html

We replace `ng-show/hide` with `ng-if` on the main page in order to
remove unnecessary calls and become more efficient.
Changelog-Entry: Replace ng-show/hide with ng-if on main page.

feat(GUI): replace ng-show and ng-hide with ng-if

---

lib/image-stream/handlers.js
npm-shrinkwrap.json
package.json

This updates `udif` to v0.13.0:
**v0.13.0:**
- fix(readstream): Use strict mode for compat with Node 4
- refactor(lib): Improve & fix zerofill streaming
- test: Add passthrough to check for read/push after EOD
- test: Add compression method tests
- feat(udif): Add LZFSE compression type constant
- fix(readstream): Fix passing on readable stream options
**v0.12.0:**
- feat(image): Support use of custom `fs` instances
- feat(readstream): Stream ZEROFILL & FREE blocks
Fixes a buffer allocation failure on large zerofill ranges.
Changelog-Entry: Fix "Array buffer allocation failed" when flashing some .dmg images

upgrade(package): Update udif 0.10 -> 0.13

---

lib/gui/app/components/drive-selector/controllers/drive-selector.js
lib/gui/app/pages/main/controllers/drive-selection.js
lib/gui/app/pages/main/controllers/image-selection.js
lib/shared/models/selection-state.js
lib/shared/store.js
tests/gui/pages/main.spec.js
tests/shared/models/available-drives.spec.js
tests/shared/models/selection-state.spec.js

We rename functions in `selection-state` and the `store`.
Changelog-Entry: Rename selection-state and store functions.

refactor: rename selection state and store functions

---

npm-shrinkwrap.json
package.json
tests/image-stream/tester.js

This removes unnecessary or unused dependencies; `trackjs` hasn't been in use for a very long time, and `file-exists` was a single use dependency, which can be replaced with a single line of code.

chore(package): Remove unnecessary deps

---

lib/gui/app/modules/image-writer.js

This increases the UV_THREADPOOL_SIZE to CPUs * 4 to
facilitate full write speeds when writing to multiple destinations,
in preparation for integrating multi-writes.
Changelog-Entry: Increase UV_THREADPOOL_SIZE to allocate 4 threads per CPU

feat(writer): Increase UV_THREADPOOL_SIZE

---

lib/gui/app/app.js
lib/gui/app/components/drive-selector/services/drive-selector.js
lib/gui/app/components/modal/services/modal.js
lib/gui/app/components/progress-button/directives/progress-button.js
lib/gui/app/components/tooltip-modal/services/tooltip-modal.js
lib/gui/app/components/warning-modal/services/warning-modal.js
lib/gui/app/pages/finish/finish.js
lib/gui/app/pages/main/main.js
lib/gui/app/pages/settings/settings.js
scripts/ci/ensure-all-node-requirements-available.sh
tests/gui/components/modal.spec.js
tests/gui/pages/finish.spec.js
tests/gui/pages/main.spec.js
tests/gui/pages/settings.spec.js

We replace the `templateUrl` fields with `template` fields and thus
switch from template paths to template contents in preparation for the
Webpack PR.
Changelog-Entry: Replace template paths with template contents.

feat: replace template paths with contents

---

npm-shrinkwrap.json
package.json

This relates to building on ARM, which apparently works with the latest node-sass without any issues.

upgrade(package): Update node-sass 4.5.3 -> 4.7.2

---

lib/shared/store.js

We remove a piece of code checking whether `_.keys` returns any non-string
values in its array, but per the Lodash documentation `_.keys` always returns an
array of strings.
Changelog-Entry: Remove stale `invalidKey` check in store.

refactor: remove stale invalid key check in store

---

Makefile
scripts/build/architecture-convert.sh

This adds support for 64bit arm cpu architectures.
Changelog-Entry: Support building Etcher on armv8

fix(Makefile): Support arm64 / armv8 / aarch64

---

lib/cli/writer.js

This removes O_DIRECT and O_EXCL flags from the writer,
as O_DIRECT can lead to EINVAL under quite a few circumstances,
and O_EXCL has proven to be useless.

fix(cli): Remove O_DIRECT & O_EXCL

---

lib/gui/app/components/drive-selector/templates/drive-selector-modal.tpl.html
lib/gui/app/scss/components/_button.scss
lib/gui/app/scss/modules/_theme.scss
lib/gui/css/main.css

We make the drive-selector button orange when there is a warning attached
to the image-drive pair.
Changelog-Entry: Make the drive-selector button orange on warnings.

feat(GUI): warning makes drive-selector button orange

---

lib/gui/app/components/drive-selector/templates/drive-selector-modal.tpl.html
lib/gui/app/scss/components/_label.scss
lib/gui/css/main.css

We make all tags with `.label` have bold text and remove the need for
`<b>` tags.
Changelog-Entry: Make all `.label` tags' text bold and remove need for `<b>` tags.

fix(GUI): make all class label text bold

---

lib/gui/app/components/drive-selector/controllers/drive-selector.js
lib/shared/drive-constraints.js
lib/shared/messages.js
lib/shared/store.js
tests/shared/drive-constraints.spec.js
tests/shared/models/available-drives.spec.js

We warn the user when they select a large drive to confirm they want to
flash in case the device is important.
Fixes: https://github.com/resin-io/etcher/issues/1916
Changelog-Entry: Warn the user on selection of large drives.

feat(GUI): warn the user on large drive selection

---

lib/gui/app/components/svg-icon.js
lib/gui/app/index.html
lib/gui/app/pages/finish/templates/success.tpl.html
lib/gui/app/pages/main/templates/main.tpl.html
tests/gui/components/svg-icon.spec.js

We separate the SVG component path and content into attributes
`paths` and `contents` which take lists of strings that are
tried until one succeeds. `contents` takes precedence over `paths`,
i.e. it is tried first.
Changelog-Entry: Separate SVG component's path and content attributes.

feat(GUI): separate svg path and content attributes

---

lib/cli/diskpart.js
npm-shrinkwrap.json
package.json

This replaces shelling out to `diskpart` on Windows to clear
the partition table with `win-drive-clean`, which does so via DeviceIoControl.
**TODO:**
Changelog-Entry: Use native code to clean drives on Windows
Connects To: #1793 #1991

feat(lib): Use win-drive-clean instead of diskpart

---

lib/shared/store.js
tests/shared/models/flash-state.spec.js
tests/shared/models/selection-state.spec.js

We make the nil-checking of store state fields generic through a
`verifyNoNilFields` function that throws an error if any fields are
nil.
Changelog-Entry: Consolidate store state nil-checking with helper
function.

refactor: consolidate store-state nil-checking

---

lib/gui/app/components/drive-selector/templates/drive-selector-modal.tpl.html
lib/gui/app/scss/components/_label.scss
lib/gui/css/main.css

We add a right margin to the drive-selector labels so they look nicer
when there are multiple.
Changelog-Entry: Add spacing to the drive-selector warning/error labels.

feat(GUI): add spacing to drive-selector labels

---

lib/gui/app/pages/finish/controllers/finish.js
lib/shared/models/selection-state.js
tests/shared/models/selection-state.spec.js

We refactor and simplify the selection-state `.clear()` by removing the
options argument.
Changelog-Entry: Remove `selectionState.clear()` options argument to
simplify.

refactor(GUI): remove selection-state clear options to simplify

---

package.json

This adds `fsevents` to the platform specific dependencies,
in order to avoid shrinkwrap disagreements between platforms.

fix(package): Add fsevents to platform specific deps

---

Makefile

The devel channels will be completely deprecated. The deb/rpm snapshot
builds will still be accessible through GitHub Releases as part of Resin
CI builds.

chore: only publish production packages to Bintray

---

lib/gui/app/components/drive-selector/controllers/drive-selector.js
lib/gui/app/components/drive-selector/templates/drive-selector-modal.tpl.html
lib/gui/app/pages/finish/controllers/finish.js
lib/gui/app/pages/main/templates/main.tpl.html
lib/shared/models/selection-state.js
lib/shared/store.js
tests/shared/models/available-drives.spec.js
tests/shared/models/selection-state.spec.js

We lay the foundation for multi-selecting drives by implementing it into
the `store` and relevant modules interacting with the `store`.
Changelog-Entry: Add drive multi-selection to the store.

feat: add drive multi-selection in store

---

lib/cli/writer.js
lib/sdk/writer/index.js

This moves the preparation logic from the CLI into the SDK
in preparation for further SDK rearchitecturing, and to allow
standalone usage of SDK.
Things this will do / make easier:
- Move towards standalone use capability of the Etcher SDK, which in turn facilitates continuous flashing with a persistent child process (see https://github.com/resin-io/etcher/issues/1805), and also elevation-at-startup to re-enable USBBoot on Linux
- Control multiple write processes with less hassle (i.e. for https://github.com/resin-io/etcher/issues/267)
- Facilitate the move to source & destination for creating backups, network streaming etc. (https://github.com/resin-io/etcher/issues/1804, https://github.com/resin-io/etcher/issues/950, https://github.com/resin-io/etcher/issues/1093) …

feat(sdk): Move CLI writer logic into SDK writer

---

lib/shared/store.js

We add the missing `name` parameter to the `verifyNoNilFields` JSDoc
example.
Changelog-Entry: Add missing name param to verifyNoNilFields JSDoc example.

minifix: add missing parameter to verifyNoNilFields example

---

lib/sdk/writer/index.js

This fixes a missing error argument being passed in .emit()
Connects To: https://github.com/resin-io/etcher/issues/1990, https://github.com/resin-io/etcher/issues/1697

fix(image-writer): Fix missing error argv

---

npm-shrinkwrap.json
package.json

This updates `resin-cli-visuals` in order to fix drive selection in
the CLI, which was caused by incompatibility of two different `drivelist` versions
Connects To: #1990, #1697

upgrade(package): Update resin-cli-visuals to 1.4.1

---

npm-shrinkwrap.json
package.json
tests/shared/models/available-drives.spec.js

**Updated:**
- electron-mocha 5.0.0 -> 6.0.1
- eslint-plugin-import 2.8.0 -> 2.9.0
- eslint-plugin-jsdoc 3.3.1 -> 3.5.0
- eslint-plugin-node 6.0.0 -> 6.0.1
- html-angular-validate 0.1.9 -> 0.2.3
- mocha 3.2.0 -> 5.0.1
- mochainon 1.0.0 -> 2.0.0
- nock 9.0.9 -> 9.2.3
- sass-lint 1.10.2 -> 1.12.1
**Outdated, not updated:**
- eslint 4.17.0 -> 4.18.1 – Invalid peer-dep error
- eslint-config-standard 10.2.1 -> 11.0.0 – has peer-dep on eslint@4.18.1
- versionist 2.8.1 -> 2.13.0 – causes shrinkwrap issues due to git dependency

upgrade(package): Update test related dependencies

---

lib/gui/app/components/drive-selector/controllers/drive-selector.js
lib/shared/utils.js
tests/gui/components/drive-selector.spec.js
tests/shared/utils.spec.js

We move the memoize function to `lib/shared/utils.js` and expose it to
modules across the project.
Changelog-Entry: Move memoize function to shared utils.

refactor: move memoize function to shared utils

---

lib/cli/etcher.js
lib/cli/writer.js
lib/sdk/writer/checksum-stream.js
npm-shrinkwrap.json
package.json

As crc32-stream was identified as a massive performance bottleneck,
we remove it, and default to Node's crypto API with md5 instead.

fix(perf): Remove support for CRC32 checksumming

---

lib/gui/app/pages/main/templates/main.tpl.html

We use a list instead of element with `svg-icon` in `main.tpl.html`, as
required by the `svg-icon` component and will return an error
otherwise.
Fixes: https://github.com/resin-io/etcher/issues/2078
Changelog-Entry: Use SVG contents list in main template.

minifix: use svg contents list in main template

---

lib/gui/app/modules/progress-status.js
lib/gui/app/os/window-progress.js
lib/gui/app/pages/main/controllers/main.js
lib/gui/app/pages/main/styles/_main.scss
lib/gui/app/pages/main/templates/main.tpl.html
lib/gui/css/main.css
lib/shared/messages.js
lib/shared/models/flash-state.js
lib/shared/store.js
tests/gui/modules/progress-status.spec.js
tests/gui/os/window-progress.spec.js
tests/shared/models/flash-state.spec.js

We add colorised progress status dots with quantities of `flashing`,
`validating`, `succeeded`, and `failed` devices.
Changelog-Entry: Add colorised multi-writes progress status dots.

feat(GUI): add colorised multi-writes progress status dots

---

lib/gui/etcher.js

This disables Electron throttling timers when not in the foreground.

fix(gui): Disable throttling timers when in background

---

lib/shared/store.js

We fix store autoselection, which selects an empty value when one
drive is selected and then ejected, leaving one drive that is
supposed to be autoselectable. Now it instead properly autoselects the
last drive.
Changelog-Entry: Stop store autoselection from selecting empty values on
drive ejection.

fix: stop autoselecting empty value in store

---

lib/gui/app/components/drive-selector/templates/drive-selector-modal.tpl.html
lib/gui/app/modules/drive-scanner.js

This re-enables the usbboot scanner dynamically if Etcher
is run as root on Linux.

fix(scanner): Enable usbboot on Linux if run as root

---

lib/shared/drive-constraints.js
lib/shared/messages.js
tests/shared/drive-constraints.spec.js

This adds a display of the determined image size to the
drive label when the drive has been determined to be too small.
Changelog-Entry: Display image size in drive selector if drive is too small
Connects To: #1136, https://github.com/resin-io/etcher/issues/2004

feat(gui): Display image size when drive too small

---

electron-builder.yml

We disable `npm rebuild` and `node-gyp rebuild` being run through
`electron-builder`, as we already rebuild native bindings against
the respective CPU arch through `make electron-develop`, and
electron-builder doesn't appear to respect package's install / rebuild scripts.

fix(windows): Disable rebuilding bindings in electron-builder

---

lib/gui/app/modules/drive-scanner.js

We use the `app.asar` relative path to read the usbboot blob files
instead of relative to the normal project root.
Changelog-Entry: Use correct usbboot blob path in AppImages.

fix: use correct usbbot blob path in appimages

---

lib/gui/app/pages/main/main.js
lib/gui/app/pages/main/templates/main.tpl.html
lib/gui/app/utils/middle-ellipsis.js
lib/gui/app/utils/middle-ellipsis/filter.js
npm-shrinkwrap.json
package.json
tests/gui/utils/middle-ellipsis.spec.js

We remove our dependency on the `middle-ellipses` package and include
and expose the function in `lib/shared/utils`, alongside the regular
Angular filter it exposes. This allows use of the middle ellipsis
method in React.
Changelog-Entry: Inline middle-ellipsis package as util.

refactor: inline middle-ellipsis package as util

---

lib/gui/app/pages/main/styles/_main.scss
lib/gui/css/main.css

We line wrap the main-page image and drive size labels as a whole
instead of partially, if the drive or image title is long enough for a
line wrap.
Changelog-Entry: Line wrap selector size subtitles wholly

fix(GUI): line wrap selector size subtitles wholly

---

lib/gui/app/pages/main/templates/main.tpl.html

We hide the size label when there are multiple selected devices, as this
doesn't make sense because you could only logically show the sum size,
which isn't very helpful on its own.
Changelog-Entry: Hide the size label given multiple devices.

fix(GUI): hide the size label given multiple devices

---

scripts/html-lint.js

This avoids a new error from `html-lint` about the "lang" attr
on `<html>` tags, which isn't applicable to templates.
Depends On: #2167

fix(lint): Fix html-lint error about "lang" attr

---

lib/gui/app/app.js
lib/shared/models/flash-state.js
lib/shared/store.js
tests/gui/pages/main.spec.js
tests/shared/models/flash-state.spec.js

We expose all the flash state fields to the store, and mirror
`speed`'s format with `totalSpeed` with MB as the size unit.
We also format the progress state messages to use information
available with multiwrites.
Changelog-Entry: Expose all flash state fields to the store.

feat: expose all flash state fields to the store

---

npm-shrinkwrap.json
package.json

This updates Electron to v1.7.13 in order to mitigate 2 vulnerabilities:
[CVE-2018-1000136] and [CVE-2018-1000118]
[CVE-2018-1000136]: https://nvd.nist.gov/vuln/detail/CVE-2018-1000136
[CVE-2018-1000118]: https://nvd.nist.gov/vuln/detail/CVE-2018-1000118
Changelog-Entry: Update Electron to v1.7.13

upgrade(package): Bump Electron to v1.7.13

---

lib/sdk/writer/index.js

This fixes a bug where succeeded flashes could become negative due to
improper math

fix(writer): Fix succeeded flash count in progress state

---

lib/gui/app/modules/image-writer.js

Due to improper command escaping, cmd metacharacters lead to failure
in spawning the child writer process on Windows when the entire environment
is passed through the command line. The user's environment will still
be inherited by default on Windows.

fix(image-writer): Don't inherit environment on Windows

---

CHANGELOG.md
docs/MAINTAINERS.md
lib/gui/app/components/modal/styles/_modal.scss
lib/shared/models/selection-state.js
requirements.txt
tests/gui/components/svg-icon.spec.js
tests/shared/errors.spec.js

This updates codespell, and fixes new spelling error detections
```
lib/shared/models/selection-state.js:377: Unselect  ==> Deselect
lib/gui/app/components/modal/styles/_modal.scss:72: programatically  ==> programmatically
tests/shared/errors.spec.js:88: prioritise  ==> prioritize
tests/shared/errors.spec.js:94: prioritise  ==> prioritize
tests/shared/errors.spec.js:100: prioritise  ==> prioritize
tests/gui/components/svg-icon.spec.js:100: prioritise  ==> prioritize
docs/MAINTAINERS.md:19: artefacts  ==> artifacts
docs/MAINTAINERS.md:21: artefacts  ==> artifacts
docs/MAINTAINERS.md:25: artefacts  ==> artifacts
docs/MAINTAINERS.md:36: artefacts  ==> artifacts
docs/MAINTAINERS.md:96: artefacts  ==> artifacts
docs/MAINTAINERS.md:147: artefacts  ==> artifacts
CHANGELOG.md:492: interferring …
```

test(lint): Update codespell 1.11.0 -> 1.12.0

---

lib/gui/app/components/drive-selector/controllers/drive-selector.js
lib/gui/app/components/drive-selector/drive-selector.js
lib/gui/app/components/warning-modal/styles/_warning-modal.scss
lib/gui/app/pages/main/controllers/flash.js
lib/gui/app/pages/main/main.js
lib/gui/css/main.css

We move the drive selector warning to the flash step, and concatenate
warning messages when more than one needs to be displayed at once.
Changelog-Entry: Move the drive selector warning dialog to the flash step.

feat(GUI): move drive selector warning to flash step

---

lib/gui/app/pages/main/styles/_main.scss
lib/gui/css/main.css

This forces the image and device size to always be displayed on the
second line for visual consistency.

fix(gui): Ensure image/drive size displayed on new line

---

lib/shared/store.js
tests/shared/models/flash-state.spec.js

We replace the `_.identity` predicate with `_.isFinite` to ensure
the flash quantity fields are numbers.
Changelog-Entry: Ensure flash quantity fields are finite.

fix: ensure flash quantity fields are finite

---

lib/sdk/writer/index.js
lib/sdk/writer/progress-stream.js

This force-defaults the individual stream speeds to zero,
in order to avoid null values when not available yet.

fix(writer): Fix writer progress state values

---

lib/cli/etcher.js
lib/gui/app/modules/image-writer.js
lib/gui/app/modules/progress-status.js
lib/gui/modules/child-writer.js
lib/sdk/writer/index.js

This fixes the use and handling of events in the write pipeline,
such that the pipeline would not be prematurely stalled or terminated.
Also, a new `fail` event is introduced, to signal non-fatal errors.

fix(writer): Fix erronous event handling in write pipeline

---

.resinci.json

This will ensure we have all bindings built, even when using cached
modules.

Enable nodeGypRebuild for Etcher builds

---

README.md

This removes the "mac" from the Travis CI badge label, as we're not
running Mac OS builds on Travis CI anymore.
Change-Type: none
Connects To: https://github.com/resin-io/etcher/issues/2168

doc(README): Remove Mac OS from Travis CI badge label

---

webpack.config.js

Due to properties being added to the `package.json` when building binaries, it needs to be excluded from the webpack bundle, as these added properties will not be available to it at runtime otherwise.

fix(webpack): Exclude package.json from UI bundle

---

lib/gui/app/pages/main/styles/_main.scss
lib/gui/app/pages/main/templates/main.tpl.html
lib/gui/css/main.css
lib/shared/messages.js
lib/shared/models/flash-state.js

We remove usage of the status dots except when failed devices occur, in
which case we still display the red failed dot and quantity. We also use
singular and plural depending on the quantity of failed devices.

feat(GUI): remove unnecessary status dots

---

lib/gui/app/pages/main/controllers/drive-selection.js
tests/gui/pages/main.spec.js

Change the `Multiple Devices (n)` label on selected devices to a
quantity-prefixed form `n Devices`.

minifeat(GUI): prefix multiple devices label with quantity

---

lib/gui/modules/child-writer.js
lib/shared/errors.js
tests/shared/errors.spec.js

This fixes transmission of user errors over IPC, as the `report`
property was previously missing. Further it also adds more properties
to `errors.toJSON`, like `syscall`, `errno`, etc. and re-uses the method
for failure signalling.

fix(child-writer): Fix handling of user errors over IPC

---

scripts/build/docker/Dockerfile-armv7hf
scripts/build/docker/Dockerfile-i686
scripts/build/docker/Dockerfile-x86_64
scripts/build/docker/Dockerfile.template

The pip tarball URL now redirects to another location, which
caused `curl` to fail, as the follow-redirects option wasn't specified.

fix(ci): Fix pip installation

---

npm-shrinkwrap.json
package.json

This fixes a ReferenceError that could occur when the DeviceNode was null,
as well as devices being null when run after the system recovers from sleep / standby.

upgrade(package): Update drivelist 6.1.5 -> 6.1.7

---

lib/sdk/adapters/blockdevice/index.js

This force-ignores RAID attached devices, to ensure they aren't flashed, not even intentionally,
as that can have yet unknown consequences.
Changelog-Entry: Exclude RAID devices from drive selection list
Connects To: https://github.com/resin-io/etcher/issues/2071

fix(adapters): Always ignore RAID attached devices

---

lib/gui/app/pages/main/controllers/drive-selection.js
tests/gui/pages/main.spec.js

We fallback to `'Untitled Device'` when the device lacks a
`.description` field.
Changelog-Entry: Display Untitled Device when the device lacks a
description field.

fix(GUI): display untitled device when device lacks description

---

lib/gui/app/modules/image-writer.js

`_.isError()` returns `true` for anything that has a `name` and `message`
property, causing the check here to always keep the plain object as error.

fix(image-writer): Remove use of _.isError

---

lib/gui/app/modules/drive-scanner.js

This fixes the usbboot blobs path when the application is bundled & packaged.
Change-Type: fix
Changelog-Entry: Fix usbboot blob loading
Connects To: #2197

fix(drive-scanner): Fix usbboot blob path when bundled

---

lib/cli/diskpart.js
npm-shrinkwrap.json
package.json

This reverts commit 47fc1b7357bdb9e9aa8e2d7476690435087d984e
in order to prevent a possible regression, until properly investigated
and fixed.
Changelog-Entry: Revert using native binding to clean disks on Windows

Revert "feat(lib): Use win-drive-clean instead of diskpart"

---

lib/gui/app/modules/image-writer.js
lib/gui/app/pages/finish/templates/success.tpl.html
lib/sdk/writer/index.js

This fixes a state where the success screen would display
zero succeeded and zero failed devices if verification was
turned off. This could occur due to the "done" event being
emitted before the next progress event could set the relevant data.

fix(gui): Fix zero-zero devices when verify is disabled

---

lib/gui/app/pages/finish/templates/success.tpl.html

We remove success screen dots that are zero, which mainly means that the
error dot disappears as it shouldn't currently be possible to end up
with zero successful devices on that screen.

fix(GUI): remove success screen dots with a quantity of zero

---

lib/shared/store.js
tests/shared/models/selection-state.spec.js

We ensure that drive-image pairs with warnings don't get deselected when
there is only one drive available. This happenened because there was no
check for any previous selected devices. Comes with a test case.
Fixes: https://github.com/resin-io/etcher/issues/2267
Changelog-Entry: Keep single warning-drive-image pairs selected.

fix(store): keep single warning-drives selected

---

lib/gui/app/app.js
lib/gui/app/components/safe-webview.js
lib/gui/app/index.html
lib/gui/app/os/open-external/services/open-external.js

We allow users to pass an env var `ETCHER_DISABLE_EXTERNAL_LINKS` to
disable external links and hide links rendered useless by the change
such as the help icon.
Closes: https://github.com/resin-io/etcher/issues/2246
Closes: https://github.com/resin-io/etcher/issues/2247
Changelog-Entry: Allow disabling links and hiding help link with an env var.

feat(GUI): allow disabling links and hiding help link

---

lib/gui/app/modules/image-writer.js

We make the analytics block into a function `handleErrorLogging` and
use it in the fail event that happens during multi-writes. Previously
error events would only be handled when single drives were flashed.
Changelog-Entry: Fix multi-writes analytics by reusing existing logic in
multi-write events.

fix(GUI): fix multi-writes analytics

---

lib/gui/app/modules/image-writer.js
lib/gui/app/pages/main/controllers/flash.js
lib/gui/app/pages/main/styles/_main.scss
lib/gui/app/pages/main/templates/main.tpl.html
lib/gui/css/main.css
lib/gui/modules/child-writer.js
lib/sdk/writer/.eslintrc.yml
lib/sdk/writer/index.js

We add a cancel button next to the flash progress bar that gracefully
aborts the flash process.
Closes: https://github.com/resin-io/etcher/issues/1791
Closes: https://github.com/resin-io/etcher/issues/2234
Closes: https://github.com/resin-io/etcher/issues/2245
Changelog-Entry: Add a button to cancel the flash process.

feat(GUI): add button to cancel flash process

---

lib/gui/app/modules/image-writer.js

We add a field `driveAmount` to the flash analytics events in the image
writer.

feat(GUI): add drive quantity to flash analytics

---

lib/gui/app/pages/main/controllers/drive-selection.js
lib/gui/app/pages/main/styles/_main.scss
lib/gui/app/pages/main/templates/main.tpl.html
lib/gui/css/main.css

We add a list of selected drives below the drive selection step, able to
accommodate four lines of drives before scrolling occurs.
Closes: #2263
Changelog-Entry: Show selected drives below drive selection step.

feat(GUI): show selected drives below drive step

---

lib/gui/app/app.js

We add an environment variable `ETCHER_BLACKLISTED_DRIVES` that allows
us to filter certain drives from ever showing up in Etcher with comma
separated device paths, e.g. `/dev/sda,/dev/sdb,/dev/mmcblk0`.
Closes: https://github.com/resin-io/etcher/issues/2264
Changelog-Entry: Allow blacklisting of drives through and environment
variable ETCHER_BLACKLISTED_DRIVES.

feat(GUI): blacklist drives with an env var

---

lib/gui/etcher.js

We enable the `darkTheme` mode for GTK-3 applications (mainly Linux)
that suits Etcher's dark theme better, making the window title bar dark.
Changelog-Entry: Use GTK-3 darkTheme mode.

feat(GUI): use gtk3 dark theme mode

---

lib/gui/app/components/confirm-modal/confirm-modal.js
lib/gui/app/components/confirm-modal/controllers/confirm-modal.js
lib/gui/app/components/confirm-modal/services/confirm-modal.js
lib/gui/app/components/confirm-modal/styles/confirm-modal.scss
lib/gui/app/components/confirm-modal/templates/confirm-modal.tpl.html
lib/gui/app/components/drive-selector/controllers/drive-selector.js
lib/gui/app/components/drive-selector/drive-selector.js
lib/gui/app/components/drive-selector/templates/drive-selector-modal.tpl.html
lib/sdk/adapters/usbboot/index.js

Step 2 until we support installing the drivers from within Etcher. This
also introduces an "Open drive link" Mixpanel event.
See: https://www.raspberrypi.org/documentation/hardware/computemodule/cm-emmc-flashing.md
See: https://github.com/resin-io/etcher/pull/1892
Changelog-Entry: Download usbboot drivers installer when clicking a driverless usbboot device on Windows.

feat(GUI): link to drivers when clicking a driverless usbboot device

---

lib/gui/app/models/local-settings.js

This adds the capability to configure settings via a `.etcherrc` file,
either in the user's home directory, or the current working directory.
The defined settings are merged with localStorage settings, and preceding
configuration files.
If both are present, the current working directory takes precedence.
Changelog-Entry: Add support for configuration files
Connects To: #1356

feat(gui): Add ability to read settings from a config file

---

webpack.config.js

We ensure that paths inside node_modules files are kept untouched, as
currently the RegExp can match 'shared' folders inside those and rewrite
paths, breaking them.

fix(webpack): don't rewrite import paths inside node_modules

---

lib/gui/etcher.js

This fixes the `kiosk` setting always being true, and causing
the operating system's desktop to disappear.

minifix(gui): Only enable Kiosk Mode when FULLSCREEN is set

---

README.md

As [pgp.mit.edu](//pgp.mit.edu) has become extremely unreliable, this switches to
[keyserver.ubuntu.com](//keyserver.ubuntu.com) for retrieval of package keys
Connects To: #1786, #1634, #2009, #2144, #2303, #2317

doc(README): Use ubuntu keyserver for apt-key

---

lib/gui/app/pages/main/controllers/drive-selection.js
lib/gui/app/pages/main/styles/_main.scss
lib/gui/app/pages/main/templates/main.tpl.html
lib/gui/css/main.css
lib/shared/store.js

We introduce an environment variable
`ETCHER_DISABLE_EXPLICIT_DRIVE_SELECTION` that both enables
autoselection of drives and disables explicit drive selection by hiding
the buttons allowing this. All valid drives are autoselected, i.e. any
drive-image pair that does not result in an error, however warnings are
accepted.
Closes: https://github.com/resin-io/etcher/issues/2262
Changelog-Entry: Introduce env var to toggle autoselection of all
drives.

feat(GUI): env var toggle autoselecting all valid drives

---

lib/gui/app/app.js
lib/gui/app/modules/image-writer.js
lib/gui/app/modules/update-lock.js
lib/gui/app/pages/finish/controllers/finish.js
npm-shrinkwrap.json
package.json

This adds functionality to acquire & release the update lock
when running under resinOS, re-using the `ELECTRON_RESIN_UPDATE_LOCK`
environment variable from `resin-electronjs`.
Further this adds the `ETCHER_INTERACTION_TIMEOUT_MS` env var, to
facilitate adjusting the inactivity period required to release the lock.
Connects To: https://github.com/resin-io/etcher/issues/2258

feat(gui): Add resin update lock based on inactivity

---

lib/gui/app/components/update-notifier.js

This disables Etcher checking for updates & showing update notifications
if running under resinOS with update locks enabled
Connects To: #2258

minifix(gui): Don't check for updates when in resin

---

lib/gui/app/modules/analytics.js

This adds the ability to set the Sentry & Mixpanel API tokens
via environment variables.
Connects To: #2329

feat(gui): Add ability to set analytics tokens via env

---

lib/gui/app/modules/drive-scanner.js
lib/gui/app/pages/main/controllers/drive-selection.js
lib/gui/app/pages/settings/controllers/settings.js
lib/gui/app/pages/settings/templates/settings.tpl.html

We hide the unsafe mode option toggle with an env var
`ETCHER_HIDE_UNSAFE_MODE` that also enables unsafe mode.
Closes: https://github.com/resin-io/etcher/issues/2243
Changelog-Entry: Hide unsafe mode option toggle with an env var.

feat(GUI): hide unsafe mode option with env var

---

SUPPORT.md

The key binding for devtools is Ctrl + **Shift** + I and not Ctrl + Alt + I.

Fix devtools key binding for Windows in SUPPORT.md

---

lib/gui/app/components/file-selector/file-selector/file-selector.jsx

We ensure the file-picker is slicing arrays when the localStorage values
aren't available.

fix: ensure file-picker is slicing arrays

---

lib/cli/diskpart.js

This escapes the diskpart script filename when shelling out,
to avoid failure when the username and thus the `os.tmpdir()` path
contains spaces.
Connects To: https://github.com/resin-io/etcher/issues/1991

fix(diskpart): Fix diskpart argv when tmpdir contains spaces

---

lib/gui/css/desktop.css

We ensure that the `-webkit-app-region` attribute is only set to `drag`
on the header element and we explicitly disable it on modals, as this
has unintended behaviour on a non-draggable window with touch-screens.

fix(GUI): restrict webkit drag to header

---

lib/gui/app/app.js
lib/gui/app/components/file-selector/controllers/file-selector.js
lib/gui/app/components/file-selector/file-selector/file-selector.jsx
lib/gui/app/components/file-selector/styles/_file-selector.scss
lib/gui/app/components/file-selector/templates/file-selector-modal.tpl.html
lib/gui/app/models/files.js
lib/gui/css/main.css
tests/gui/models/files.spec.js

- Replace onClick arrow functions in all components that use them for
efficiency reasons: 300-500% speed-up
- Sort by folders and ignore case for better UX
- Remove use of `rendition.Button` in files, leading to a 10-20%
performance increase when browsing files
- Proper sidebar width and spacing
- Recents and favorites are now filtered by existence async for a tiny
performance improvement
- Make Breadcrumbs and Icon pure components to stop frequent re-rendering
- Initial support for array constraints
- Use first constraint as initial path instead of homedir if a
constraint is set
- Use correct design height on modal, `calc(100vh - 20px)`
- Reset scroll position when browsing a new folder
- Fuse Bluebird `.map()` and `.reduce()` in
`files.getAllFilesMetadataAsync`.
- Use `localeCompare`'s …

fix(GUI): file-picker performance and design improvements

---

npm-shrinkwrap.json
package.json
webpack.config.js

This adds `webpack-node-externals` to exclude node_modules,
immensely reducing bundle size and avoiding complex exclusion rules
for the etcher-sdk

fix(webpack): Exclude all node externals / node_modules

---

lib/gui/app/components/file-selector/file-selector/file-selector.jsx

This adds the display of the full filename to the file selector.

feat(gui): Add full filename to file selector

---

lib/gui/app/components/file-selector/file-selector/file-selector.jsx

This adds thin gray borders to the control surfaces in
the file selector for better visual distinction

refactor(gui): Add separating borders to file selector

---

electron-builder.yml

This fixes an issue where the settings model would be missing
from Etcher when packaged, as it's used in two different contexts;
namely the webpack bundle and the main process.
Connects To: #2385

fix(app): Fix settings being unavailable when packaged

---

lib/gui/app/components/file-selector/controllers/file-selector.js
lib/gui/app/components/file-selector/file-selector/file-list.jsx
lib/gui/app/components/file-selector/file-selector/file-selector.jsx
lib/gui/app/components/file-selector/templates/file-selector-modal.tpl.html
lib/gui/app/models/files.js

This adds the ability to restrict the file selection to a given device,
only making its mountpoints accessible.
Connects To: https://github.com/resin-io/etcher/issues/2377

feat(gui): Enable device specific constraints for file selection

---

npm-shrinkwrap.json
package.json

This updates `winusb-driver-generator` to the latest version,
which supports building under VS 2015 and running under Electron 2.0+

upgrade(package): Update winusb-driver-generator

---

package.json

This should cause ResinCI to ignore this repo for npm builds, and just run the basic checks + electron + node-cli pipelines.
Signed-off-by: Jack Brown <jack@resin.io>

resinci: Set private: true in package.json to avoid running npm builds

---

lib/sdk/writer/index.js

This patches validation errors coming form the `blockmap` module to have
the `EVALIDATION` error code, in order to trigger the appropriate code
paths and analytics.

fix(writer): Set EVALIDATION on blockmap checksum errors

---

lib/gui/app/modules/drive-scanner.js
lib/sdk/adapters/index.js
lib/shared/permissions.js

For some reason loading it later didn't work
Changelog-Entry: Load usbboot adapter on start on GNU/Linux if running
as root.

fix(sdk): load usbboot adapter on start

---

lib/gui/app/models/local-settings.js

A previous change erroneously relied solely on `electron` to determine
the user's data directory, which of course, isn't available when running
in the CLI. So this adds a fallback to the same mechanic for CLI should
this code not be loaded in Electron.

fix(cli): Don't use electron to get USER_DATA_DIR in CLI

---

scripts/ci/test.sh

Currently, the Travis CI build is failing due to the fact that
the folder 'generated/etcher' is empty.
The folder is missing because the "make webpack" step is missing
from the travis CI build.
This commit amends that by adding the "make webpack" build step
after linting.

minifix: add "make webpack" to travis-ci build script

---

Makefile
tests/spectron/runner.spec.js

The tilde is not a valid version character in RPM packages, according to
the RPM source code.

Makefile: Don't use tilde in rpm versions

---

lib/gui/app/app.js

This fixes device blacklist handling to also match against
`drive.device` and `drive.raw`, in order to be able to specify devices
lacking a `devicePath`.
Connects to: #2468

gui: Also blacklist match against device & raw path

---

npm-shrinkwrap.json
package.json

This is to avoid running the child-writer twice when the hostname isn't
set in /etc/hosts. See https://github.com/jorangreef/sudo-prompt/pull/76
Signed-off-by: Alexis Svinartchouk <alexis@resin.io>

fix(sudo-prompt): Use a fork of sudo-prompt

---

CHANGELOG.md
npm-shrinkwrap.json
package.json

- Center content independent to window resolution.
- Add electron-native file-picker component.
- Hide unsafe mode option toggle with an env var.
- Use new design background color and drive step size ordering.
- Add a convenience Storage class on top of localStorage.
- Introduce env var to toggle autoselection of all drives.
- Add font-awesome.
- Add support for configuration files
- Use GTK-3 darkTheme mode.
- Add environment variable to toggle fullscreen.
- Allow blacklisting of drives through and environment variable ETCHER_BLACKLISTED_DRIVES.
- Show selected drives below drive selection step.
- Add a button to cancel the flash process.
- Download usbboot drivers installer when clicking a driverless usbboot device on Windows.
- Allow disabling links and hiding help link with an env …

Release v1.4.5

---

lib/sdk/writer/checksum-stream.js

This fixes the digest being a number instead of a buffer.
Signed-off-by: Alexis Svinartchouk <alexis@resin.io>

fix: Provide a Buffer to xxhash.Stream

---

lib/sdk/adapters/blockdevice/index.js
tests/gui/models/available-drives.spec.js
tests/gui/modules/drive-scanner.spec.js

Changelog-entry: Reject drives with null size (fixes pretty-bytes error)

fix(GUI): Reject drives with null size

---

lib/gui/app/components/update-notifier.js

Remove "this" and use "exports" instead
Changelog-entry: Fix update notifier error popping up on v1.4.1->1.4.8

fix(GUI): Fix update notification error

---

README.md

Previously, the section header was a level 3 header, and I changed it to a lever 4 header like all the other install variants so it is the same level header. I also added uninstall instructions like the other sections had.

Updated Chocolatey section of Readme

---

.gitattributes
Makefile
lib/sdk/image-stream/supported.js
tests/shared/supported-formats.spec.js

The `.wic` is a widely used image format in the OpenEmbedded / Yocto
Project ecosystem and is straightforward to be supported.
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

Add `.wic` image extension as supported format

---

README.md

This started out with the intention to fix a typo in the uninstall 
section of Solus, but developed in to a couple improvements to the 
README.

Refinements to the README

---

lib/shared/messages.js
tests/shared/drive-constraints.spec.js

Use "Drive Mountpoint Contains Image" instead as the image may not be on
this drive but on a drive mounted in one of the mountpoins of this
drive.
We still don't want to allow flashing this drive in that situation.
Connects-To: #2281

Change "Drive Contains Image" label.

---

docs/CONTRIBUTING.md

npm 3.10 version is required to install dev tools correctly on Linux.
Signed-off-by: amdomanska <aga@resin.io>

docs: Add info about required npm version

---

webpack.config.js

This saves around 40KiB in generated/gui.js
Changelog-entry: Target electron 3 runtime in babel options

Target electron 3 runtime in babel options

---

lib/gui/app/os/windows-network-drives.js
tests/gui/os/windows-network-drives.spec.js

Changelog-entry: (Windows): Use full path to wmic as some systems don't have it in their PATH

Use full path to wmic as some systems don't have it in their PATH

---

repo.yml

This will cause VB to publish metadata about the repo to its gh-pages
branch on merge
Signed-off-by: Giovanni Garufi <giovanni@balena.io>

Set publishMetadata in repo.yml

---

lib/gui/app/os/windows-network-drives.js

Changelog-entry: (Windows): Fix reading images from network drives when the tmp dir has spaces

Fix reading images from network drives on windows when the tmp dir has spaces

---

npm-shrinkwrap.json
package.json

Changelog-entry: Fix gzipped files verification percentage and dmg verification.

Update etcher-sdk to ^2.0.5

---

README.md

Changelog-entry: waffle.io removal and adding a link to the license

waffle.io removal and adding a link to the license

---

lib/shared/permissions.js

Changelog-entry: Use bash instead of sh for running the elevated process on Linux and Mac
Related to #2970

Use bash instead of sh for running the elevated process on Linux and Mac

---

afterPack.js

Changelog-entry: Don't add --no-sandbox when ELECTRON_RUN_AS_NODE is 1

Don't add --no-sandbox when ELECTRON_RUN_AS_NODE is 1

---

npm-shrinkwrap.json

Changelog-entry: Update drivelist to 8.0.10 to fix parsing lsblk --pairs

Update drivelist to 8.0.10 to fix parsing lsblk --pairs

---

README.md

Changelog-entry: Prefer balena-etcher to etcher-bin on Arch Linux

Prefer balena-etcher to etcher-bin on Arch Linux

---

npm-shrinkwrap.json
package.json

Changelog-entry: Update etcher-sdk to ^4.1.0 to fix issues with some bz2 files

Update etcher-sdk to ^4.1.3 to fix issues with some bz2 files

---

lib/shared/drive-constraints.ts

Changelog-entry: Minor fix - Init isSourceDrive param in correct place

Init param in correct place

---

tests/spectron/runner.spec.ts

The Spectron test that we have that checks that the browser window is
visible fails when ran inside a Windows Docker container.
In particular, the `isVisible()` function returns `false` when running
in a headless Windows machine.
However, the `isMinimized()` function returns `false`, the `isFocused()`
function returns `true`, and we can fetch the expected browser window
bounds, so we can use all those values in conjunction to reformulate the
test case and avoid `isVisible()`.
The results should be pretty much the same, and the assertions will pass
inside Docker Windows containers.

spectron: Make tests pass on Windows Docker containers

---

docker-compose.yml

The fan control functionality has
been moved to the fan-control service.
The fan-control service will detect
the sleep mode and it will cool down
the cpu for 60 seconds after entering
sleep mode
Signed-off-by: Vicentiu Galanopulo <vicentiu@balena.io>

Update screensaver commands

---

lib/gui/app/components/source-selector/source-selector.tsx
lib/gui/modules/child-writer.ts

Fixes basic auth credentials not being present on subsequent requests in https://github.com/balena-io/etcher/issues/3649 but not the issue that multiple requests are made to the same resource.

patch: fix flashing from URL when using basic auth

---

lib/gui/etcher.ts

When the `stagingPercentage` is not set in the `latest*.yml` it should mean 100%
The previous version expected that the property is always present with a value of `0` or `100` was not prepared for `undefined`

patch: Fix auto update

---

after-install.tpl
electron-builder.yml

Add an after-install template file to the configuration to fix the `postinst` script for the Debian package. See electron-builder [LinuxSpecificTargetOptions](https://www.electron.build/generated/linuxtargetspecificoptions). Must hardcode the application directory name in the script because there is not a variable available with the content of 'balenaEtcher', as you can see in the [app-builder-lib source](https://github.com/electron-userland/electron-builder/blob/24e986e664f89b8a41f4e5032709a73d30667f9d/packages/app-builder-lib/src/targets/fpm.ts#L37).
`productFilename`, the variable used historically for the app directory, uses `executableName` due to [this code](https://github.com/electron-userland/electron-builder/blob/24e986e664f89b8a41f4e5032709a73d30667f9d/packages/app-builder-lib/sr …

Fix application directory for Debian postinst script

---

lib/gui/app/models/flash-state.ts

Replacing `send` calls to `invoke` for `enable/disable-screensaver` calls.
Connects-To: https://github.com/balena-io-hardware/EtcherPro-Fleet/issues/27
Signed-off-by: Aurelien VALADE <aurelien.valade@balena.io>
---
- When submitting a review, please pick:
- '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that could be improved).
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance issues, etc).
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want …

Fixing call to electron block screensaver methods invocation

---

README.md

We have frozen etcher at `v1.8.14` and discontinued support for it in Homebrew.

Remove Homebrew instructions

---

.github/workflows/flowzone.yml

Running on ubuntu-latest means you need a more recent version of glibc which breaks on older ubuntu.
Thanks to @theofficialgman for suggesting the fix.

Patch: run linux build on ubuntu-18.04

---

README.md

Due to a race between two patch, 1.10.5 assets are labelled 1.10.3. This dummy PR should fix this.

Dummy update to fix asset version issue

---

.github/workflows/flowzone.yml

as [`18.04` has been removed](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/)
We cannot use `latest` as the glibc version will cause issue with older ubuntu version.

Patch: run linux build on ubuntu-20.04

---

lib/gui/app/components/settings/settings.tsx
lib/gui/app/utils/etcher-pro-specific.ts

Adding EtcherPro device serial number to the Settings modal
Pulls Serial from Supervisor API when available, displays only Serial number when available, otherwise displays only UUID.
Signed-off-by: Aurelien VALADE <aurelien.valade@balena.io>
---
- When submitting a review, please pick:
- '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that could be improved).
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance issues, etc).
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to …

Adding EtcherPro device serial number to the Settings modal

---

lib/gui/app/models/flash-state.ts
lib/gui/app/modules/analytics.ts
lib/gui/etcher.ts

Only makes sense on etcher-pro, polluting sentry with useless reports

fix disabled-screensaver unhandled exception outside balena-electron env

---

package-lock.json
package.json
webpack.config.ts

The Electron version we’re currently using is on Node 14 but this is a step forward to upgrading to a newer Electron and Node version.
Updates etcher-sdk and switches the redundant aws4-axios dependency to just axios.
Also changed bundler to stop trying to bundle wasm files — they must be included inline with JS code as data — and removed some now redundant code.
The crucial changes that enable support are:
1. The update to etcher-sdk@8 where some dependency fixes and updates took place
2. The downgrade and pinning of "electron-rebuild" to v3.2.3 until we’re able to update to Electron >= 14.2. The patch we need to avoid is https://github.com/electron/rebuild/pull/907. Also see: https://github.com/nodejs/node-gyp/issues/2673 and https://github.com/electron/rebuild/issues/913
3. A rule in …

Add support for Node 18

---

lib/gui/app/components/finish/finish.tsx
lib/gui/app/pages/main/MainPage.tsx

Move EFP & Success-banner to https://efp.balena.io
This is the first pass on a better, lighter and faster EFP system.

move EFP & success-banner to efp.balena.io

---

package-lock.json
package.json

To add "accept-encoding: gzip" header to HTTP request.
This prevents proxy on-the-fly decompression.

patch: bump etcher-sdk to 8.3.1

---

package.json

libudev package has changed and cannot be installed if we not update apt cache

patch: add apt-get update in flowzone preinstall

---

.github/actions/publish/action.yml
.github/actions/test/action.yml
lib/gui/app/components/safe-webview/safe-webview.tsx
lib/gui/app/i18n/zh-TW.ts
lib/gui/etcher.ts

Fix opening links from within SafeWebView

---

lib/gui/etcher.ts

For some reason, after clicking the **Flash!** button, ```ready-so-show``` event is being fired. This causes [the code](https://github.com/balena-io/etcher/blob/a42be8ee747f3ecb41305d57f647a082c164e14e/lib/gui/etcher.ts#L192) to give focus to etcher window. On some systems this hides authentification dialog when user is entering their password, which is quite annoying.
Tested on: Kde plasma 5.27.5, Arch Linux
This pr should fix issues https://github.com/balena-io/etcher/issues/3620, https://github.com/balena-io/etcher/issues/3789
Demo:
Before: ![before](https://github.com/balena-io/etcher/assets/42062111/738cc06b-78e9-4a12-8e9f-4ec14c53d7a5)
After: ![after](https://github.com/balena-io/etcher/assets/42062111/d6a195bf-ac3a-422f-9d6d-6ec134255b6e)

Prevent stealing window focus from auth dialog

---

README.md

Update install & uninstall instructions for `.deb` files in `README`. 
Changes:
- On install instructions, use `apt` instead of `dpkg` since `apt` takes care of managing dependencies when installing a `.deb` file.
- On uninstall instructions, removed some of the steps since they're not necessary.

patch: update instructions for installing deb file

---

.github/workflows/flowzone.yml

The `custom_runs_on` array supports multiple runner labels in nested arrays.

Replace deprecated flowzone input tests_run_on

---

forge.config.ts

Prevent the rebuilding of native modules by @electron/rebuild.
This was useless and waste times during the build as those modules are only used in the sidecar using another non-electron version of node (and packaged by pkg).
Now we only rebuild once for the correct target instead of twice.

patch: prevent rebuild of native modules by @electron/rebuild

---

.github/actions/test/action.yml
forge.config.ts
lib/gui/app/models/selection-state.ts
lib/gui/app/modules/analytics.ts
lib/gui/app/modules/progress-status.ts
lib/shared/sudo/windows.ts
npm-shrinkwrap.json
package.json
tests/gui/models/available-drives.spec.ts
tests/gui/models/selection-state.spec.ts
tests/gui/modules/image-writer.spec.ts
tests/gui/modules/progress-status.spec.ts
tests/gui/os/window-progress.spec.ts
tests/shared/drive-constraints.spec.ts
tests/test.e2e.ts
wdio.conf.ts

This is a similar move that what we did from electron-build to electron-forge but for testing.
This tool is more modern, can test the real build e2e (and not only do some partial unit/internal testing).
And removes a lot of complexity (or at least move it out of our way)
Most of the old tests runs fine in the new context (the real unit one).
I actually found and fix a couple bugs that were in the way.
But the more integrated tests are failing, and I temporarily moved them out of the way (the `spec.todo.ts`) as they will become redundant once we have proper E2E.
Once https://github.com/balena-io-modules/etcher-sdk/pull/321 is in, and merged here, we can start adding E2E tests with virtual drives, so that's for a next PR.
Note that this 🐰 has been driven by the ~~bad~~ weird support for ESM …

patch: setup wdio and port most tests

---

lib/gui/app/app.ts
lib/gui/app/components/source-selector/source-selector.tsx

This is a poor man wait while loading to prevent a potential race condition without completely blocking the interface
This should be properly addressed when we do a proper GUI refactoring.

patch: hold request for metadata while waiting for flasher

---

forge.config.ts
lib/gui/app/modules/analytics.ts
lib/gui/etcher.ts
webpack.config.ts

When we switched to electron-forge, we moved the injection of the analytics key to a `readPackageJson` hook.
This properly injects the keys in `package.json`. Unfortunately, the import of package.json is not dynamic and is done at build time by webpack *before* those keys are injected.
To circumvent the problem, this PR replaces the hook with a webpack `definePlugin` which will inject the key in the code at build time (it acts as a search and replace), the keys are not injected in the package.json anymore as that served no other purposes.

patch: fix injection of analytics key at build time

---

webpack.config.ts

Sentry DNS was only set for renderer and not main process.
(it needs both to work)

patch: fix sentry DSN

---

.github/actions/test/action.yml
npm-shrinkwrap.json
package.json

The shrinkwrap has been done on mac which prevent windows specific module to be packaged
This should fix it.

patch: fix missing windows dependency

---

docs/USER-DOCUMENTATION.md
package.json

Closes #4096
Cherry-picked from https://github.com/balena-io/etcher/pull/4226
Thanks to @marcaurele 🙏

patch: remove gconf2 libgconf-2-4 deps

---

.github/actions/publish/action.yml

Cherry-picking https://github.com/balena-io/etcher/pull/4304
---
rpmbuild strips executables by default when generating an rpm packge. This was causing the JavaScript code bundled in the etcher-util file to be removed, causing "Pkg: Error reading from file." whenever etcher-util was called.
This in turn caused balena-etcher to generate the error message `Error: (0, h.requestMetadata) is not a function` when attempting to write an SD card.
This fixes the issue for RPM builds by replacing the `strip` command with `true` so that rpmbuild no longer strips the executables and the embeded code stays intact.
See: https://github.com/balena-io/etcher/issues/4150

patch: etcher-util is corrupted in RPM package

---

npm-shrinkwrap.json
package.json

notable:
- https://github.com/balena-io-modules/etcher-sdk/pull/327
- https://github.com/balena-io-modules/etcher-sdk/pull/326

patch: bump etcher-sdk to 9.1.2

---

.github/workflows/flowzone.yml

This will drop support for ubuntu 20 (which will reach EoL in a few months) hence the major.
Macos upgrade shouldn't have any impact, but is necessary as there's no more macos12 public runner on GH.
https://balena.fibery.io/Work/Project/Bump-Etcher-minimum-supported-OS-to-Ubuntu-22.04-1148

major: build on ubuntu 22 and macos 13

---

lib/gui/app/components/source-selector/source-selector.tsx
lib/gui/app/components/target-selector/target-selector.tsx
lib/gui/app/pages/main/MainPage.tsx

Add informational notice about how to disable analytics collection
Change-type: minor
Fibery: https://balena.fibery.io/Work/Improvement/let-individuals-know-they-can-toggle-off-the-analytics-2564

Add informational notice about how to disable analytics collection
