- package.json
- tests/browser/modules/drive-scanner.spec.js
- tests/browser/modules/image-writer.spec.js
- tests/browser/modules/path.spec.js
- tests/browser/modules/selection-state.spec.js
The real issue was fixed in
https://github.com/jprichardson/electron-mocha/pull/20
> Remove window.mocha stub

- .jshintrc
- lib/src/dialog.js
- lib/src/drives.js
- lib/src/writer.js
- package.json
- tests/src/dialog.spec.js
- tests/src/drives.spec.js
- tests/src/writer.spec.js
Native promises showed strange behaviour from time to time.
> Use Bluebird instead of native promises

- lib/components/hero-button.html
Fixes: https://github.com/resin-io/herostratus/issues/24
> all: Fix button outline on focus

- build/browser/app.js
- lib/browser/app.js
- lib/browser/modules/image-writer.js
- lib/browser/modules/selection-state.js
- lib/index.html
- lib/src/writer.js
- package.json
Use the `removedrive` for this task:
https://github.com/jviotti/removedrive
Fixes: https://github.com/resin-io/herostratus/issues/40
> Eject Windows drives after successful burning

- build/browser/app.js
- build/css/main.css
- lib/index.html
- lib/scss/main.scss
Currently we say "done" as soon as the progress is equal to 100, however
we don't wait for the drive to be ejected/unmounted.
This commit introduces a new state, called "Finishing..." which is shown
when the progress is 100, but the drive has not been unmounted.
> Add finished state before done

- appveyor.yml
- lib/herostratus.js
Fixes: https://github.com/resin-io/herostratus/issues/33
> Add a global shortcut to open DevTools

- build/browser/app.js
- lib/browser/app.js
- lib/browser/modules/drive-scanner.js
- lib/src/dialog.js
Fixes: https://github.com/resin-io/herostratus/issues/50
> Show error dialogs on JavaScript exceptions

- lib/index.html
Make "AN OPEN SOURCE PROJECT" link to the project's GitHub page and
"RESIN.IO" to the Resin.io website.
> Split footer caption anchor

- build/browser/app.js
- lib/browser/app.js
- lib/browser/modules/drive-scanner.js
- tests/browser/modules/drive-scanner.spec.js
Updated version of https://github.com/resin-io/resin-etcher/pull/70 by @alexandrosm 
Fixes https://github.com/resin-io/resin-etcher/issues/55
> Autoselect the drive if only one drive is present

- build/browser/app.js
- build/css/main.css
- lib/browser/app.js
- lib/browser/modules/image-writer.js
- lib/index.html
- lib/scss/main.scss
- lib/scss/modules/_space.scss
- tests/browser/modules/image-writer.spec.js
Fixes https://github.com/resin-io/resin-etcher/issues/89
> Show burn speed information during write

- build/browser/app.js
- lib/browser/app.js
- lib/browser/modules/image-writer.js
- lib/browser/modules/logger.js
This service prints the exact date and time of the messages.
> Implement a decent debug logger service

- build/browser/app.js
- lib/browser/modules/logger.js
This has the added benefit that services like TrackJS, which deeply
integrate with Angular, will share the messages with the service.
> Make LoggerService use Angular's $log

- build/css/main.css
- lib/css/angular.css
- lib/css/desktop.css
- lib/index.html
- lib/scss/main.scss
These are files that contain static rules that are not likely change nor
require the advanced functionality that SASS requires.
This is the first step towards an attempt to get rid of preprocessor and
use native supported web technologies.
> Convert angular.scss and desktop.scss to plain CSS files

- lib/browser/app.js
- lib/browser/modules/image-writer.js
- lib/index.html
- tests/browser/modules/image-writer.spec.js
This change required re-architecting the way we store the burn state.
> Move burn state log to app controller

- lib/browser/modules/drive-scanner.js
- tests/browser/modules/drive-scanner.spec.js
No need for this extra level of abstraction.
> Inline DriveScannerRefreshService in DriveScannerService

- README.md
See: https://github.com/atom/electron/issues/3666
> Document the need of execution permissions in home directory in Linux

- lib/etcher.js
Fixes: https://github.com/resin-io/etcher/issues/122
> Fix flash of white at startup

- build/css/main.css
- lib/components/hero-button.html
- lib/index.html
- lib/scss/main.scss
- lib/scss/modules/_space.scss
Fixes: https://github.com/resin-io/etcher/issues/74
> Improve "Burn another" screen design

- lib/elevate.js
- package.json
This version contains a fix to allow the module to run on `asar`
packages.
> Upgrade sudo-prompt to v2.2.0

- Makefile
- PUBLISHING.md
- package.json
Partially Fixes: https://github.com/resin-io/etcher/issues/88
> Implement Windows installers

- lib/browser/app.js
> Show progress bar in dock/taskbar

- package.json
None of the functions we were using suffered from breaking changes.
> Upgrade Lodash to v4.5.1

- lib/browser/app.js
- lib/browser/modules/image-writer.js
- lib/browser/modules/settings.js
- lib/partials/settings.html
- lib/partials/success.html
- lib/src/writer.js
> Add a setting to disable auto-unmount on success

- lib/css/angular.css
- lib/css/desktop.css
Fixes: https://github.com/resin-io/etcher/issues/191
> Allow window to be dragged from anywhere

- .travis.yml
Deploy will be done locally for now given security concerns with CI
servers and certificates.
> Remove .travis.yml deploy section

- Makefile
- package.json
- Legal copyright.
- Company name.
- File description.
- Original filename.
- Product name.
- Internal name.
> Add missing package metadata

- .gitignore
- Makefile
- PUBLISHING.md
Fixes: https://github.com/resin-io/etcher/issues/173
> Setup code-signing in Windows

- build/css/main.css
- lib/partials/main.html
- lib/partials/success.html
- lib/scss/components/_button.scss
- lib/scss/main.scss
This will be needed for implementing the drive selector modal.
> Make button element more extensible

- lib/browser/modules/analytics.js
Its hard to attempt to debug or reproduce an issue if we don't know the
version the user is running.
> Log Etcher version in Mixpanel and TrackJS

- build/css/main.css
- lib/browser/app.js
- lib/browser/components/progress-button/directives/progress-button.js
- lib/browser/components/progress-button/styles/_progress-button.scss
- lib/browser/components/progress-button/templates/progress-button.tpl.html
- lib/browser/models/settings.js
- lib/browser/modules/image-writer.js
- lib/browser/pages/settings/templates/settings.tpl.html
- lib/partials/main.html
- lib/scss/components/_alert-ribbon.scss
- lib/scss/main.scss
- lib/scss/modules/_bootstrap.scss
- lib/src/writer.js
- package.json
This feature allows the user to perform a check step to determine if the data that was written to the drive matches exactly the datafrom the original input image file.
This is done by calculating a CRC32 checksum from both the original input image file and what was written to the drive. If they match, the check succeeds.
Fixes: https://github.com/resin-io/etcher/issues/45
> Implement write validation support

- build/css/main.css
> Rebuild pending SASS changes

- gulpfile.js
> Watch sass files in modules/

- build/css/main.css
- lib/scss/main.scss
Fixes: https://github.com/resin-io/etcher/issues/253
> Add subtle hover styling to footer links

- Makefile
- package.json
- scripts/packageignore.js
> Move package ignore list computation to a separate script

- lib/browser/app.js
- lib/browser/utils/dropzone/directives/dropzone.js
- lib/browser/utils/dropzone/dropzone.js
- lib/partials/main.html
- tests/browser/utils/dropzone.spec.js
See https://github.com/electron/electron/blob/master/docs/api/file-object.md
Fixes: https://github.com/resin-io/etcher/issues/279
> Allow to drag and drop an image to the first step

- build/css/main.css
- lib/partials/main.html
- lib/scss/main.scss
Fixes: https://github.com/resin-io/etcher/issues/290
> Add "Change" button links below each step

- lib/browser/app.js
Fixes: https://github.com/resin-io/etcher/issues/310
> Add a Mixpanel event when the application starts

- Makefile
`Squirrel.Mac` works with ZIP packages rather than DMGs.
Fixes: https://github.com/resin-io/etcher/issues/314
> Publish ZIP versions of Etcher.app

- lib/browser/modules/drive-scanner.js
- package.json
> Promisify `drivelist.list()` with `angular-q-promisify`

- lib/browser/components/progress-button/directives/progress-button.js
- lib/browser/os/open-external/directives/open-external.js
> Document directives with JSDoc

- lib/browser/app.js
- lib/browser/components/drive-selector/drive-selector.js
- lib/browser/pages/finish/finish.js
- lib/browser/pages/settings/settings.js
- lib/browser/utils/if-state/if-state.js
> Require ui.router and ui.bootstrap using NPM style

- tests/browser/components/svg-icon.spec.js
> Fix double-quote lint warnings

- lib/index.html
> Link the version string in the footer to the CHANGELOG

- lib/elevate.js
- lib/etcher.js
> Refactor initial elevation routine

- bower.json
We don't distribute the application through bower, and removing stuff
means one less place to be concerned about certain meta-data to be in
sync.
> Remove unnecessary fields from `bower.json`.

- lib/browser/app.js
- package.json
> Distinguish between flash and validation events in Mixpanel

- README.md
- bin/etcher
- lib/cli/cli.js
- lib/cli/etcher.js
- lib/cli/utils.js
- package.json
This PR integrates the Etcher CLI code-wise, but doesn't yet handles the
distribution part of the story.
> Integrate Etcher CLI in the main repository

- README.md
Fixes: https://github.com/resin-io/etcher/issues/291
> Highlight features in README file

- lib/cli/cli.js
- lib/cli/etcher.js
> Implement validation support in Etcher CLI

- package.json
- `electron-mocha`
- `electron-packager`
> Upgrade outdated dependencies

- package.json
Fixes: https://github.com/resin-io/etcher/issues/289
> Upgrade sudo-prompt to v3.1.0

- lib/cli/cli.js
- lib/cli/etcher.js
> Add an option to control unmounting on success in Etcher CLI

- lib/src/writer.js
- package.json
> Upgrade resin-image-write to v4.0.0

- package.json
> Include lib/cli in final package

- lib/cli/cli.js
> Document exit codes in Etcher CLI help

- CONTRIBUTING.md
- README.md
> Move README "Developing" section to CONTRIBUTING.md

- lib/gui/modules/image-writer.js
This is very useful for debugging.
> Show the forked command as a debug analytics message

- lib/gui/modules/image-writer.js
This reverts commit fab2d767b0ae6b0401b428910096af236897973d.
> Revert "Implement writing by spawning the CLI as a child process (#385)"

- appveyor.yml
> Show electron output in Appveyor

- appveyor.yml
> Point NPM to electron in Appveyor to avoid compilation issues

- .travis.yml
- appveyor.yml
> Make sure bower dependencies are installed in CI servers

- build/css/main.css
- lib/cli/etcher.js
- lib/gui/app.js
- lib/gui/modules/image-writer.js
- lib/gui/pages/finish/controllers/finish.js
- lib/gui/pages/finish/finish.js
- lib/gui/pages/finish/templates/success.tpl.html
- lib/gui/scss/components/_label.scss
- lib/gui/scss/main.scss
- package.json
Partly addresses: http://github.com/resin-io/etcher/issues/357
> Display image checksum on success in the CLI

- scripts/build/darwin.sh
- scripts/build/linux.sh
- scripts/build/windows.bat
> Only install production dependencies from build scripts

- scripts/build/darwin.sh
- scripts/build/linux.sh
> Fix indentation in build scripts

- docs/CONTRIBUTING.md
> Add instructions to configure NPM for installation

- docs/CONTRIBUTING.md
- lib/gui/etcher.js
- lib/gui/os/open-external/directives/open-external.js
- lib/gui/utils/path/filters/basename.js
- package.json
- tests/gui/os/open-external.spec.js
- tests/gui/utils/path.spec.js
> Upgrade electron to v1.1.1

- .travis.yml
- appveyor.yml
> Upgrade CI servers NodeJS version

- lib/gui/utils/path/filters/basename.js
- package.json
- tests/gui/os/dropzone.spec.js
> Run linter as part of `npm test`

- scripts/build/darwin.sh
- scripts/build/linux.sh
- scripts/build/windows.bat
> Install NPM dev dependencies during the build

- Etcher.desktop
- scripts/build/linux.sh
- scripts/elevate-linux.sh
Fixes: https://github.com/resin-io/etcher/issues/439
Fixes: https://github.com/resin-io/etcher/issues/412
> Provide a GUI elevation dialog for GNU/Linux

- package.json
> Upgrade drivelist to v3.1.1

- build/css/main.css
- lib/gui/components/update-notifier/styles/_update-notifier.scss
Fixes: https://github.com/resin-io/etcher/issues/442
> Don't show a progress bar in update notifier modal

- docs/ARCHITECTURE.md
- docs/CONTRIBUTING.md
> Write a document explaining Etcher's architecture

- package.json
> Upgrade drivelist to v3.1.2

- README.md
> Update Appveyor badge

- build/css/main.css
- lib/gui/app.js
- lib/gui/modules/image-writer.js
- lib/gui/partials/main.html
- lib/gui/scss/main.scss
- package.json
Fixes: https://github.com/resin-io/etcher/issues/256
> Display ETA during flash and check

- package.json
> Fix package.json key/property spacing

- README.md
> Link README to the roadmap

- lib/gui/app.js
- lib/gui/models/supported-formats.js
- tests/gui/models/supported-formats.spec.js
> Refactor supported image logic to SupportedFormatsModel

- .jscsrc
- lib/gui/components/drive-selector/templates/drive-selector-modal.tpl.html
- lib/gui/models/selection-state.js
- package.json
- tests/gui/models/selection-state.spec.js
Fixes: https://github.com/resin-io/etcher/issues/458
> Show a "Locked" label if the drive is write-protected

- build/css/main.css
- lib/gui/components/drive-selector/styles/_drive-selector.scss
- lib/gui/components/drive-selector/templates/drive-selector-modal.tpl.html
> Move drive selector warning labels below the drive

- lib/gui/css/desktop.css
> Fix application wide vertical scroll bar

- gulpfile.js
- package.json
> chore(gulp): make linter exit with a non-zero code

- lib/gui/models/store.js
- tests/gui/modules/image-writer.spec.js
> test: validate contents of flash state object

- lib/gui/models/store.js
- tests/gui/modules/image-writer.spec.js
> fix: don't throw if state percentage is zero

- npm-shrinkwrap.json
> chore: update shrinkwrap file

- npm-shrinkwrap.json
> chore: update shrinkwrap version

- .travis.yml
- README.md
- SUPPORT.md
- appveyor.yml
- lib/cli/cli.js
We've created a new Gitter channel specifically for Etcher.
> chore: point to the new Gitter channel

- README.md
- docs/ARCHITECTURE.md
- docs/CLI.md
- docs/COMMIT-GUIDELINES.md
- docs/CONTRIBUTING.md
- docs/MAINTAINERS.md
- docs/PUBLISHING.md
- Make sure we use the same tile style.
- Make sure we wrap lines in the same way.
> chore: normalize documentation

- lib/src/child-writer/index.js
- lib/src/child-writer/writer-proxy.js
We were facing quite some issues that involved debugging the writer child
process, which proved to be a very difficult task given the lack of information
we're exposing to the parent.
This is an attempt to improve that situation.
> refactor(GUI): increase writer proxy logging

- CHANGELOG.md
This layout will be used when generating the CHANGELOG with Versionist.
> chore: change CHANGELOG layout to features/fixes/misc

- SUPPORT.md
- Remove mention about Gitter channel covering Resin.io as a whole.
- Wrap text as the other documents.
- Move links to the bottom.
- Encourage users to submit OS/Etcher version and DevTools info.
> docs: revise the SUPPORT.md guide

- lib/gui/partials/main.html
The current error message is a bit blurry. The new one is much more user
friendly and directly guides the user towards a possible "next action".
> minifix(GUI): improve validation error message

- docs/USER-DOCUMENTATION.md
> docs: fix non-sense USER-DOCUMENTATION description

- docs/CONTRIBUTING.md
- docs/PUBLISHING.md
- docs/RUNNING-LOCALLY.md
This file will contain all information necessary to be able to get a
development version of Etcher running locally.
> doc: extract development setup docs into `RUNNING-LOCALLY.md`

- lib/gui/os/dialog/services/dialog.js
- npm-shrinkwrap.json
- package.json
We're interested in the following changes:
- Add `supportUrl` property in `_info/manifest.json`.
- Add `releaseNotesUrl` property in `_info/manifest.json`.
- Add `version` property in `_info/manifest.json`.
- Add `checksum` and `checksumType` properties in `_info/manifest.json`.
Link: https://github.com/resin-io-modules/etcher-image-stream/blob/master/CHANGELOG.md
> upgrade: `etcher-image-stream` to v4.0.0

- docs/CLI.md
- lib/cli/etcher.js
- lib/gui/models/flash-state.js
- lib/gui/models/store.js
- lib/gui/pages/main/controllers/flash.js
- lib/gui/pages/main/templates/main.tpl.html
- lib/src/child-writer/index.js
- npm-shrinkwrap.json
- package.json
- tests/gui/models/flash-state.spec.js
- tests/gui/modules/image-writer.spec.js
This new version stops sending a `passedValidation` boolean property
upon completion and still throws an `EVALIDATION` error when validation
fails.
Such small chance allows us to get rid of lot of complexity related to
handling the `passedValidation` value in the application state.
> upgrade: `etcher-image-write` to v8.0.0

- .travis.yml
- scripts/build/debian/config.json
- scripts/build/debian/etcher-electron.sh
- scripts/build/linux.sh
This adds a "debian" command to the linux build script. It uses
electron-installer-debian to create a debian package.
> chore: add debian packaging

- lib/src/child-writer/writer-proxy.js
We do this for macOS and GNU/Linux for debugging purposes, but we
weren't doing it for Windows.
> refactor(GUI): log elevation command in Windows

- docs/USER-DOCUMENTATION.md
See: https://github.com/resin-io/etcher/issues/413
See: https://github.com/resin-io/etcher/pull/783#issuecomment-256959050
> docs: suggest UNetbootin if user requires setting persistence storage

- README.md
- lib/gui/components/update-notifier/templates/update-notifier-modal.tpl.html
- lib/gui/index.html
- scripts/build/debian/config.json
See: https://github.com/resin-io/etcher/pull/795
> chore: remove www from etcher homepage URL

- docs/USER-DOCUMENTATION.md
Such image seems to require the "Windows 10 IoT Core Dashboard" tools.
See: https://github.com/resin-io/etcher/pull/783#issuecomment-257255185
> docs: add Win 10 IoT to the list of images requiring special treatment

- lib/gui/pages/main/templates/main.tpl.html
- Change "and many more" to "and much more"
See: https://github.com/resin-io/etcher/issues/787
> style(GUI): improve wording of supported extensions label

- docs/ARCHITECTURE.md
This commit notes down the most important technologies used by Etcher,
so that contributors know what they should focus their learning in.
> docs: list of major technologies used by Etcher

- README.md
> docs: add instructions on how to install from Cask and Bintray

- lib/gui/app.js
> chore: update "join us" email to join+etcher@resin.io

- scripts/build/windows.bat
- scripts/windows/sign.bat
> chore: extract code-signing logic from `windows.bat` to `sign.bat`

- .editorconfig
- Makefile
Additionally, we setup an EditorConfig rule to automatically switch to
tab style on Makefile.
> style: convert spaces to tabs in Makefile

- scripts/unix/dependencies-bower.sh
Somehow got missed out when the rest of the scripts got updated
> chore: exit with error code 1 on build script usage section

- Makefile
Just for conciseness and style.
> style: use GNU Make `foreach` instead of a shell for loop

- scripts/unix/dependencies-bower.sh
- scripts/unix/dependencies-npm.sh
See: https://github.com/resin-io/etcher/pull/934#issuecomment-264862767
> chore: symlink manifests in dependencies scripts

- Makefile
- scripts/unix/dependencies-npm.sh
> chore: set msvs version on `dependencies-npm.sh` when running on Windows

- Makefile
> chore: fix small spacing issue in Makefile

- docs/ARCHITECTURE.md
- docs/CLI.md
See: https://github.com/resin-io/etcher/pull/1010
> docs: minor edits to ARCHITECTURE.md and CLI.md

- lib/gui/components/drive-selector/templates/drive-selector-modal.tpl.html
- lib/gui/components/update-notifier/templates/update-notifier-modal.tpl.html
- lib/gui/components/warning-modal/styles/_warning-modal.scss
- lib/gui/css/main.css
Some button texts are all uppercase, while the remaining of them are
capitalised. This commit capitalises all button texts for consistency
purposes.
Fixes: https://github.com/resin-io/etcher/issues/881
Changelog-Entry: Normalize button text casing.
> fix(GUI): normalize button text casing

- lib/gui/components/warning-modal/templates/warning-modal.tpl.html
See: https://github.com/resin-io/etcher/pull/1043
> style(GUI): change WarningModal title to "Attention"

- lib/gui/assets/image.svg
- lib/gui/pages/main/controllers/main.js
- lib/gui/pages/main/templates/main.tpl.html
- tests/gui/pages/main.spec.js
Change the first step to be drive selection and the second step to be
image selection, instead of vice versa as it previously was.
Changelog-Entry: Swap the order of the drive and image selection steps.
> feat(GUI): swap drive and image selection step order

- lib/gui/components/drive-selector/templates/drive-selector-modal.tpl.html
- lib/gui/components/modal/styles/_modal.scss
- lib/gui/css/main.css
- lib/gui/index.html
- lib/gui/pages/main/templates/main.tpl.html
- lib/gui/pages/settings/templates/settings.tpl.html
- lib/gui/scss/main.scss
As per @konmouz's request.
Fixes: https://github.com/resin-io/etcher/issues/881
Changelog-Entry: Capitalize every text throughout the application.
> style(GUI): capitalize every text for consitency purposes

- .travis.yml
- appveyor.yml
- docs/RUNNING-LOCALLY.md
- lib/gui/components/drive-selector/templates/drive-selector-modal.tpl.html
- lib/gui/models/drives.js
- lib/gui/scss/modules/_bootstrap.scss
- lib/image-stream/index.js
- package.json
- scripts/build/docker/Dockerfile-i686
- scripts/build/docker/Dockerfile-x86_64
- scripts/build/docker/Dockerfile.template
- tests/gui/modules/image-writer.spec.js
This tool scans the comments of every source file and reports back
spelling errors.
> chore: integrate codespell and fix existing spelling issues

- lib/gui/components/drive-selector/styles/_drive-selector.scss
- lib/gui/components/modal/styles/_modal.scss
- lib/gui/components/tooltip-modal/templates/tooltip-modal.tpl.html
- lib/gui/components/update-notifier/templates/update-notifier-modal.tpl.html
- lib/gui/components/warning-modal/templates/warning-modal.tpl.html
- lib/gui/css/main.css
- Remove unnecessary `.modal-text` wrapper
- Move drive selector specific styles to `_drive-selector.scss`
> refactor(GUI): unify modal body styles

- README.md
> docs: document supported operating systems and versions

- lib/image-stream/README.md
> docs: add developer documentation to the lib/image-stream module

- lib/gui/components/warning-modal/services/warning-modal.js
- lib/gui/components/warning-modal/templates/warning-modal.tpl.html
- lib/gui/models/supported-formats.js
- lib/gui/os/open-external/open-external.js
- lib/gui/pages/main/controllers/image-selection.js
- lib/shared/messages.js
- tests/gui/models/supported-formats.spec.js
Changelog-Entry: Show warning when user tries to flash a Windows image
Closes: https://github.com/resin-io/etcher/issues/1035
> feat(GUI): warn when atempting to burn Windows images

- dictionary
- lib/gui/app.js
style: fix typo aknowledge -> acknowledge
chore: add aknowledge->acknowledge to dictionary
> Fix typo, add pair to dictionary

- .eslintrc.yml
- lib/gui/models/selection-state.js
- Prefer `@returns` to `@return`
- Prefer `@param` to `@arg`
- Prefer capitalised types
See: https://github.com/resin-io/etcher/pull/1111#discussion_r103483879
> chore: improve JSDoc ESLint rules

- .eslintrc.yml
- lib/child-writer/writer-proxy.js
- lib/cli/errors.js
- lib/gui/models/flash-state.js
- lib/gui/models/selection-state.js
- lib/gui/models/store.js
- lib/gui/models/supported-formats.js
- lib/gui/modules/analytics.js
- lib/gui/modules/drive-scanner.js
- lib/gui/utils/byte-size/byte-size.js
- lib/gui/utils/path/path.js
- lib/image-stream/archive-hooks/zip.js
- lib/image-stream/utils.js
- lib/shared/drive-constraints.js
- lib/shared/robot/index.js
- package.json
- tests/cli/errors.spec.js
- versionist.conf.js
This is one step towards enforcing the linter until we barely have to
check for style issues on code reviews.
> chore: add ESLint Lodash plugin

- lib/gui/app.js
> style(GUI): reduce `eslint-disable no-var` scope

- docs/CONTRIBUTING.md
- lib/gui/components/update-notifier/services/update-notifier.js
- package.json
* fix the command so it actually works - see https://github.com/lucasdemarchi/codespell/issues/101
* check the spelling of more files
* ignore known-binary filetypes
* fix a couple of spelling mistakes it caught
> chore: codespell improvements

- scripts/build/docker/run-command.sh
Fixes `set -u` errors, and prevents variables being set to undefined values
> chore: Fix copying of variables into Docker

- lib/image-stream/index.js
See: https://github.com/resin-io/etcher/pull/1211#issuecomment-288896853
> doc(image-stream): document that .getFromFilePath also resolves metadata

- lib/cli/etcher.js
The current message is short and unfriendly.
Fixes: https://github.com/resin-io/etcher/issues/1125
> style(CLI): improve error message when drive doesn't exist anymore

- npm-shrinkwrap.json
This removes extraneous dependencies from the `npm-shrinkwrap.json` that couldn't be found being used across the codebase.
> chore(package): Remove extraneous dependencies from shrinkwrap

- lib/cli/writer.js
See: https://github.com/resin-io/etcher/pull/1223#discussion_r108707741
> style(CLI): improve drive not large enough message wording

- lib/gui/modules/analytics.js
- npm-shrinkwrap.json
- package.json
This module contains various fallbacks in case `os.userInfo()` doesn't
exist, which does exist in Electron.
> refactor(GUI): get rid of the `username` module

- lib/image-stream/gzip.js
- lib/image-stream/handlers.js
- npm-shrinkwrap.json
- package.json
> refactor(image-stream): get rid of `gzip-uncompressed-size`

- lib/image-stream/archive.js
- lib/image-stream/utils.js
- npm-shrinkwrap.json
- package.json
- tests/image-stream/archive-hooks/zip.spec.js
- tests/image-stream/tester.js
- tests/image-stream/utils.spec.js
> refactor(image-stream): get rid of rindle

- lib/gui/pages/main/controllers/flash.js
> feat(GUI): add analytics image / drive info on flash done / error events

- .travis.yml
- appveyor.yml
This may speed up cloning on CI services by reducing the clone depth.
> chore(ci): Limit git clone depth

- lib/shared/permissions.js
See: https://github.com/resin-io/etcher/pull/1262#discussion_r110541438
> style(shared): fix `given that is` -> `given that it` typo

- lib/gui/app.js
See: https://github.com/resin-io/etcher/pull/1264/files#r110662965
> fix(GUI): correctly reference the `eta` property in `lib/gui/app.js`

- scripts/build/docker/Dockerfile-i686
- scripts/build/docker/Dockerfile-x86_64
- scripts/build/docker/Dockerfile.template
> chore: remove duplicated curl dependency in Dockerfiles

- scripts/build/docker/run-command.sh
> chore: add analytics token environment variables to Docker container

- npm-shrinkwrap.json
- package.json
- https://github.com/resin-io-modules/drivelist/pull/161
- https://github.com/resin-io-modules/drivelist/pull/156
- https://github.com/resin-io-modules/drivelist/pull/153
Changelog-Entry: Various fixes for when drive descriptions contain special characters.
> upgrade: drivelist to v5.0.19

- dictionary
> chore: add another typo to codespell dictionary

- lib/child-writer/index.js
- lib/shared/robot/index.js
- tests/shared/robot.spec.js
See: https://github.com/resin-io/etcher/pull/1295#discussion_r112463686
> refactor(child-writer): add robot commands constant

- docs/MAINTAINERS.md
> docs: clarify how to deal with problematic releases

- lib/child-writer/writer-proxy.js
- tests/shared/permissions.spec.js
See: https://github.com/resin-io/etcher/pull/1351
> refactor: address review comments from #1351

- lib/gui/models/store.js
- lib/shared/file-extensions.js
- tests/gui/models/selection-state.spec.js
- tests/shared/file-extensions.spec.js
See: https://github.com/resin-io/etcher/pull/1343#pullrequestreview-34288142
> refactor: address file-extensions review comments

- package.json
> chore(codespell): add rpi-sdcard to the list of ignored extensions

- lib/gui/models/store.js
- tests/gui/models/flash-state.spec.js
We limit the progress button's label to 100.
Changelog-Type: Limit the progress button's label to 100.
> fix(GUI): limit progress button label to 100

- Makefile
- binding.gyp
- lib/shared/native-module.js
- lib/shared/permissions.js
- scripts/build/dependencies-npm.sh
- src/os/elevate.h
- src/os/win32/elevate.cpp
See: https://github.com/resin-io/etcher/pull/1366
> refactor: address code review comments from #1366

- lib/gui/app.js
- lib/gui/components/drive-selector/controllers/drive-selector.js
- lib/gui/components/drive-selector/drive-selector.js
- lib/gui/components/flash-error-modal/flash-error-modal.js
- lib/gui/components/flash-error-modal/services/flash-error-modal.js
- lib/gui/components/modal/modal.js
- lib/gui/components/modal/services/modal.js
- lib/gui/components/update-notifier/controllers/update-notifier.js
- lib/gui/components/update-notifier/update-notifier.js
- lib/gui/modules/analytics.js
- lib/gui/modules/error.js
- lib/gui/modules/image-writer.js
- lib/gui/os/open-external/open-external.js
- lib/gui/os/open-external/services/open-external.js
- lib/gui/pages/finish/controllers/finish.js
- lib/gui/pages/finish/finish.js
- lib/gui/pages/main/controllers/drive-selection.js
- lib/gui/pages/main/controllers/image-selection.js
- lib/gui/pages/main/controllers/main.js
- lib/gui/pages/main/main.js
- lib/gui/pages/settings/controllers/settings.js
- lib/gui/pages/settings/settings.js
- tests/gui/components/drive-selector.spec.js
We rename `AnalyticsService` to `analytics` and remove its dependency on
Angular.
Changelog-Entry: Rename and de-angularise AnalyticsService to analytics
> refactor(GUI): remove analytics angular dependency

- docs/CLI.md
> docs(CLI): add installation instructions

- docs/CLI-INSTALLATION.md
- docs/CLI.md
As discussed with @craig-mulligan
> docs(CLI): move the CLI installation instructions to a separate page

- .travis.yml
- Makefile
- appveyor.yml
- package.json
- scripts/build/docker/Dockerfile-i686
- scripts/build/docker/Dockerfile-x86_64
- scripts/build/docker/Dockerfile.template
- scripts/build/electron-installer-debian-linux.sh
- scripts/ci/appveyor-deploy.bat
- scripts/ci/appveyor-install.bat
- scripts/ci/appveyor-test.bat
- scripts/ci/ensure-all-node-requirements-available.sh
- scripts/ci/ensure-staged-shrinkwrap.sh
- scripts/ci/travis-install.sh
- scripts/clean-shrinkwrap.js
See: https://github.com/resin-io/etcher/pull/1372
> chore: check that there are no unstaged shrinkwrap changes

- scripts/build/concatenate-javascript.sh
See: https://github.com/resin-io/etcher/pull/1401#pullrequestreview-37459059
> refactor: address review comments from #1401

- scripts/build/electron-installer-debian-linux.sh
I realised this while reviewing #1425  :-)
> chore: Check for the commands used by electron-installer-debian

- README.md
This updates & normalizes the badges in the README to all have
a consistent style and adds a release-badge pointing to the website.
> doc(README): Update & normalize badges

- lib/image-stream/supported.js
- tests/shared/supported-formats.spec.js
Solves #1348, #1361.
Change discussed in #1360 (though this PR does not solve this issue), it is a temporary and simple fix to address part of this issue.
> minor: addition of .sdcard file support

- lib/gui/app.js
- lib/gui/components/drive-selector/controllers/drive-selector.js
- lib/gui/components/drive-selector/drive-selector.js
- lib/gui/components/flash-error-modal/flash-error-modal.js
- lib/gui/components/flash-error-modal/services/flash-error-modal.js
- lib/gui/models/selection-state.js
- lib/gui/pages/finish/controllers/finish.js
- lib/gui/pages/finish/finish.js
- lib/gui/pages/main/controllers/drive-selection.js
- lib/gui/pages/main/controllers/image-selection.js
- lib/gui/pages/main/controllers/main.js
- lib/gui/pages/main/main.js
- tests/gui/components/drive-selector.spec.js
- tests/gui/models/drives.spec.js
- tests/gui/models/selection-state.spec.js
- tests/gui/pages/main.spec.js
We remove the dependency on Angular from SelectionStateModel and rename
it to selectionState.
Changelog-Entry: Remove Angular dependency from selection-state
> refactor(GUI): remove angular dependency from selection-state

- lib/gui/app.js
- lib/gui/modules/drive-scanner.js
- lib/gui/pages/main/controllers/flash.js
- lib/gui/pages/main/main.js
- tests/gui/modules/drive-scanner.spec.js
Remove the Angular dependency from DriveScanner and with it the service,
exposing it through the module directly.
Changelog-Entry: Remove Angular dependency from DriveScanner.
> [WIP] refactor(GUI): remove angular dependency from drive scanner

- scripts/build/dependencies-npm.sh
See: https://github.com/resin-io/etcher/pull/1550/files#r125015773
> chore(npm): move retry options to INSTALL_OPTS

- npm-shrinkwrap.json
- package.json
> upgrade(package): update resin-corvus to 1.0.0-beta.28 

- README.md
> docs(README): add debian repository in one line

- npm-shrinkwrap.json
- package.json
Changelog-Entry: Improve Windows drive detection error codes.
See: https://github.com/resin-io-modules/drivelist/pull/204
> upgrade: drivelist to v5.1.4

- README.md
Fixes: https://github.com/resin-io/etcher/issues/1155
> docs: add chocolatey install instructions

- README.md
See: https://github.com/resin-io/etcher/pull/1703
> docs(README): execution -> executable

- npm-shrinkwrap.json
- package.json
This updates Electron from v1.6.6 to v1.7.9
Changelog-Entry: Update Electron to v1.7.9
> upgrade(package): Update Electron v1.6.6 -> v1.7.9

- lib/shared/sdk/usbboot/index.js
> fix(usbboot): increase device reboot delay a little bit

- lib/start.js
This fixes Electron startup on Windows
> fix(gui): Don't check elevation on start on Windows

- dictionary
- lib/shared/sdk/index.js
>  fix(sdk): Correct "subscribe" typos

- lib/shared/sdk/index.js
> fix(sdk): Remove event listeners on unsubscribe

- lib/gui/app.js
- lib/gui/modules/progress-status.js
- lib/gui/os/window-progress.js
- lib/gui/pages/main/controllers/flash.js
- tests/gui/modules/progress-status.spec.js
- tests/gui/os/window-progress.spec.js
- tests/gui/pages/main.spec.js
We add the progress percentage to the window alongside the status
(validating, flashing).
Closes: #1427
Fixes: #1439
Changelog-Entry: Add the progress and status to the window title.
> feat(GUI): add progress and status to window title

- docs/CONTRIBUTING.md
Changelog-Entry: Add the Python version (2.7) to the CONTRIBUTING doc.
> docs: add python version to contributing

- docs/ARCHITECTURE.md
But I think its still an interesting module to mention.
> etcher-image-stream was moved to the main etcher repo.

- docs/MAINTAINERS.md
> doc(MAINTAINERS): Fix changelog make target, reword screenshot

- npm-shrinkwrap.json
- package.json
> upgrade(ipc): Update node-ipc 8.9.2 -> 9.1.1

- lib/child-writer/writer-proxy.js
> fix(child-writer): Pass parent env during elevation

- lib/shared/s3-packages.js
- tests/shared/s3-packages.spec.js
> fix(s3): Fix EAI_AGAIN error at startup with no internet connection

- lib/gui/app.js
> fix(gui): Re-enable printing progress in console

- dictionary
> chore: add some more typos to the dictionary

- scripts/ci/install.sh
The `pip` command is now `pip2`
> chore(ci): Attempt to fix TravisCI OSX builds

- docs/MANUAL-TESTING.md
> docs: add high level manual testing script

- lib/writer/error-types.js
> fix(writer): Add EBUSY to transient errors on Linux

- npm-shrinkwrap.json
- package.json
> upgrade(package): Bump mountutils 1.2.2 -> 1.3.8

- src/elevator_init.cpp
- src/os/elevate.h
- src/os/win32/elevate.cpp
> minifix(GUI): run elevated process asynchronously on Windows

- docs/MAINTAINERS.md
This updates the maintainers' doc with a little more detail
regarding the release process, to avoid it staying tribal knowledge.
> doc(MAINTAINERS): Elaborate on the process of releasing

- .travis.yml
We will rely on our Concourse instance for that.
> chore: stop testing macOS on Travis CI

- .resinci.json
> chore: declare Concourse node-cli pipeline's entrypoint

- lib/cli/etcher.js
- lib/gui/app/components/drive-selector/controllers/drive-selector.js
- lib/gui/app/pages/main/controllers/flash.js
- lib/gui/app/pages/main/controllers/image-selection.js
- lib/shared/messages.js
We replace the lodash templates with arrow-functions and change the
single-argument object into multiple arguments.
Changelog-Entry: Replace Lodash templates with arrow-functions.
> refactor: replace lodash templates #1810

- lib/gui/etcher.js
- lib/gui/menu.js
This fixes the Developer Tools opening in docked mode by default.
> fix(gui): Fix DevTools opening in docked mode

- lib/gui/app/components/drive-selector/services/drive-selector.js
- lib/gui/app/components/modal/services/modal.js
- lib/gui/app/components/tooltip-modal/services/tooltip-modal.js
- lib/gui/app/components/warning-modal/services/warning-modal.js
We add a descriptive name to modals for analytics and debugging.
Changelog-Entry: Add descriptive name to modals for analytics and
debugging.
> feat(GUI): add descriptive name to modals

- lib/gui/app/components/safe-webview.js
We add log the banner HTTP load event object to the analtytics.
Changelog-Entry: Log the banner load event to analytics.
> feat: log the event status of the banner

- lib/gui/app/app.js
This fixes enabling debug output via the DEBUG env var
> fix(app): Fix enabling debug output

- webpack.config.js
We resolve `.jsx` files such that they get handled by babel and bundled
with webpack.
Changelog-Entry: Resolve JSX files
> feat: resolve jsx files

- .resinci.json
- package.json
We also have to add the generated directory to the final package.
> chore: add "make webpack" as a Concourse build step

- Makefile
> chore: fixup 'distclean' rule to also delete `generated` directory

- scripts/build/architecture-convert.sh
> fix(scripts): Add missing types to architecture-convert.sh usage

- webpack.config.js
> fix(webpack): Fix not resolving .json

- electron-builder.yml
> chore(package): Update copyright years

- docs/CONTRIBUTING.md
Connects-To: https://github.com/resin-io/etcher/issues/2079
> doc(CONTRIBUTING): Add webpack step to instructions

- lib/gui/app/scss/main.scss
- lib/gui/css/main.css
- npm-shrinkwrap.json
- package.json
We replace Helvetica with Roboto as the main font.
Changelog-Entry: Replace Helvetica as the main font with Roboto.
> feat(CSS): use roboto font instead of helvetica

- scripts/ci/ensure-all-node-requirements-available.sh
> chore: Allow namespaced requires to be sanity-checked

- lib/shared/store.js
- tests/shared/models/available-drives.spec.js
Changelog-Entry: Remove stale JSON object plainifying in store
> minifix: remove stale json object plainifying in store

- npm-shrinkwrap.json
- package.json
**Dependencies:**
- pkg 4.1.1 -> 4.3.0
- nan 2.3.5 -> 2.9.2
- bindings 1.2.1 -> 1.3.0
- asar 0.10.0 -> 0.14.2
**TODO:**
Connects To: https://github.com/resin-io/etcher/issues/1990, https://github.com/resin-io/etcher/issues/1697
> upgrade(package): Update release packaging deps

- lib/gui/app/modules/image-writer.js
- lib/gui/app/pages/main/controllers/flash.js
> fix(gui): Fix devices passed to writer

- lib/gui/app/components/drive-selector/controllers/drive-selector.js
- lib/gui/app/modules/progress-status.js
- lib/gui/app/pages/main/controllers/drive-selection.js
- lib/gui/app/pages/main/controllers/flash.js
- lib/gui/app/pages/main/styles/_main.scss
- lib/gui/app/pages/main/templates/main.tpl.html
- lib/gui/css/main.css
- lib/shared/drive-constraints.js
- lib/shared/messages.js
- lib/shared/models/flash-state.js
- lib/shared/models/selection-state.js
- lib/shared/store.js
- tests/gui/modules/progress-status.spec.js
- tests/gui/os/window-progress.spec.js
- tests/gui/pages/main.spec.js
- tests/shared/drive-constraints.spec.js
- tests/shared/models/flash-state.spec.js
- tests/shared/models/selection-state.spec.js
We add some preparatory changes including new utility functions, as well
as changes throughout the codebase that reflect the change from single
drives to a list of drives, given multi-writes is coming.
Changelog-Entry: Various preparatory changes to account for
multi-writes.
> refactor: multi-writes preparatory changes

- npm-shrinkwrap.json
- package.json
**Before:**
**After:**
**Before: Unsafe mode**
**After: Unsafe mode**
Connects To: #1969
> upgrade(package): Bump drivelist 6.0.4 -> 6.1.3

- npm-shrinkwrap.json
- package.json
> upgrade(package): Update winusb-driver-generator to v1.1.7

- lib/gui/app/pages/main/styles/_main.scss
- lib/gui/css/main.css
We ensure the status dots don't move about and stick to their position
by using absolute positioning relative to its parent element.
Changelog-Entry: Fix status dots to their position.
> fix(GUI): fix status dots to their position

- .travis.yml
- README.md
- SUPPORT.md
- appveyor.yml
- docs/PUBLISHING.md
- lib/cli/options.js
We plan to shut down Gitter soon.
> docs: point users to forums instead of Gitter

- npm-shrinkwrap.json
- package.json
This diverts to using a custom webpack branch to resolve
cyclic symlink issues with `enhanced-resolve` on Concourse.
> fix(webpack): Use fixed enhanced-resolve

- package.json
> chore: don't lint frontend files (ie HTML) on the Node CLI pipeline

- .resinci.json
> chore(ci): Update copyright years in .resinci.json

- lib/gui/app/components/drive-selector/templates/drive-selector-modal.tpl.html
Changelog-Entry: Use multi-drive methods with drive-list warning button.
> minifix: use multi-drive methods with drive-list warning button

- lib/gui/app/pages/main/styles/_main.scss
- lib/gui/css/main.css
Changelog-Entry: Add spacing to the drive warning icon.
> minifix: add spacing to drive warning icon

- npm-shrinkwrap.json
- package.json
> upgrade(package): Bump drivelist to v6.1.5

- lib/gui/app/components/progress-button/styles/_progress-button.scss
- lib/gui/css/main.css
We make the progress button blue on verification.
Changelog-Entry: Make the progress button blue on verification.
> feat(GUI): make the progress button blue on verification

- lib/gui/app/modules/image-writer.js
- lib/gui/app/pages/finish/controllers/finish.js
- lib/gui/app/pages/finish/styles/_finish.scss
- lib/gui/app/pages/finish/templates/success.tpl.html
- lib/gui/app/pages/main/styles/_main.scss
- lib/gui/css/main.css
- lib/sdk/writer/index.js
- lib/shared/errors.js
- lib/shared/messages.js
- scripts/html-lint.js
- tests/shared/errors.spec.js
We display the quantity of succeeded and failed devices using status
dots on the finish screen.
Changelog-Entry: Display succeeded and failed device quantities on the
finish screen.
> feat(GUI): display succeeded and failed devices on finish screen

- lib/gui/app/modules/image-writer.js
- lib/gui/modules/child-writer.js
> fix(gui): De-serialize errors from flashResults

- lib/shared/messages.js
- tests/gui/modules/progress-status.spec.js
- tests/gui/os/window-progress.spec.js
- tests/gui/pages/main.spec.js
- tests/shared/messages.spec.js
> minifix: replace succeeded with successful in messages

- docs/MAINTAINERS.md
This adds instructions for submitting Etcher for false positive detection
to Symantec Endpoint Protection.
> doc: Update MAINTAINERS.md with Symantec Whitelisting

- lib/gui/app/app.js
> minifix(GUI): negate predicate to show help icon

- .gitattributes
- lib/gui/app/utils/middle-ellipsis.js
- lib/gui/app/utils/middle-ellipsis/filter.js
> minifix: add jsx files to gitattributes and attribute jviotti

- npm-shrinkwrap.json
- package.json
We add font-awesome icons as this is more in-line with the designs.
Changelog-Entry: Add font-awesome.
> feat(GUI): add font-awesome

- lib/gui/app/models/local-settings.js
- lib/gui/app/models/storage.js
- tests/gui/models/storage.spec.js
We add a class `Storage` and accompanying helper methods that makes
localStorage usage easier.
Changelog-Entry: Add a convenience Storage class on top of localStorage.
> feat(GUI): add convenience localstorage class

- lib/gui/app/os/notification.js
- lib/shared/store.js
This adds a setting to disable desktop notifications, to be controlled
via configuration file
Change-Type: feat
Connects To: #2254
> feat(gui): Add desktop notification setting

- lib/gui/app/components/file-selector/file-selector/file-selector.jsx
- lib/shared/files.js
- tests/shared/files.spec.js
We add a convenience module for file and path operations.
Tests included.
> fix: add missing files module

- .eslintrc.yml
> test(eslint): Fix JSX not being linted

- package.json
- webpack.config.js
> chore(package): Add npm run script for webpack

- lib/gui/app/components/safe-webview.js
- lib/gui/app/pages/finish/styles/_finish.scss
- lib/gui/app/pages/main/styles/_main.scss
- lib/gui/app/scss/main.scss
- lib/gui/css/main.css
We pave way for different sizes of Etcher windows by dynamically
centering the content with flexbox.
Connects-To: #2263
Closes: #2241
Changelog-Entry: Increase the vertical window size to 480px.
> feat(GUI): center content independent to window resolution

- lib/gui/app/scss/main.scss
- lib/gui/css/main.css
> minifix(GUI): move success banner back down

- lib/gui/app/components/file-selector/file-selector/colors.js
- lib/gui/app/components/file-selector/file-selector/file-list.jsx
- lib/gui/app/components/file-selector/file-selector/file-selector.jsx
- lib/gui/app/components/file-selector/file-selector/path-breadcrumbs.jsx
- lib/gui/app/components/file-selector/file-selector/recent-files.jsx
- lib/gui/app/components/file-selector/services/file-selector.js
- lib/gui/app/models/files.js
- lib/gui/app/scss/main.scss
- lib/gui/css/main.css
- npm-shrinkwrap.json
- package.json
This refactors the experimental file picker to avoid fs i/o in as many places as possible to improve performance. Further, rendering performance is improved by avoiding unnecessary element state changes invalidating components. Also, recent files & favorites have been temporarily disabled due to lack of need for Etcher Pro.
Errors / warnings from within the file picker are native OS dialogs, as this is a React component and doesn't have access to the Angular modal controllers / components;
Connects To: https://github.com/resin-io/etcher/issues/2348, https://github.com/resin-io/etcher/issues/1823
> refactor(gui): Refactor file picker fs I/O

- lib/gui/app/models/files.js
> fix(gui): Fix missing promisify in file picker model

- webpack.config.js
This enables production builds for React
> chore(webpack): Set NODE_ENV to production for React / WebPack

- README.md
This adds the required steps to installing and uninstalling Etcher on Solus Linux.
Changelog-Entry: Add instructions for installing and uninstalling on Solus.
> doc(README): add install and uninstall instructions for Solus

- npm-shrinkwrap.json
- package.json
> upgrade(package): Bump drivelist to v6.4.0

- npm-shrinkwrap.json
- package.json
> upgrade(package): Bump mountutils to v1.3.15

- lib/gui/app/app.js
- lib/gui/app/components/drive-selector/controllers/drive-selector.js
- lib/gui/app/components/file-selector/file-selector/file-selector.jsx
- lib/gui/app/components/flash-error-modal/services/flash-error-modal.js
- lib/gui/app/components/modal/services/modal.js
- lib/gui/app/components/safe-webview.js
- lib/gui/app/components/update-notifier.js
- lib/gui/app/models/store.js
- lib/gui/app/modules/image-writer.js
- lib/gui/app/os/open-external/services/open-external.js
- lib/gui/app/pages/finish/controllers/finish.js
- lib/gui/app/pages/main/controllers/drive-selection.js
- lib/gui/app/pages/main/controllers/image-selection.js
- lib/gui/app/pages/main/controllers/main.js
- lib/gui/app/pages/settings/controllers/settings.js
Application session UUID for global app events
Flashing workflow UUID for every flashing session
Refine events for when flashing ends with success/failure count on each flash instance
> fix(GUI): Additional data on events

- lib/gui/etcher.js
- lib/start.js
- package.json
- scripts/ci/install.sh
- webpack.config.js
Build electron the electron main process js file to include internal settings module
Signed-off-by: Lorenzo Alberto Maria Ambrosi <lorenzoa@resin.io>
> fix(webpack): Add etcher.js to webpack build

- lib/gui/app/modules/image-writer.js
Signed-off-by: Lorenzo Alberto Maria Ambrosi <lorenzoa@resin.io>
> fix(GUI): Remove results data from cancel event

- npm-shrinkwrap.json
- package.json
Signed-off-by: Lorenzo Alberto Maria Ambrosi <lorenzoa@resin.io>
> chore: Update drivelist to v6.4.2

- lib/gui/app/components/file-selector/file-selector/file-selector.jsx
Signed-off-by: Alexis Svinartchouk <alexis@resin.io>
> fix(GUI): Add missing 'store' require

- Makefile
- README.md
- docs/MAINTAINERS.md
- tests/spectron/runner.spec.js
depends on: https://github.com/resin-io/etcher-homepage/pull/133
connects to: #2442
> 2442 update package repo info

- npm-shrinkwrap.json
- package.json
- tests/spectron/runner.spec.js
Signed-off-by: Lorenzo Alberto Maria Ambrosi <lorenzoa@resin.io>
> Use fork of node-usb to disable libudev

- CHANGELOG.md
> fix: Correct 1.4.5 release date & remove checklist

- lib/sdk/writer/checksum-stream.js
Signed-off-by: Alexis Svinartchouk <alexis@resin.io>
> fix: Fix 64 bit detection on arm

- lib/gui/app/components/file-selector/controllers/file-selector.js
- tests/spectron/runner.spec.js
> Fix incorrect file constraint path

- .eslintrc.yml
- npm-shrinkwrap.json
- package.json
- tests/spectron/runner.spec.js
> Enable React lint rules

- lib/gui/app/pages/main/styles/_main.scss
- lib/gui/css/main.css
> Put flash cancel button in foreground

- docs/CONTRIBUTING.md
Signed-off-by: Lucian Buzzo <lucian.buzzo@gmail.com>
> docs: fix typo in contributing guidelines

- .gitmodules
- lib/gui/app/components/image-selector/image-selector.jsx
- lib/gui/app/components/image-selector/index.js
- lib/gui/app/pages/main/main.js
- lib/gui/app/pages/main/templates/main.tpl.html
- lib/gui/app/styled-components.js
- npm-shrinkwrap.json
- package.json
Add Image Selector component using React and Rendition library
Change-type: minor
Signed-off-by: amdomanska <aga@resin.io>
> refactor(GUI): Image Selector Button

- versionist.conf.js
Changelog-entry: Modify versionist.conf.js to match new internal commit guidelines
> fix(versionist): Adapt versionist.conf.js to new guidelines

- lib/gui/app/components/featured-project/featured-project.jsx
- lib/gui/app/components/featured-project/index.js
- lib/gui/app/components/progress-button/progress-button.jsx
- lib/gui/app/components/reduced-flashing-infos/index.js
- lib/gui/app/components/reduced-flashing-infos/reduced-flashing-infos.jsx
- lib/gui/app/components/safe-webview/index.js
- lib/gui/app/components/safe-webview/safe-webview.jsx
- lib/gui/app/components/svg-icon/svg-icon.jsx
- lib/gui/app/models/store.js
- lib/gui/app/pages/main/controllers/main.js
- lib/gui/app/pages/main/main.js
- lib/gui/app/pages/main/styles/_main.scss
- lib/gui/app/pages/main/templates/main.tpl.html
- lib/gui/app/scss/main.scss
- lib/gui/app/scss/modules/_theme.scss
- lib/gui/app/styled-components.js
- lib/gui/css/main.css
- lib/gui/etcher.js
Changelog-entry: Added featured-project while flashing
> feat(GUI): Add featured-project component

- lib/gui/app/index.html
Signed-off-by: Chris Crocker-White <chriscw@balena.io>
> Update URLs in GUI to balena

- .gitmodules
This switches over the sub module to using https instead of ssh. It simplifies a lot for people packaging the application and you won't need to have ssh configured correctly. 👍
> Use https for fetching sub modules

- lib/gui/app/components/safe-webview/safe-webview.jsx
> Use explicit names for safe-webview events

- lib/gui/app/components/safe-webview/safe-webview.jsx
> Remove forwarding of SafeWebview console messages

- .eslintrc.yml
- lib/gui/app/components/flash-another/flash-another.jsx
- lib/gui/app/components/flash-another/index.js
- lib/gui/app/components/flash-results/flash-results.jsx
- lib/gui/app/components/flash-results/index.js
- lib/gui/app/components/reduced-flashing-infos/reduced-flashing-infos.jsx
- lib/gui/app/index.html
- lib/gui/app/pages/finish/controllers/finish.js
- lib/gui/app/pages/finish/styles/_finish.scss
- lib/gui/app/pages/finish/templates/success.tpl.html
- lib/gui/app/pages/main/main.js
- lib/gui/app/pages/main/styles/_main.scss
- lib/gui/app/scss/components/_button.scss
- lib/gui/app/scss/main.scss
- lib/gui/app/styled-components.js
- lib/gui/app/theme.js
- lib/gui/css/main.css
- npm-shrinkwrap.json
- package.json
Changelog-entry: Added React component for the Flash Another button
> Restyle success screen and enlarge UI elements

- lib/gui/app/pages/finish/styles/_finish.scss
- lib/gui/app/pages/finish/templates/success.tpl.html
- lib/gui/css/main.css
It somehow got lost in the last release, so I restored it as seen in the designs.
> Restored offline success-banner style

- lib/gui/app/pages/main/templates/main.tpl.html
> ProgressBar.disabled prop is a boolean

- package.json
> Update winusb-driver-generator to 1.2.4

- npm-shrinkwrap.json
- package.json
> Update node-gyp to 3.8.0

- lib/gui/app/components/file-selector/file-selector/file-selector.jsx
- lib/gui/app/models/files.js
- npm-shrinkwrap.json
- package.json
Enable the experimental file picker if you want to test this
```json
{
"fileBrowserConstraintPath": "/dev/sda",
"experimentalFilePicker": true
}
```
in `~/.config/balena-etcher/config.json`
> Dont use drivelist directly

- Makefile
- versionist.conf.js
Signed-off-by: Giovanni Garufi <giovanni@balena.io>
> [WIP] Remove lodash use from versionist.conf.js

- versionist.conf.js
> Enable versionist editVersion

- docs/CONTRIBUTING.md
> Add missing step for submodule init & update

- lib/gui/app/modules/image-writer.js
- lib/gui/app/os/dropzone/directives/dropzone.js
- lib/gui/app/os/window-progress.js
- lib/gui/app/pages/main/controllers/image-selection.js
- npm-shrinkwrap.json
- package.json
> 1.5.x fixes

- npm-shrinkwrap.json
Changelog-entry: Update ext2fs to 1.0.27
> upgrade(ext2fs): Update ext2fs to 1.0.27

- lib/gui/app/modules/image-writer.js
> Use APPDIR from env in the child writer

- .resinci.json
> Update electron-builder scripts

- npm-shrinkwrap.json
- package.json
Changelog-entry: Show the correct logo on usbboot devices on Ubuntu
> etcher-sdk: Upgrade to 1.3.11

- .gitattributes
- repo.yml
Signed-off-by: Giovanni Garufi <giovanni@balena.io>
> Add repo.yml

- CHANGELOG.md
- repo.yml
Signed-off-by: Giovanni Garufi <giovanni@balena.io>
Changelog-entry: Automatically publish github release from CI
> Set publish: github in repo.yml

- lib/gui/app/modules/analytics.js
Changelog-entry: Fix error when config.analytics was undefined
> Fix error when config.analytics was undefined

- npm-shrinkwrap.json
- package.json
Changelog-entry: Update resin-corvus to ^2.0.3
> Update resin-corvus to ^2.0.3

- lib/gui/app/modules/analytics.js
> Add sample property to Mixpanel events

- lib/gui/app/components/safe-webview/safe-webview.jsx
> New parameter in webview for opt-out analytics

- .gitattributes
- CODEOWNERS
- Makefile
Changelog-entry: Export NPM_VERSION variable in Makefile
> Export NPM_VERSION variable in Makefile

- npm-shrinkwrap.json
- package.json
- patches/allow-electron-forks-of-modules-that-use-pre-gyp.patch
Changelog-entry: Downgrade electron 4.1.5 -> 3.1.9
> Downgrade electron 4.1.5 -> 3.1.9

- npm-shrinkwrap.json
- package.json
Changelog-entry: Update etcher-sdk to ^2.0.9
> Update etcher-sdk to ^2.0.9

- npm-shrinkwrap.json
- package.json
Changelog-entry: Bump react dependency to v16.8.5
> Bump react to v16.8.5

- README.md
Changelog-entry: Add mention to usbboot compatibility
Signed-off-by: Carlo Maria Curinga carlo@balena.io
> add mention to usbboot devices support

- .eslintrc.yml
- npm-shrinkwrap.json
- package.json
- scripts/clean-shrinkwrap.js
Changelog-entry: Add clean-shrinkwrap script to postshrinkwrap step
> Add clean-shrinkwrap script to postshrinkwrap step

- lib/gui/app/os/windows-network-drives.js
- lib/shared/permissions.js
- lib/shared/utils.js
- npm-shrinkwrap.json
- package.json
- tests/shared/permissions.spec.js
> Fix elevation on windows when the path contains "&" or "'"

- npm-shrinkwrap.json
Changelog-entry: Update ext2fs to 1.0.29
> Update ext2fs to 1.0.29

- lib/gui/etcher.js
Changelog-entry: Make window size configurable
> Make window size configurable

- npm-shrinkwrap.json
- package.json
Changelog-entry: Update sudo-prompt to ^9.0.0
> Update sudo-prompt to ^9.0.0

- repo.yml
> Trigger update for 1.5.52

- .editorconfig
- Makefile
- npm-shrinkwrap.json
- package.json
- tsconfig.json
- webpack.config.js
Changelog-entry: Allow typescript files
> Allow typescript files

- npm-shrinkwrap.json
- package.json
> Update etcher-sdk to ^2.0.13

- lib/gui/app/modules/image-writer.js
Changelog-entry: Fix entrypoint when options are passed to electron
> Fix entrypoint when options are passed to electron

- docs/_config.yml
> docs: Remove leftover GH-pages configuration file

- lib/gui/app/components/safe-webview/safe-webview.jsx
This simplifies debugging of the content loaded by Etcher,
including analysis of loaded analytics libraries.
Signed-off-by: Roman Mazur <roman@balena.io>
> Catch console log messages from SafeWebView

- npm-shrinkwrap.json
Signed-off-by: Matthew McGinn <matthew@balena.io>
> ext2fs: upgrade ext2fs to 1.0.30

- npm-shrinkwrap.json
> Update drivelist to 8.0.9

- FAQ.md
Much needed file in order to generate the FAQ section for the website using Landr
Changelog-entry: Introduce an FAQ file
Signed-off-by: Dimitrios Lytras dnlytras@gmail.com
> docs: Introduce an FAQ file

- lib/gui/app/pages/main/DriveSelector.tsx
- lib/gui/app/pages/main/Flash.tsx
- npm-shrinkwrap.json
- package.json
Signed-off-by: Stevche Radevski <stevche@balena.io>
> Add husky and lint-staged to run linting on commit

- lib/gui/app/pages/main/MainPage.tsx
- lib/gui/app/scss/main.scss
- lib/gui/css/main.css
Signed-off-by: Stevche Radevski <stevche@balena.io>
> Fix layout when flashing

- lib/gui/app/components/settings/settings.tsx
- lib/gui/app/os/open-external/services/open-external.js
- npm-shrinkwrap.json
- package.json
Changelog-entry: Add version in settings modal
> Add version in settings modal

- npm-shrinkwrap.json
- package.json
- webpack.config.js
Changelog-entry: Update resin-corvus to 2.0.5
> Update resin-corvus to 2.0.5

- repo.yml
> Trigger update for 1.5.71

- lib/gui/app/models/leds.ts
Fixes: #3056 #3057 #3058 #3060
Changelog-entry: Initialize leds object map
> Initialize leds object map

- lib/gui/app/components/image-selector/image-selector.tsx
- lib/shared/permissions.ts
- npm-shrinkwrap.json
- package.json
> Update etcher-sdk to ^2.0.17

- afterPack.js
- webpack.config.ts
> Fix start script

- repo.yml
Changelog-entry: Trigger update for v1.5.81
> Trigger update for v1.5.81

- repo.yml
Changelog-entry: Add staging percentage for v1.5.81
> Add staging percentage for v1.5.81

- lib/gui/app/pages/main/MainPage.tsx
Changelog-entry: Fix theme warnings
> Fix theme warnings

- lib/shared/drive-constraints.ts
Fixes: #3160
Changelog-entry: Fix undefined image from DriveCompatibilityWarning
> Fix undefined image from DriveCompatibilityWarning

- lib/gui/etcher.ts
Changelog-entry: Fix content not loading when the app path contains special characters
> Fix content not loading when the app path contains special characters

- npm-shrinkwrap.json
- package.json
Changelog-entry: Workaround elevation bug on Windows when the username contains an ampersand
> Workaround elevation bug on Windows when the username contains an ampersand

- scrutinizer.json
> Rollback to v1.5.109

- lib/gui/app/components/drive-selector/drive-selector.tsx
- lib/gui/app/css/main.css
> Change some border colors to have higher contrast

- npm-shrinkwrap.json
- package.json
Update etcher-sdk from 5.1.12 to 5.2.1
> Update etcher-sdk from 5.1.12 to 5.2.1

- README.md
> Update readme for new PPA provider

- CODEOWNERS
- Makefile
- lib/gui/app/components/drive-selector/drive-selector.tsx
- lib/gui/app/components/source-selector/source-selector.tsx
- lib/gui/app/components/target-selector/target-selector.tsx
- lib/gui/app/models/leds.ts
- lib/gui/app/pages/main/MainPage.tsx
- lib/shared/drive-constraints.ts
- npm-shrinkwrap.json
- tests/shared/drive-constraints.spec.ts
- webpack.config.ts
- webpack.dev.config.ts
> patch: Select drive on list interaction rather than modal closing

- lib/gui/etcher.ts
Signed-off-by: Peter Makra <peter@balena.io>
> patch: fixed open from browser on windows

- lib/shared/permissions.ts
resolves #3648
Signed-off-by: Peter Makra peter@balena.io
> patch: fix mesage of null

- package-lock.json
- package.json
- repo.yml
> patch: updated electron to 12.2.3

- README.md
> patch: fix usb-device-boot link in README

- .github/workflows/winget.yml
This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.
Before merging this:
1. Please add a GitHub token with `public_repo` scope as a repository secret and rename the secret name in the workflow.
2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @balena-io.
> patch: Publish release to WinGet (Windows Package Manager)

- .github/actions/finalize/action.yml
> Only run finalize on Linux runners

- .github/actions/finalize/action.yml
- .github/actions/publish/action.yml
> Avoid duplicate releases

- .github/actions/finalize/action.yml
> Update release notes on finalize

- .github/actions/finalize/action.yml
- .github/actions/publish/action.yml
> Build targets individually

- .github/actions/finalize/action.yml
- .github/actions/publish/action.yml
> Generate release notes with git

- .github/actions/always/action.yml
- .github/actions/publish/action.yml
- .github/actions/test/action.yml
* on PR syncs, delete draft releases on Linux runners only
* delete draft releases when unmerged PRs are closed
> CI: generalise artefact handling

- lib/gui/app/models/flash-state.ts
> testing renovate

- .github/actions/publish/action.yml
Signed-off-by: Edwin Joassart edwin.joassart@balena.io
> Fix missing analytics token

- .github/workflows/flowzone.yml
> Allow external contributors

- .github/workflows/flowzone.yml
> Enable repository configuration

- lib/gui/app/components/settings/settings.tsx
> Patch: expose trim ext{2,3,4} setting

- lib/gui/app/components/settings/settings.tsx
- lib/gui/app/i18n/en.ts
> Patch: replaced plain text with i18n in settings

- .github/workflows/winget.yml
patch: introducing github actions
winget release, EP auto update, release build
> patch: introducing github actions (WinGet)

- lib/gui/app/i18n/en.ts
> Patch: made trim setting more readable

- electron-builder.yml
- package-lock.json
- package.json
Fix https://github.com/balena-io/etcher/issues/3899
> patch: update copyright in electron-builder

- lib/gui/app/i18n.ts
- lib/shared/catalina-sudo/sudo.ts
> patch: fixed mac sudo on other languages

- lib/gui/app/i18n/en.ts
- lib/gui/app/utils/etcher-pro-specific.ts
- lib/gui/etcher.ts
- lib/shared/utils.ts
- webpack.config.ts
Remove the check for an updated configuration from the server.
> Remove configuration remote update

- lib/gui/etcher.ts
> revert auto-update feature

- docs/PUBLISHING.md
Add reference to etcher-efp in publishing.md
> Add reference to etcher-efp in publishing.md

- docs/FAQ.md
> add-flash-with-etcher-to-docs

- README.md
- lib/gui/app/pages/main/MainPage.tsx
replace https://github.com/balena-io/etcher/pull/4021
> Patch: Fix support link

- .github/actions/publish/action.yml
- .github/actions/test/action.yml
- .github/workflows/flowzone.yml
Also ensure we are generating unique artifact names on upload.
See: https://github.com/product-os/flowzone/pull/827
> Update actions/upload-artifact to v4

- lib/gui/app/app.ts
- lib/gui/app/modules/image-writer.ts
> fix: typos

- .github/actions/publish/action.yml
- forge.config.ts
This fixes the windows signature process to use the new digicert process which complies with Microsoft requirements.
> patch: fix windows signature

- .prettierrc.js
- lib/gui/app/css/main.css
Fix the configuration of balena-lint & fix linting
> patch: configure prettier in the project to use balena-lint config

- .github/actions/test/action.yml
idem, but without the typo and in draft while I test this time ;)
> patch: fix missing windows dependency

- .github/workflows/flowzone.yml
> Replace deprecated Flowzone inputs

- .github/actions/publish/action.yml
This fixes the issue with syncing digicert's certificate before signing for windows
> patch: fix signin for windows

- .github/actions/test/action.yml
- docs/MAINTAINERS.md
- docs/MANUAL-TESTING.md
- lib/gui/app/app.ts
- lib/gui/app/components/drive-selector/drive-selector.tsx
- lib/gui/app/components/finish/finish.tsx
- lib/gui/app/components/safe-webview/safe-webview.tsx
- lib/gui/app/components/settings/settings.tsx
- lib/gui/app/components/source-selector/source-selector.tsx
- lib/gui/app/components/target-selector/target-selector.tsx
- lib/gui/app/i18n/en.ts
- lib/gui/app/modules/analytics.ts
- lib/gui/app/modules/image-writer.ts
- lib/gui/app/os/open-external/services/open-external.ts
- lib/gui/app/pages/main/Flash.tsx
- npm-shrinkwrap.json
- package.json
- webpack.config.ts
Removes usage analytics code (keep sentry crash reports)
[Fibery](https://balena.fibery.io/Work/Project/remove-unused-analytics-from-etcher-1224)
> patch: remove analytics code
